### ISSUE TITLE
Large candidate-search spreadsheet exports causing CPU spikes

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#1040]
Turns out one cause of our 100% CPU spikes are spreadsheet exports from candidate search. 

Below is prod monitoring after I requested a 25k export — it pretty much ground to a halt and until I cancelled the export:

<img width="988" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXNXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4bfa86bf0ece7c11e64f4dfc9af2721a1c30e73d/Screenshot%202024-05-27%20at%2011.19.53%E2%80%AFAM.png" alt="Screenshot 2024-05-27 at 11.19.53 AM.png" />

We discussed this in team meeting and these are the first steps to tackle this:
- [x] Test in staging to find a reasonable amount to set as a candidate-limit for exports
- [x] Submit a hot fix PR to implement that limit as a temporary measure
- [x] Review the code to understand better what's causing the performance issue
- [x] Implement a more permanent solution

**Comment by samschlicht** [comment]
Some limit tests:

- 397 candidates: 12s, spike 19%
- 3,543: 1m 26s, spike 10%
- 7,634: 3m 3s, spike 16%
- 9,639: 3m 50s, spike 23%
- 16,450: 6m 37s, spike 25%
- 19,330: 7m 52s, spike 35%
- 26,325: 11m 10s, spike 75%


<img width="998" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0VXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d89a934914d60ab61ae93f191d3ec45e9c9545c0/Screenshot%202024-05-28%20at%201.03.00%E2%80%AFPM.png" alt="Screenshot 2024-05-28 at 1.03.00 PM.png" />

**Comment by samschlicht** [comment]
This problem may be solved by adding `EntityManager.clear()` as for #860. I've tested it in local and it does speed up a bit, but I'm not having the same issue there to begin with, so it's hard to measure conclusively. Will need to merge this into staging and test there, where I can compare to the above results.

Before finalising a PR I'll wait for my hotfix to be merged, since I'll need to remove that code in order for this to work. The branch is `EM-csv-export-fix`.

**Comment by samschlicht** [comment]
I've submitted a PR adding EntityManager but would note that another potential improvement might be to go with a lower page size — 500 seems like a lot of candidates at once, perhaps.

**Comment by samschlicht** [comment]
This has definitely got quicker w EntityManager, though not a huge difference: 27,595 candidates in 10min 40secs (30secs quicker than previously it processed 26,325). There's no increase in individual-page processing duration: 11-12 seconds per 500 candidates throughout.

Most encouragingly, there's no spike in CPU or memory usage:

<img width="1974" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1pJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d217158a3dabc8a18f023d3ac5baec51cf9488e/Screenshot%202024-06-07%20at%204.21.34%E2%80%AFPM.png" alt="Screenshot 2024-06-07 at 4.21.34 PM.png" />

**Comment by samschlicht** [comment]
To be certain, I exported 80,000 candidates: still no CPU/memory spike and no increase in individual-page processing duration. But in the end the sheet didn't export, so I think we may also need to look at the way it's been written. You would also think we could improve the speed a bit.

We can confidently say now, though, that if we were to lift the 3k limit, there's no risk of someone crashing prod with a large request (which is what I managed to do last week).

**Comment by samschlicht** [comment]
Managed to export 164093 candidates in 1hr 23min - no slowdown in individual page processing duration, 12-13 seconds, and no CPU or memory spikes. This time it did download.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTFLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa9f4a3959c130f8522ea6b5a097a900bf911317/Screenshot%202024-06-08%20at%201.57.18%E2%80%AFPM.png" alt="Screenshot 2024-06-08 at 1.57.18 PM.png" />

Reminder if you scroll up top, that 25k candidate export pretty much crashed prod, so we've definitely solved the pressing problem. But I think we can also say, as above, that this functionality could use a little bit of tuning to be quicker and more reliable.

[candidates (30).xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXhLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1fa2ee23ea6e8e4324021f61b9afc561b1200b9/candidates%20%2830%29.xlsx)

**Comment by samschlicht** [comment]
@camerojo reckons we may want to keep some kind of limit on this function even if fixed, so I've closed the PR and will but this back in product backlog for another discussion.

At the moment, the limit error is commented out, so something will need to be submitted if we don't want a limitless export function again with the new release.

**Comment by sadatmalik** [comment]
Increasing limit to 5,000.

See the conversation with Hanine for background: https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1720717047179519

This has been applied as a hotfix to production; PR #1182 has been opened to sync up with staging:
