### ISSUE TITLE
AWS Imagine Grants

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1062]

**Comment by sadatmalik** [comment]
UK:
https://docs.google.com/document/d/1Lggis_iUkIRaPazjMiDKfDswsdUQ9TY3Qpbsl-m9NeA/edit

US:
https://docs.google.com/document/d/1kI6pusESqKDfYmfkoNPy06w1QgLZT6PtYpbfrXFLxEM/edit

**Comment by samschlicht** [comment]
Confirming I've read this - nice work and exciting stuff!
