### ISSUE TITLE
System outage logging

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#1089]
At about 9:20am GMT I had to restart the service again. Users started reporting errors at 8:50am.

Something certainly blew out CPU, as can be seen here:

<img width="204" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f1361f8822b561405d3e1aa9081fa843ab7dbbe/Screenshot%202024-06-10%20at%2012.20.22%E2%80%AFPM.png" alt="Screenshot 2024-06-10 at 12.20.22 PM.png" />

**Comment by samschlicht** [comment]
Just noting that there are a few occasions in the logs when this error comes up around 400 times in 2 seconds: 

<img width="1072" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3c418ecaeb4e17da2a7ba75ccac406aafdfd778/Screenshot%202024-06-10%20at%2012.23.39%E2%80%AFPM.png" alt="Screenshot 2024-06-10 at 12.23.39 PM.png" />

**Comment by samschlicht** [comment]
I would guess that the above is just a symptom. There are many other errors happening at the same time. Here is where they all start:

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ceeae88db93ee2895f510c6ddce409ed273b74f4/Screenshot%202024-06-10%20at%2012.47.49%E2%80%AFPM.png" alt="Screenshot 2024-06-10 at 12.47.49 PM.png" />

**Comment by samschlicht** [comment]
Unfortunately I can't find any conspicuous activity. I'm going to keep this issue live for future crashes, and see if we can glean a bit more. But hopefully it improves with the next release!

**Comment by camerojo** [comment]
<img width="1453" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjFOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15b8b395a48886b1e762b50b92c8235bf9ef38bb/Screenshot%202024-06-10%20at%204.18.02%E2%80%AFPM.png" alt="Screenshot 2024-06-10 at 4.18.02 PM.png" />

**Comment by camerojo** [comment]
From last night. The problem with AWS memory monitoring is that it is possible that it misses sudden spikes.
And once you have an out of memory error, the system can be compromised in a number of unpredictable ways that could not actually cause problems until later.

**Comment by samschlicht** [comment]
I'm closing this, as I think we're well aware of the issues we're facing, and the logs aren't yielding any extra info that seems very beneficial. There are a lot of fixes included in the next release, and nothing in the logs is lost if we do decide to take another look.
