### ISSUE TITLE
Cannot delete list. 

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#112]
See https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1687280507762239

**Comment by samschlicht** [comment]
Just an update to this issue after a bit of testing — it is specifically related to lists that have been _published_, after which they can't be deleted. Now I can try to fix it!

**Comment by samschlicht** [comment]
Here's the error message in text rather than pic: `org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [export_column_saved_list_id_fkey]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement`

**Comment by samschlicht** [comment]
Here's the actual issue: Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "saved_list" violates foreign key constraint "export_column_saved_list_id_fkey" on table "export_column"

My working assumption is I need to delete the relevant rows in the 'export column' table before I'll be able to delete the list itself.

**Comment by samschlicht** [comment]
This only required a small change to the entity relationship between the saved_list and export_column, to avoid violating a foreign key constraint which was causing the error.

I had a bit of confusion around 'orphan removal' which I'll read up on to better understand!

**Comment by samschlicht** [comment]
This only required a small change to the entity relationship between the saved_list and export_column, to avoid violating a foreign key constraint which was causing the error.

I had a bit of confusion around 'orphan removal' which I'll read up on to better understand!

**Comment by camerojo** [comment]
Just a note that there is an argument that lists that have published should not be able to be deleted - or, at least, it should not be so easy. These are lists that have been made widely available - so deleting them should be done with consideration.

Similarly it should not be possible to delete submission lists - they are history which should be deleted.
