### ISSUE TITLE
Bug: intake data disappearing, profile reverting to draft

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#1137]
HOTFIX went in to prod on 15th July at about 3.30pm melbourne time

Hello <@U02NYRN57V5> <@U055YR1QT0A>, hope all is well!

There's a candidate (Behrad (Hassan) Amjadi 244772) that I have completed both the mini and full intake last week (Wed 26th) but all info from both intakes was deleted (except the "Destinations" and "Citizenships" in the mini intake). Also the sentence near the title (intake conducted by _person_ on _date_) is removed but it's still present in the "Notes" (attached is a screenshot for your reference). I noticed that he changed his status from "active" to "draft" (I changed it back to "active"), could that be the reason? And if so, is there a way to recover the data or should I reschedule with him another call? Thank you in advance!

cc: <@U04Q0BPA68H>

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1719942698985459?thread_ts=1719942698.985459&cid=C42S4AJ73)

**Comment by samschlicht** [comment]
My Slack reply:
Thanks, @Caroline Cameron, I’ve made a bug issue for this. I’m guessing you’ve clocked off now, so I’ll have a look today — if it is a bug then it’s definitely something we need to address pretty quickly, but I’d note that I had to restart the service due to an OutOfMemory error on Wednesday afternoon, right after the mini intake note was created. The status changes are a little mysterious though, and some of the activity is after the restart, so I’ll do a bit more digging hopefully to put our minds at rest.

(I was going to mention that this hasn’t been reported more than once, but Ribale just reminded us that it has! Will make this a priority, although that still doesn’t rule out the OutOfMemory issues.)

**Comment by samschlicht** [comment]
[Here's](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1718267537096339) Ribale's TC channel message, with replies from John.

As you can see in the current [Slack thread](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1719942698985459?thread_ts=1719942698.985459&cid=C42S4AJ73), Hawraa confirmed that both intakes were completed shortly before a series of OutOfMemory errors that caused me to restart the service on 26 June after Stephanie reported issues. My suspicion is that's directly connected, but I'm going to take a closer look.

**Comment by samschlicht** [comment]
Actually not so sure. The intake took place 1500-1545 BST:


<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnl1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cddb7357d17c2c9c3b5233b22244d4a3f674c2ce/Screenshot%202024-07-03%20at%2011.50.34%E2%80%AFAM.png" alt="Screenshot 2024-07-03 at 11.50.34 AM.png" />


<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZ1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a9032336f8cccb719dca5d8027cadbdfedf6166/Screenshot%202024-07-03%20at%201.23.36%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 1.23.36 PM.png" />



But the first memory error was at 1643 BST:


<img width="1358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZ1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc103bfeefb1a31ce6346c4de433ffb5b9c518c0/Screenshot%202024-07-03%20at%2011.49.41%E2%80%AFAM.png" alt="Screenshot 2024-07-03 at 11.49.41 AM.png" />

Nothing weird is happening in the logs before then.

**Comment by samschlicht** [comment]
From Ribale on Slack:
Hi @Sam Schlicht
I can share the names of two candidates with you:

- Omar El Mahmoud 141451
- Shahida Rahimi 242617

We have redone their intakes. Thank you in advance! FYI @Tiffany Chlala

**Comment by samschlicht** [comment]
Omar El Mahmoud (British Summer Time, UTC +1):


<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2F1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cf5c7db03cf3c7bc1710dca6dfe2aa289d4d62f/Screenshot%202024-07-03%20at%201.05.19%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 1.05.19 PM.png" />

Also some serious service issues (UTC, so the issues had started before the intake, in this case):


<img width="548" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN211QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14c802634f4048927124dc5c0ac094b249062d18/Screenshot%202024-07-03%20at%201.07.44%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 1.07.44 PM.png" />


Although the first OutOfMemory error is not till 1706 BST:


<img width="1262" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGl1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1c7ba31c0e4cba68e2ea17de6fa17b746aa58dd/Screenshot%202024-07-03%20at%201.13.43%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 1.13.43 PM.png" />

**Comment by samschlicht** [comment]
Shahida Rahimi:


<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFN1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02a088dc9c0cb2760f299ece0d52963382089832/Screenshot%202024-07-03%20at%201.12.45%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 1.12.45 PM.png" />


Yep:


<img width="1216" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUd1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8666692b7541044fab5ab6fa3191238ec48bfdaa/Screenshot%202024-07-03%20at%201.16.28%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 1.16.28 PM.png" />

730 BST:


<img width="591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW11QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bac308a60ec9594a4e33b34171decbebb5de6631/Screenshot%202024-07-03%20at%201.17.59%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 1.17.59 PM.png" />

**Comment by samschlicht** [comment]
Hawraa confirmed that the full intake questions were filled in before the OutOfMemory error. I think that one's worth looking into, in that case — it could be another cause!

The status change is curious. First, the candidate goes from draft to pending when they submit their profile (normal); then Hawraa changes them from pending to active before the intake (also normal), but not that unusual):


<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWF2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--213723082da6bfa6af5b7a6128451a7aee5b36d5/Screenshot%202024-07-03%20at%202.04.11%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 2.04.11 PM.png" />


But then, here's the weird thing, the next status changes are from draft to pending and draft to active, with no explanation as to why they reverted to draft. When an admin makes that change, a candidate note is created (there isn't one), and to my knowledge a candidate would have no way of doing it themselves:


<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXV2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e033820c21f9b346cd99e7ca5d565fff218f788/Screenshot%202024-07-03%20at%202.07.13%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 2.07.13 PM.png" />

**Comment by samschlicht** [comment]
Same thing for one of Ribale's candidates:


<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeml2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40de6fa6ac473e194f361196ec02f2202c7226e4/Screenshot%202024-07-03%20at%202.13.41%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 2.13.41 PM.png" />

**Comment by samschlicht** [comment]
Ah, I think I have it here. I went further back in the logs relative to Hawraa's intake, and on the 25th there was an OutOfMemory error at 1146 BST. The service was not restarted in the meantime, so it would still be responsible for the loss of work the following day.


<img width="1198" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1N2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d84aae68e4ba82d27027dc726e6d2674a69ef5dd/Screenshot%202024-07-03%20at%202.19.19%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 2.19.19 PM.png" />

**Comment by samschlicht** [comment]
Given that I've identified preceding OutOfMemory errors for all 3 intakes flagged to us, I think we can put this behaviour down to that, and not look any further into the code at this point. Will report back to group tomorrow.

**Comment by samschlicht** [comment]
I've posted to the channel ([here](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1720015577376569?thread_ts=1719942698.985459&cid=C42S4AJ73)), since a few people are waiting on a response on this.

**Comment by cazcam34** [comment]
Been posting to the Slack thread so copying over here.
Hi @Sam Schlicht thanks so much for handling this all yesterday. Definitely very interesting that there was out of memory errors around all those times! My only thoughts was that it is bizarre that for Hawraa's candidate example, the candidate did have intake fields such as Destinations and Citizenships as saved. These objects are in their own tables and not in the candidate object, so those successfully saved and still exist. So it's like all the fields on the candidate object were nullified, but the other objects were successfully saved. I just did a test in prod and managed to replicate the problem on my test candidate. I filmed a video to show what I did and how this occurred  (excuse the terrible explanation at the end)...  I guess can't help but be suspicious that this kind of overwrite is very similar to the partner overwrite problem that we had with BOSCO

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHV5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c296bae7ef8a3c86b96e26810d42f345da0cc57/Screenshare%20-%202024-07-04%2011_47_51%20AM.mp4)

**Comment by cazcam34** [comment]
Update - Not logging out on CP appears to be the cause of the intake to be overwritten

In the video above I already was logged into the candidate portal and after the intake was changed in the admin portal I just went straight into the candidate portal and updated my occupation and then refreshed the admin portal. So there were **no log outs**!
I did another test where after changing the intake, I went to my candidate portal and logged out. Then I logged back in, updated my occupations and then went to admin portal which also then logged itself out, so logged back in there and then the intake changes were still present!!
So it seems it could be an issue if the candidate remains logged into their portal after the intake has been completed, and without logging out they then do an update, this then somehow overwrites the candidate object with the pre-intake fields?!

I also did the same test with my mobile logged into the CP, and desktop on admin portal. If I am already logged into CP, a change to my intake is made on the AP, and then I add an occupation on my CP, go back to AP and refresh... my intake changes are reverted back.

I also tested AP changing a non-intake field (whatsapp number) doing the same no logout process as above however that did stay the same and didn't get reverted back.

**Comment by cazcam34** [comment]
Ok a little more digging and I think I can see where/how this is occurring.
1) When updating occupations in this scenario we fetch the logged in user from the authenticated logged in user object.
<img width="1920" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFMyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e6ec9bea4bbc6e213cff2b479d144e85a27f14a/Screen%20Shot%202024-07-05%20at%2012.16.48%20pm.png" alt="Screen Shot 2024-07-05 at 12.16.48 pm.png" />
<img width="1590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFcyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8557fd4ce2bc9c9b2c8a5ada464d76f9cab3e66/Screen%20Shot%202024-07-05%20at%2012.17.13%20pm.png" alt="Screen Shot 2024-07-05 at 12.17.13 pm.png" />

2) We then also fetch the candidate FROM that authenticated user object.
<img width="1290" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGEyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5020f9f44d797c2c334ba5a1a6c3e6176a1f97ee/Screen%20Shot%202024-07-05%20at%2012.17.02%20pm.png" alt="Screen Shot 2024-07-05 at 12.17.02 pm.png" />

3) We proceed to create/update the occupations, really just needing to use the id from that candidate object to connect the occupations to that candidate.

4) HOWEVER at the very end, we update that candidate's audit fields to reflect the action of the occupations update... after setting the audit fields we then SAVE that candidate object to the DB... the candidate object that was fetched via the logged in user... who was logged in PRIOR to the intake changes being made!
<img width="1156" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGUyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cde211cbdbc9cb20cb2322e8312fcef2ff08800a/Screen%20Shot%202024-07-05%20at%2012.16.35%20pm.png" alt="Screen Shot 2024-07-05 at 12.16.35 pm.png" />

**Comment by cazcam34** [comment]
The simplest fix here I think is just instead of fetching the candidate off the logged in user object, we just fetch the updated candidate object. 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDIyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d5b8fa8a3783ab62c4bd251e3c37318bcc546bf/Screen%20Shot%202024-07-05%20at%2012.37.49%20pm.png" alt="Screen Shot 2024-07-05 at 12.37.49 pm.png" />

I'll put in a PR with this change in for this particular scenario...however I'm concerned that this bug is happening throughout the code. Looking at this particular AuthService method getLoggedInCandidate() it is used a bit in the code, and if this object is being used to set and save audit fields then it probably needs a wider fix than the one spot as per the PR. Just from an initial glance I can see it's also occurring when a candidate is updating their job experience.
<img width="1357" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUcyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06519f45cd06fa8ff1378d4cdbeaa4b0fa9c2d3a/Screen%20Shot%202024-07-05%20at%2012.44.13%20pm.png" alt="Screen Shot 2024-07-05 at 12.44.13 pm.png" />

**Comment by cazcam34** [comment]
Also replaced this bug in createCandidateJobExperience method, as this also set the candidate using the auth service logged in candidate. Interestingly in updateCandidateJobExperience method it doesn't have this bug, as we are getting the candidate from the candidateJobExperience object, so that must be an updated object which we are then using to set audit fields and saving. I wonder if this way of doing the audit fields could be a good way to standardise?
<img width="1522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1M3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48c7195dd769203c63eb2247dbd925bcea10ae38/Screen%20Shot%202024-07-08%20at%2012.30.26%20pm.png" alt="Screen Shot 2024-07-08 at 12.30.26 pm.png" />

**Comment by cazcam34** [comment]
Another interesting note:
The reason this issue didn't happen when I changed whatsapp number (or any contact details) on old logged in Candidate Portal is that I save the user object first which instead of using the loggedInUser object to fetch the candidate (which causes the issue) i am instead using the updated saved user object which will then have the updated candidate object attached. 
<img width="1415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3U3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c235a8d1eae87b99fac65ec91c447e46d1b544ab/Screen%20Shot%202024-07-08%20at%2012.56.38%20pm.png" alt="Screen Shot 2024-07-08 at 12.56.38 pm.png" />

Update personal information is safe as it fetches a candidate object instead of using the authService logged in object.
<img width="1167" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMys3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76ea148eb40b3b7ec94ab81c5b7a917eaf91022b/Screen%20Shot%202024-07-08%20at%201.00.49%20pm.png" alt="Screen Shot 2024-07-08 at 1.00.49 pm.png" />

**Comment by cazcam34** [comment]
I think we could also be overwriting user objects... in the code example above, if the candidate changes their first or last name or email, those are being saved on a loggedInUser object not an updated user object. from the DB. So if admin change something on their user (e.g. partner, or status or role) and then the old logged in candidate portal user changes something (first name, last name, email) that will overwrite the admin portals changes...

**Comment by cazcam34** [comment]
- [x] Candidate Occupations
- [x] Candidate Experience
- [x] Candidate Educations
- [x] Candidate Certifications
- [x] Candidate Languages
- [x] Other information
- [x] Uploads
