### ISSUE TITLE
Mini Intake: Availability for International Recruitment

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1153]
### Issue Description: Screen Revision for Interest in International Recruitment

**Context:**
This screen was discussed with Noura, Mariam, Zeynep, John, and Sadat on 14 June. The following revisions were agreed upon:

**Revisions:**

1. **Panel Title Change:**
   - Update the panel title to **"Availability for International Recruitment"**.
---
2. **Follow-up Questions for "No" Response:**
   - If the answer to **"Are you available for international employment opportunities now?"** is **NO**, the following follow-up questions should be asked:
     - **Factors preventing immediate availability for international work** (already implemented)
     - **If Other, or if you have additional notes please describe here** (already implemented)
     - **When will you be available?** (New question to be added)
---
3. **Follow-up for "Yes" Response:**
   - If the answer to **"Are you available for international employment opportunities now?"** is **YES**, no more information is required. The question asking for details on potential opportunities - "What type of opportunities are you qualified for?" - is moved to the registration process.
   - A separate ticket will be opened for this in the **Registration Revision v2** epic.
---
4. **Removal of "Unsure" Option:**
   - Remove the **"Unsure"** option from the dropdown, as it no longer makes sense in the context of the revised questions on availability.
   - John has checked in the database and there only 11 candidates who answered "Unsure"
   - For these, we will:
     - Change the data field (avail_immediate) value from "Unsure" to "No"
     - Append a comment in the notes (avail_immediate_notes) : "Candidate is not sure about international opportunities at the moment"
---
5. **Addition of Initial Question:**
   - Add an initial question at the start of the intake to reconfirm the candidate's **"interest"** in international opportunities.
   - The candidate can answer Yes, No, Unsure.
   - Include notes for the interviewer on next steps depending on the candidate answers.
   - This will be addressed in a separate ticket.

**Comment by camerojo** [comment]
> If the answer to "Are you available for international employment opportunities now?" is YES, move the question "What type of opportunities are you qualified for?" to the registration process.

This just reads a little strangely but I know what you mean. Obviously we can't conditionally move a question to registration.

How about changing it to:
If the answer to "Are you available for international employment opportunities now?" is YES, no more information is required. The question asking for details on potential opportunities - "What type of opportunities are you qualified for?" - is moved to the registration process.

Other than that, this looks good to me @sadatmalik

**Comment by sadatmalik** [comment]
Thanks, @camerojo - I've now amended that in the issue description.

**Comment by camerojo** [comment]
- [x] Change panel name
- [x] Open issue under Registration Revision v2 epic for What type of opportunities - see #700
- [x] Remove unsure option
- [x] Display non empty avail_immediate_job_ops if a response has already been given
- [x] Add availability date avail_date (add to Flyway)
- [x] Do Flyway to convert existing unsure answers
- [x] Append converted unsure notes to any existing notes
- [x] Display availability date if they replied no
- [x] Add new initial question Yes,No,Unsure
- [x] Do Issue for interviewer notes on next steps depending on answer to initial question

**Comment by camerojo** [comment]
- [x] Added to Release Planning Issue for 2.2.2: add translation keys for STAFF_INSTRUCTION.CANDIDATE_UNSURE_INTEREST and STAFF_INSTRUCTION.CANDIDATE_NO_INTEREST (can contain html).
