### ISSUE TITLE
Mini Intake: Interest in International Recruitment

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1155]
**Context:**
This task is complementary to the changes noted in issue #1153. 

In a meeting with Noura, Mariam, Zeynep, John, and Sadat on 14 June, it was agreed to add an additional initial question at the start of the intake process to re-confirm the candidate's interest in international employment opportunities.

**Details:**

1. **New Initial Question:**
   - Add a question at the beginning of the intake process: **"Are you still interested in international employment opportunities?"**
---
2. **Response Options:**
   - The candidate may answer with:
     - **Yes**
     - **No**
     - **Unsure**
---
3. **Guidance Notes for Interviewers:**
   - Include guidance notes for interviewers on how to respond based on the candidate's answer. Mariam and Noura to provide guidance note. John will approve the final wording.

**Comment by camerojo** [comment]
Looks good to me @sadatmalik

**Comment by camerojo** [comment]
This appears to have been blocked waiting for the Guidance notes.

I will get the coding done based on using translation keys for the text - that way we can get this completed. Then the actual guidance text can be updated any time by modifying the translation settings.
