### ISSUE TITLE
Mini Intake: Revisions to Destination Intake and Registration Process

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1156]
**Context:**
In a meeting with Noura, Mariam, Zeynep, John, and Sadat on 5 July, the following revisions were agreed upon:

**Revisions:**

1. 

- [x] **Destination Preferences Question Section:**

   - Add a **"Destination preferences"** question section to the candidate registration process.
   - Move the questions on **destination interest** and associated **notes** from the mini intake to the registration process.
---
2. 

- [x] **Capturing Notes:**

   - Ensure that notes are captured for all responses (Yes, No, and Unsure) in all relevant sections.
   - Currently, notes are not captured for **"No"** responses. This should be rectified.
---
3. 

- [x] **Relatives Questions:**

   - Move the questions regarding relatives, such as **"Do you have family in Australia and if so what is the closest relative?"**, to the relevant country's Visa eligibility checks section.
   - **Note** - a question arose from Zeynep about the feasibility of the Visa eligibility check admin person communicating with the candidate directly to confirm this information. Discussed with John - there are a number of reasons during the Visa eligibility check where the admin will need to contact the candidate, so this will not be an issue. This will be potentially easier to do in the future with JobChats. Remember this is an advanced stage, presumably they are being considered for the job, so we will be in closer communication with the candidate. A process question: Should someone at destination be doing this for scalability reasons?
---
4. 

- [x] **Removal of Destination Panel from Mini Intake:**

   - Remove the **"Destination"** panel from the mini intake. Because the data capture has moved to the registration process + visa eligibility checks.
   - Incorporate the destination preferences information provided during the registration process into the **General** tab of the candidate profile.

**Comment by camerojo** [comment]
This looks good to me. @sadatmalik

**Comment by cazcam34** [comment]
UI wise - unique component, it is a one to many , however we are wanting to create all candidate destinations at once. Unless we rephrase the question, which countries are you interested in? But then we won't have a notes for each one.
Also seems overkill for each question of are you interested in... to have a save button. 
Discussing with dad, having the form with save on the next button is best and most consistent with the rest of the code. However will process the array of form data on the front end and then call create for each form via a fork join on the front end. This means we keep our backend code simple and standard CRUD.

**Comment by cazcam34** [comment]
- [x] Remove from Mini intake
- [x] Check why the destinations change order in admin portal (UK first, then Aus first then etc)
- [x] Move questions to visa
- [x] Add new translations to release notes
- [x] Destination limit question?
- [x] Locally delete new fields and create flyway
- [x] Question with flyway... there are candidates that may have had their mini intake completed and destinations are added including the family/location fields. However these won't be transferred if there is no visa check for that country as it will need to create one... how do I capture this?!
- [x] Create update flyway (below for review/discussion) as it will be creating alot of new records.
- [x] Wait for Ehsans registration branch to be merged into staging so I can resolve conflicts

alter table candidate_visa_check add column destination_family text;
alter table candidate_visa_check add column destination_family_location text;

update candidate_visa_check cvc set destination_family = 
    (select family from candidate_destination cd 
        join candidate c on cd.candidate_id = c.id
        where c.id = cvc.candidate_id 
        and cd.country_id = cvc.country_id 
        and family is not null) where cvc.destination_family is null;

update candidate_visa_check cvc set destination_family_location =
                                        (select location from candidate_destination cd
                                        join candidate c on cd.candidate_id = c.id
                                        where c.id = cvc.candidate_id
                                        and cd.country_id = cvc.country_id
                                        and location is not null) where cvc.destination_family_location is null;

**Comment by cazcam34** [comment]
fyi @camerojo for your review. Flyway to create candidate visa checks for the candidate destinations that have a family field to transfer AND that are missing an associated visa check for that candidate/country.
```
-- alot more candidate destinations (60240) than visa checks (843).
-- there are 843 where candidate destinations with matching country/candidate visa check. 
select cd.id, cd.candidate_id, cd.country_id, cd.family from candidate_destination cd
join candidate c on cd.candidate_id = c.id
join candidate_visa_check cvc on c.id = cvc.candidate_id
where cvc.candidate_id = cd.candidate_id
and cvc.country_id = cd.country_id;

-- leaving there 59397 who do not have visa checks associated. 59397 + 843 = 60240 the total candidate destinations
select * from candidate_destination cd 
where id not in 
(select cd.id from candidate_destination cd 
 join candidate c on cd.candidate_id = c.id
 join candidate_visa_check cvc on c.id = cvc.candidate_id
 where cvc.candidate_id = cd.candidate_id
 and cvc.country_id = cd.country_id);

-- of those there are 29080 which has a family field that needs transferring over to a candidate visa check - therefore needing one created.
select * from candidate_destination cd 
where id not in 
(select cd.id from candidate_destination cd
  join candidate c on cd.candidate_id = c.id
  join candidate_visa_check cvc on c.id = cvc.candidate_id
  where cvc.candidate_id = cd.candidate_id
  and cvc.country_id = cd.country_id) 
and cd.family is not null;

-- this requires the following flyway to insert the rows for the update.
insert into candidate_visa_check (candidate_id, country_id, destination_family)
select candidate_id, country_id, family from candidate_destination cd
where id not in (select cd.id from candidate_destination cd
                             join candidate c on cd.candidate_id = c.id
                              join candidate_visa_check cvc on c.id = cvc.candidate_id
                              where cvc.candidate_id = cd.candidate_id
                              and cvc.country_id = cd.country_id) 
and cd.family is not null;
```
