### ISSUE TITLE
Evict cached User on save Candidate

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1205]
Thinking some more about what Caroline has been suggesting - I think she is right: when we save a candidate we should evict the corresponding user from the redis cache. Even though Candidate and User are two separate entities, there is an "is a" relation between them. Logically Candidate is a subclass of User - but not in reality.

The User entity has a getCandidate method on it which accesses the associated Candidate (null if the user is not a candidate). That makes sense. There are only a couple of places in the code where a Candidate object is accessed by calling getCandidate on the underlying user - but they are the places which I believe have caused us the problems - which <@UJ45K6M36> has fixed. The problem is that a saved candidate will not update the candidate value cached with the user.

But what if someone uses user.getCandidate again in another part of the code?

Caroline's suggested solution, which I have only just understood, is that when a Candidate is saved, its associated User should be evicted from the cache. Given that a candidate IS a user. That makes sense to me.

[Slack Message](https://refugeejobsmarket.slack.com/archives/C0583HJ9CHM/p1721352318620509?thread_ts=1721352318.620509&cid=C0583HJ9CHM)

**Comment by camerojo** [comment]
Just another thought. If the cache caches not only the User object, but all connected objects - rather than just caching the entity ids of those objects, then we have a broader problem. 

We not only should evict the cache when the associated candidate updates - but all connected objects.

The other alternative is to remove the get X methods from the user object. That way there is no way code can directly retrieve an associated entity from the Redis cache.

For example, get Partner. 

Not sure of the best approach here, but needs thought.

**Comment by sadatmalik** [comment]
**Problem**

The issue arises because when a related entity (e.g., Candidate or Partner) is updated directly in the database, the cached User entity still holds references to the old versions of these entities, leading to stale data being served from the cache.

**Analysis**

Looking at an actual cached User entry, the below fields have been serialised. Consider each one in light of which, when updated, will necessitate a User cache eviction - and can this be a partial cache eviction or is a full cache eviction required.

Possible eviction scenarios:

A: cached user updated: evict single user entry from cache
B: cached user's connected object updated: no reference from the connected object to the cached object: therefore evict all user entries from cache
C: cached user's connected object updated: connected object references cached object: evict single user entry from cache

Which eviction scenario applies to each cached user field:

1. jobCreator: boolean - A
2. readOnly: boolean - A
3. usingMfa: boolean - A
4. approver: org.tctalent.server.model.db.User - B
5. candidate: org.tctalent.server.model.db.Candidate - C
6. email: java.lang.String - A
7. firstName: java.lang.String - A
8. lastLogin: java.time.OffsetDateTime - A
9. lastName: java.lang.String - A
10. mfaSecret: java.lang.String - A
11. partner: org.tctalent.server.model.db.PartnerImpl - B
12. passwordEnc: java.lang.String - A
13. passwordUpdatedDate: java.time.OffsetDateTime - A
14. purpose: java.lang.String - A
15. resetToken: java.lang.String - A
16. resetTokenIssuedDate: java.time.OffsetDateTime - A
17. role: org.tctalent.server.model.db.Role - B
18. selectedLanguage: java.lang.String - A

19. sharedLists: java.util.Set<SavedList> - 
20. sharedSearches: java.util.Set<SavedSearch> -

21. sourceCountries: java.util.Set<Country> - B
22. status: org.tctalent.server.model.db.Status - A
23. username: java.lang.String - A

_Given (4) - whenever a User is updated we need to evict the entire cache - partial cache eviction will not suffice on User updates
Given (5) - whenever a Candidate is update a partial cache eviction of the associated user entry will suffice
Given (11) - whenever a Partner is updated we need to evict the entire user cache - partial cache eviction will not be possible on Partner updates.
Given (17) - whenever a Role is updated we need to evict the entire user cache - partial cache eviction will not be possible on Role updates. NB: Role is an enum - not a JPA entity
Given (21) - whenever a Country is updated we need to evict the entire user cache - partial cache eviction will not be possible on Country updates.
Given (22) - whenever a Status is updated we need to evict the entire user cache - partial cache eviction will not be possible on Status updates. NB: Status is an enum - not a JPA entity_

Additionally, the serialised data includes fields inherited from superclasses:

From org.tctalent.server.model.db.AbstractAuditableDomainObject:

24. createdBy: org.tctalent.server.model.db.User - B
25. createdDate: java.time.OffsetDateTime - A
26. updatedBy: org.tctalent.server.model.db.User - B
27. updatedDate: java.time.OffsetDateTime - A

_Given (24 and 26) - whenever a User is updated we need to evict the entire cache - partial cache eviction will not suffice on User updates_

From org.tctalent.server.model.db.AbstractDomainObject:

28. id: java.io.Serializable - <Long> - n/a - a user's domain ID does not change

For org.tctalent.server.model.db.PartnerImpl:

29. autoAssignable: boolean - B
30. defaultJobCreator: boolean - B
31. defaultPartnerRef: boolean - B
32. defaultSourcePartner: boolean - B
33. jobCreator: boolean - B
34. sourcePartner: boolean - B
35. abbreviation: java.lang.String - B
36. contextJobId: java.lang.Long - B
37. defaultContact: org.tctalent.server.model.db.User - B
38. employer: org.tctalent.server.model.db.Employer - B
39. id: java.lang.Long - B
40. logo: java.lang.String - B
41. name: java.lang.String - B
42. notificationEmail: java.lang.String - B
43. partnerJobRelations: java.util.Set - B
44. registrationLandingPage: java.lang.String - B
45. sflink: java.lang.String - B
46. sourceCountries: java.util.Set - B
47. status: org.tctalent.server.model.db.Status - B
48. websiteUrl: java.lang.String - B

_Given (37) - whenever a User is updated we need to evict the entire cache - partial cache eviction will not suffice on User updates
Given (38) - whenever an Employer is updated we need to evict the entire user cache - partial cache eviction will not be possible on Employer updates
Given (46) - whenever a Country is updated we need to evict the entire user cache - partial cache eviction will not be possible on Country updates_

For org.tctalent.server.model.db.Employer (on partner):

49. country: org.tctalent.server.model.db.Country - B
50. description: java.lang.String - B
51. hasHiredInternationally: java.lang.Boolean - B
52. website: java.lang.String - B
53. name: java.lang.String - B
54. sfId: java.lang.String - B

Given (49) - whenever a Country is updated we need to evict the entire user cache - partial cache eviction will not be possible on Country updates

For org.tctalent.server.model.db.Status:
55. status: java.lang.String - B - see Status notes above

For org.tctalent.server.model.db.Role:
56. role: java.lang.String - B - see Role notes above

For java.util.HashMap:
57. loadFactor: float - n/a
58. threshold: int - n/a

Final note - configure a pre-defined time to live - e.g. 60 seconds for each cached user entry.

**Comment by sadatmalik** [comment]
**Solution 1**

When a connected entity is updated, the cache entry for the Use must also be evicted or updated. For simplicity, opt to evict the cached entity, not update it.

From the above analysis, we have the following conclusions:

Given (4, 24, 26, 37) - whenever a User is updated we need to evict the entire cache - partial cache eviction will not suffice on User updates
Given (5) - whenever a Candidate is updated a partial cache eviction of the associated user entry will suffice
Given (11) - whenever a Partner is updated we need to evict the entire user cache - partial cache eviction will not be possible on Partner updates.
Given (17) - whenever a Role is updated we need to evict the entire user cache - partial cache eviction will not be possible on Role updates. NB: Role is an enum - not a JPA entity
Given (22) - whenever a Status is updated we need to evict the entire user cache - partial cache eviction will not be possible on Status updates. NB: Status is an enum - not a JPA entity
Given (38) - whenever an Employer is updated we need to evict the entire user cache - partial cache eviction will not be possible on Employer updates
Given (21, 46 and 49) - whenever a Country is updated we need to evict the entire user cache - partial cache eviction will not be possible on Country updates

**For implementation:**

- [x] Create failing tests for each JPA scenario
- [x] Whenever these JPA entities are updated evict all user entries from the user cache: User, Partner, Employer, Country
  - [x] User
  - [x] Partner
  - [x] Employer
  - [x] Country
- [x] Whenever these JPA entiries are update evict the single related user entry from the user cache: Candidate
  - [x] Candidate
- [x] Confirm that all JPA tests pass
- [x] Create Unit tests for 2 additional scenario:
  - [x] SavedSearch
  - [x] SavedList
- [x] Implement selective cache eviction logic for these repositories:
  - [x] SavedSearchRepository
  - [x] SavedListRepository
- [ ] Whenever these Role and Status enums are edited, manually flush all entries from the user cache (*)

(*) Configure a pre-defined time to live - e.g. 60 seconds for each cached user entry.

**Comment by sadatmalik** [comment]
**Solution 2**

A simpler solution to consider might be to evict a single user cache entry whenever a User get method is invoked.

**Revised implementation:**

- [ ]  Create failing tests for each JPA scenario
- [ ]  Evict single user entry from cache whenever a use get method is invoked
- [ ]  Confirm that all JPA tests pass

Additionally, configure a pre-defined time to live - e.g. 60 seconds for each cached user entry.

On further thought, this won't work. What we want is to be sure that whenever findByUsername is called on user; the most up to date record is returned - from the cache is fine so long as the cache has not become stale. Evicting the cache entries when we call e.g. getPartner does not guarantee that calling findByUsername will alway return the most up to date record. If getPartner hasn't been called in the interim, findByUsername will continue to return a stale entry from the cache. We do actually require the cache to evict when one of the connected JPA entities is updated in the DB. Thus, back to working Solution 1.

As Martin Fowler is fond of saying, there are only two hard problems in Computer Science, cache invalidation, naming things, and off-by-one errors.

**Comment by sadatmalik** [comment]
All tests passing:

<img width="979" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1pOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2086d51b9e02abaeb9e17065419160bbdf575851/Screenshot%202024-08-12%20at%2017.33.45.png" alt="Screenshot 2024-08-12 at 17.33.45.png" />
