### ISSUE TITLE
Chats registering as unread for user who wrote the unread post

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#1229]

**Comment by samschlicht** [comment]
As a TC user
I only want to see the read dot indicating unread posts when I didn't write the post
So that I'm not clicking 'Mark as read' or visiting said chat unnecessarily

Not sure how well phrased that is, so here's a short vid:



[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1VsQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c757ac8a047c6449418ec98959e86697e38fd5b6/Screen%20sharing%20-%202024-08-01%2012_10_14%20PM.mp4)

**Comment by cazcam34** [comment]
This has been fixed with PR #1412 which was merged in release 2.2.2 (see #1408 for duplicate issue which was addressed)
