### ISSUE TITLE
Sam parental leave handover notes

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#1239]
Things that could possibly come up while I'm away (6 Sep - 1 Nov inclusive).

I'd add that it's always worth checking the Operational Tech Asana project board if you're looking to understand something that I've done in the past: I document pretty much everything on there and if applicable there'll be extra context in the comments, links to useful docs, correspondence, etc.

## SF admin requests
[Here's](https://app.tettra.co/teams/talentbeyondboundaries/pages/salesforce-admin-guides) a Tettra page with clickable links to videos showing how to carry out regular requests.

## Candidate-Data-4 storage limit
Once a month I go [here](https://admin.google.com/ac/drive/manageshareddrives?sort_column=storage_used&sort_direction=desc) (Google Admin console - must be admin) to check that our current Google Drive isn't about to blow through the item cap. On 6 Aug it was 56%. When it gets to 80%, I follow [this process](https://app.tettra.co/teams/talentbeyondboundaries/drafts/3456770/edit#header-fbfvb-monitoring-and-managing-storage-capacity) to set up a new one.

NB: I'm going to set up Candidate-Data-5 before I go, so this unlikely to be an issue, but someone should still be checking the capacity, I reckon.

## Direct DB queries/edits
Every so often I get asked to do these. I've logged the most common ones [here](https://app.tettra.co/teams/talentbeyondboundaries/drafts/3456770/edit#header-28tlg-useful-sql-db-queries).

### TC intake stats
I update these sheets for the previous month's intakes, at the beginning of the next, more or less. 

But I've wondered lately whether they're actually being read, and an item for my list when I get back is to check in with Mariam and Noura again and see whether they're actually needed — and whether we reprise the idea of implementing a better version in the TC.

So, I would suggest just skipping the month that I'm away — but if they're needed for any reason, [here's](https://docs.google.com/spreadsheets/d/1ratxVXHpfhCG46V3wIg1z07UeIS0z3sAdWk8sHJW8AE/edit#gid=0) the sheet. All the SQL is included below the tables, and it's very quick and straightforward to run by replacing the date parameters.

## TC partner access requests & user registration/login issues
I handle all of these. [Here's](https://app.tettra.co/teams/talentbeyondboundaries/pages/talent-catalog-partner-access-user-perspective) the Tettra page for the process from a user perspective and [here](https://app.tettra.co/teams/talentbeyondboundaries/pages/talent-catalog-partner-access-admin-perspective) are some useful vids and links for the admin perspective.

And [here](https://app.tettra.co/teams/talentbeyondboundaries/pages/tc-user-registration-admin) are the generic instructions and template email for registering a new user and some tips for common login issues.

## Google admin
David Fitzrogers handles on- and off-boarding but occasionally I assist with that, and other times there are issues with access to shared inboxes and drives. [Here's](https://app.tettra.co/teams/talentbeyondboundaries/pages/common-google-admin-tasks) a Tettra page for the most common admin tasks.

Current admins are David F (user admin only), Steph, JC, Sadat, and me.

Occasionally I'm asked to set up new Groups for email forwarding or inbox delegation (this is turned on at the individual level, but Groups are a convenient way of adding lots of people at once, and we currently have a few, e.g. for info@). For Groups, just log into the [Google Admin Console](https://admin.google.com/ac/home?hl=en&rapt=AEjHL4PH24QuwBQiGepHCl34vrKlDivc2EFaG8K_qCmrHrQDlFg-s_X-512d31L-hKNcMRF2LGu2-SACAmN0xd0avNojlVrk-UOBZEvTf36R4G4ivY16R0Q) and look at some others I've done — the setup differs depending on the purpose.

## Zapier
I've set up quite a few Zaps for different TBB teams and projects, most of them still running. I expect that requests for new ones will just pause while I'm away, but I've made the whole TC team admins, just in case. The more likely scenario (though it's a very rare occurrence) is that someone wants to make an adjustment to a Zap or something has gone wrong. For that reason I've put everything I've done in the Shared folder, which means it can be viewed and edited by any other admin. The folder names should point you in the right direction. It's all pretty intuitive but where possible, wait till I get back. 

Note that any SF ones might be working in tandem with [SF Flows](https://talentbeyondboundaries.lightning.force.com/lightning/setup/Flows/home) — again, the whole team has access and you should find them quite clearly labelled.

## Misc TBB Tools On- and Off-Boarding
David F handles this but occasionally I assist. Requests are unlikely to come in to the team but nevertheless [here's](https://app.tettra.co/teams/talentbeyondboundaries/pages/misc-tbb-tools-on-and-off-boarding) a Tettra page with instructional vids for the ones that might come up. 

David F and Alec are admins for all these and can enable your access if required — better yet, one of them will handle it! 

_NB: for every tool there are at least two admins other than me. Sadat has access to [Alec's subscription audit](https://docs.google.com/document/d/1PPgbQOuQtzIMxVRzx4Q1uLuHIf83dlLqpODmPi3qvb8/edit#heading=h.yyixmn7nd86q), which provides a good current reference of who that is._

**Comment by sadatmalik** [comment]
@samschlicht can we add some brief handover doco on Zapier as well?

Can we make me, John and Caroline Zapier admins?

**Comment by samschlicht** [comment]
👍 done
