### ISSUE TITLE
Bug with stats "Go to stat" - can't scroll drop down options

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#1283]
Go to stats - run stats. Then click on Go to stat. Can't scroll from drop down options

**Comment by EhsanEhrari** [comment]
Fixed bug by adding the .scroll-dropdown class to ngbDropdownMenu div.
The scroll-dropdown class was missing from ngbDropdownMenu, causing the dropdown content to overflow beyond the visible area without scrolling. 
By adding this class, I enabled the dropdown to have a scrollable area, ensuring that long lists are fully accessible within the fixed height, while preventing the dropdown from affecting the scroll behavior of the entire page.
