### ISSUE TITLE
Spike - SF Staging Environments

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#130]
As an admin user
I would like to have TC staging connect to an SF staging environnments
So that I can freely play around in the staging environment with no risk of inadvertently affecting any live data

**Comment by sadatmalik** [comment]
Investigate what it would take - time and licensing costs - to facilitate a SalesForce and Elasticsearch staging environments

**Comment by sadatmalik** [comment]
Look at Salesforce sandbox

**Comment by samschlicht** [comment]
We can make the same API calls to a SF sandbox as we do to our production version.

Our SF licence only includes a single partial-copy sandbox, but I actually checked and at our current level its storage allowance is enough to include all our records! (5 GB of storage space and a 10,000 record maximum per selected object.) That's fortunate, as a full sandbox licence costs US$8,000. (Although SF said they'd be willing to discuss a discount.) But noting that when we include all TC candidates in SF, it will max out and only some contacts will be included.

Worth noting that one can only refresh a sandbox every 5 days — so, if you're testing a change that makes a mess of the integration, you'd potentially have to wait 5 days to fix it. But those occasions ought to be rare, and it's a vast improvement on our present situation, which is that there's no safe way to check the effect that a SF change will have on the TC integration, and vice versa.

**Comment by samschlicht** [comment]
UPDATE: I was the rubber duck in a session on how we could institute this using our application.yml and AWS staging/prod environment variables. Seems like it would be a relatively light lift for a nice payoff!
