### ISSUE TITLE
Minimal candidate DTO doesn't return candidate opportunities causing bug in show candidates view

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#1302]
List or search doesn't load and returns following error in console.
TypeError: Cannot read properties of undefined (reading 'find')
    at ShowCandidatesComponent.getCandidateOppForThisJob (show-candidates.component.ts:1852:45)

This can be fixed temporarily by adding a ? before the find call see below
`  getCandidateOppForThisJob(candidate: Candidate): CandidateOpportunity {
    return candidate.candidateOpportunities?.find(o => o.jobOpp.id === this.candidateSource.sfJobOpp?.id);
  }`

**Comment by sadatmalik** [comment]
I merged an edit from #1284, which applied the Preview Dto to the show-candidate.component. I've undone that in the linked PR #1308, so once that's approved and merged, it will resolve this issue.
