### ISSUE TITLE
Remember scroll location on the candidate search card scroll

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#1305]
As an admin user,
When I am scrolling down the search card to view something lower down (e.g. languages section under General tab) I want to keep my scroll position when switching between candidates in a list,
So that I am not having to continue to rescroll down when looking at the same section.

I saw there's something called scroll position restoration in angular - worth looking into, I'm not sure if this is going to be possible for our side profile card even but it would be useful.

See how it jumps back up when changing candidates
<img width="1053" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVI1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c04561c03fbd35c388b699879ea9f4f25b7ad81d/Screen%20Shot%202024-08-22%20at%203.33.41%20pm.png" alt="Screen Shot 2024-08-22 at 3.33.41 pm.png" />

<img width="1121" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVY1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2e9946cd86567313e9e9670293bd7b7d130d009/Screen%20Shot%202024-08-22%20at%203.33.06%20pm.png" alt="Screen Shot 2024-08-22 at 3.33.06 pm.png" />

**Comment by samschlicht** [comment]
This was a little bit trickier than anticipate due to unexpected behaviour of ngAfterViewChecked — might be worth a quick show and tell. Working nicely now, though, nice feature idea, @cazcam34!
