### ISSUE TITLE
Bug: Jobs tab on candidate-search-card not opening

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#1307]
On clicking Jobs tab, previous tab's content continues to be shown, and console logs error shown below.

<img width="1128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGQ3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ae86fa18be5800e2f8df679ec0c30695de3bc8c/Screenshot%202024-08-22%20at%2012.58.16%E2%80%AFPM.png" alt="Screenshot 2024-08-22 at 12.58.16 PM.png" />

<img width="1231" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE43Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0aeff97b0105035c734428f30e2644961a165813/Screenshot%202024-08-22%20at%2012.58.38%E2%80%AFPM.png" alt="Screenshot 2024-08-22 at 12.58.38 PM.png" />

**Comment by sadatmalik** [comment]
When merging from #1284, a change was picked up that applied the Preview Dto to the show-candidates.component. 

Preview Dto is safe for browse-candidate-sources but will need further tuning if used in show-candidates. I'll log that as a separate issue.

For now, I've undone the use of previews in show-candidates in the linked PR #1308, which will resolve this issue.
