### ISSUE TITLE
Clarify registration screen

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#131]
As a Candidate
I would like it to be clearer what my email address will be used for
So that I know it will be used as my account username / login

Agree a way with Noura/Zeynep etc. how to convey this info to candidates in the appropriate place with the appropriate wording so that

i) candidates are clear on how their email will be used and will remember what they are inputting in this field
ii) candidates consent to their email address being used for us to contact them regarding their application early on in the registration process - i.e. so we can contact them should they fail to fully complete their registration to remind them to do so

Desirable -
It would be good to send an email verification link to candidates - this would in no way restrict them from continuing with their registration - but it is useful info for admins to have so they can see which email accounts were verified during the registration process and which were not

**Comment by sadatmalik** [comment]
Migrated from Trello -

"Add a note indicating that the email addresses are used as the usernames and candidates will be asked to provide them to log in. Encourage them to remember what they put down"

https://trello.com/c/ZOEw7WGJ/394-add-a-note-indicating-that-the-email-addresses-are-used-as-the-usernames-and-candidates-will-be-asked-to-provide-them-to-log-in

**Comment by sadatmalik** [comment]
Remember to translate any new text!

(Look at Google translate as a first option)

**Comment by zyurdoglu** [comment]
Hi all, here's a mock-up for a potential login screen: [https://www.canva.com/design/DAFy2GEU1hs/DTN3tqBnCQxZpcPoLCFkQw/edit]

This could be step 0 of registration, regular registration can continue from step 1 of 9 "How can we contact you"" where we ask for their phone, WhatsApp etc. HIAS team had recommended asking "alternative email" for when candidates have multiple emails. This might be a good opportunity to add that field if we think it's important.

Let me know if you have any questions!

**Comment by sadatmalik** [comment]
Adding new translations for:

login.button.already

**Comment by sadatmalik** [comment]
- [x] register new account screen
- [x] add consents to register new account screen
- [x] skip new account registration screen if returning to a previous part-complete registration
- [x] don't show step number for step 0
- [x] add new translation labels
- [x] confirm values of existing labels
- [x] update header paragraph text for step 0
- [x] add Already Registered? link
- [x] add privacy policy
- [x] remove account/create-account
- [x] remove unused fields from step 0
- [x] remove unused fields from step 1
- [x] decide on setting email from username in step 0
- [x] test / validate for confirmation password match
- [x] verify all steps save / update candidate registration
- [x] test scenario when returning to an incomplete registration
- [x] Use "Email *" instead of "Username" in new registration screen - issue #526 opened to clarify this
- [x] In Step 1 - show the entered username + the ability to add an alternative email - issue #526 to clarify this
- [x] Make a note of new translations in release notes
- [x] Make a note of updated translations in release notes

New Translations
- [x] LOGIN.BUTTON.ALREADY - "Already registered?"
- [x] REGISTRATION.HEADER.ACCOUNT.EXPLANATION - "To register your profile please create an account. You can log in anytime to update your profile."
- [x] REGISTRATION.HEADER.TITLE.ACCOUNT - "Welcome to Talent Catalog!"
- [x] All new fields will need other language translations - Arabic, others?

Check these translations
- [x] REGISTRATION.CONTACT.LABEL.USERNAME - "Email (username)"
- [x] REGISTRATION.CONTACT.LABEL.PASSWORD - "Create password"
- [x] REGISTRATION.CONTACT.LABEL.PASSWORDCONFIRMATION - "Confirm password"
- [x] REGISTRATION.CONTACT.LABEL.CONTACTCONSENTREGISTRATION - "I consent to being contacted by TBB regarding my registration and employment opportunities."
- [x] REGISTRATION.CONTACT.LABEL.CONTACTCONSENTPARTNERS - "I consent to receive occasional emails from Talent Catalog partners regarding employment and vocational training opportunities for refugees and other displaced people."
- [x] LANDING.PARA3 - "Please read our 
<a target="_blank" href="https://talentbeyondboundaries.org/s/TBB-Talent-Catalog-Privacy-Policy.pdf">
Privacy Policy 
</a> for more information about how your data will be collected, stored and used. By registering with the Talent Catalog you are giving {{partner}} consent to use your data in accordance with the Privacy Policy.
"

**Comment by camerojo** [comment]
As an observation I would be inclined to not use the term username at all. If we just only ever use email, I don't there is any chance for confusion.

**Comment by sadatmalik** [comment]
Preview:

<img width="694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzVzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8726e0206c8ba47d663aeab125c3cb3ff72d8c97/Screenshot%202023-12-18%20at%2017.14.48.png" alt="Screenshot 2023-12-18 at 17.14.48.png" />

**Comment by sadatmalik** [comment]
Opened issue #526 to decide on username / email field usage going forward, including consideration for an alternative email address.
