### ISSUE TITLE
Upgrade Node version

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#1311]
Intellij now supports Angular debugging for Node versions greater than 16.

- [x] After upgrade, update README notes which state that Node version should be 16
- [x] In notes, document required Intellij  start up parameter as recommend in below link

See https://www.jetbrains.com/help/idea/angular.html#ws_angular_debug_app_troubleshooting

**Comment by sadatmalik** [comment]
Note to self - to debug your Angular application you need two run/debug configurations:

An npm configuration to start your application in development mode, as described here:
https://www.jetbrains.com/help/idea/angular.html#angular_running_and_debugging_run

A JavaScript Debug configuration to attach the debugger to the application that is running i development mode:
https://www.jetbrains.com/help/idea/angular.html#angular_debug_via_js_debug_rc
