### ISSUE TITLE
Implement CI/CD Pipeline for Running Unit Tests on Staging Branch

### ISSUE THREAD

**Issue by EhsanEhrari** [talentbeyondboundaries/tbbtalentv2#1332]
I need to set up a CI/CD pipeline to automatically run over 2000 unit tests when code is pushed to the staging branch. If any of the tests fail, the build process should be marked as failed, preventing deployment to staging.

**Comment by EhsanEhrari** [comment]
Per my investigation we have two options for implementing our CI/CD pipeline using GitHub workflows:

1. Separate Angular Test workflow : This approach involves creating a dedicated yml file specifically for running Angular tests. This will result in two workflows running separately.
2. Integrating with the Existing Build Workflow: Alternatively, we can integrate Angular tests into the existing build.yml GitHub workflow. This option would run only one workflow, which would execute the Java build followed by the Angular tests.

Which approach do you think we should pursue? Also, regarding the timing for running tests, should we trigger them on every push, or only when merging into the staging branch or any other branch?

**Comment by sadatmalik** [comment]
Hi @EhsanEhrari, I reviewed the GitHub Actions spending tiers, and just to confirm, public repositories continue to benefit from unlimited free usage for both minutes and storage. This means there’s no cost implication with running workflows on pushes to individual branches, as no charges apply for GitHub Actions usage for our repository.

Just FYI: [GitHub Actions billing](https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-github-actions/about-billing-for-github-actions) page.

**Comment by EhsanEhrari** [comment]
Looks great @sadatmalik, I think as it mentioned there is nothing to be worried about. So, I will go ahead with it.
