### ISSUE TITLE
Unit Test Documentation

### ISSUE THREAD

**Issue by EhsanEhrari** [talentbeyondboundaries/tbbtalentv2#1334]
For maintaining high standards in testing, I will create comprehensive documentation for our testing strategies, tools, and best practices. This will include detailed guides on setting up test environments, using testing tools, and running tests.

**Comment by EhsanEhrari** [comment]
https://docs.google.com/document/d/1G0jvkf6vhl8FY9UPv1qIlZ7Kz_COBYpe/edit?usp=sharing&ouid=103371042357070995237&rtpof=true&sd=true

**Comment by EhsanEhrari** [comment]
https://docs.google.com/document/d/1G0jvkf6vhl8FY9UPv1qIlZ7Kz_COBYpe/edit?usp=sharing&ouid=103371042357070995237&rtpof=true&sd=true

**Comment by camerojo** [comment]
Great resource @EhsanEhrari !

Let's discuss with the team where it should live. Maybe OK as a Google doc. One alternative is in the Github wiki.

**Comment by sadatmalik** [comment]
Very helpful, @EhsanEhrari – thank you!

I agree with John. One option could be adding this to the [GitHub Wiki](https://github.com/Talent-Catalog/talentcatalog/wiki/Testing#angular-unit-testing). Some information is already there, such as disabling tests and reasons for test failures.

At the very least, linking to your document from the Wiki and granting public view access would be good.

**Comment by EhsanEhrari** [comment]
Already added the link with the public access to [GitHub Wiki](https://github.com/Talent-Catalog/talentcatalog/wiki/Testing#angular-unit-testing) under the **Angular Unit Testing** section.
