### ISSUE TITLE
TC Logo

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1360]
- Code to Inspire
- (Jesse)

See: #42

- [ ] Add to release notes header when ready

**Comment by EhsanEhrari** [comment]
<img width="1250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXNEQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6ce49b900e66bd4ea937737686ca216595e93eb/1.jfif" alt="1.jfif" />

**Comment by EhsanEhrari** [comment]
<img width="1250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdEQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d65d76a43df0a4cba3cefea5fd3af2b17c80118c/2.jfif" alt="2.jfif" />

**Comment by EhsanEhrari** [comment]
<img width="591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--058fb7710ab6b31ec44da6a50f46f1e859dce850/3.jfif" alt="3.jfif" />
<img width="591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFljQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9dd6f1a599bebbe336077a0039590530e1a67906/4.jfif" alt="4.jfif" />
<img width="591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGNjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fe76f345a32d91f496e996a014f15fce4ec36f4/5.jfif" alt="5.jfif" />
<img width="591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGdjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ada49759bfc82e4dffcb267e4fc86dca27fe329e/6.jfif" alt="6.jfif" />
<img width="591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGtjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e53239a6cd32cdc4469c8597d449828b9526cc99/7.jfif" alt="7.jfif" />
<img width="591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--573422f96768bd9a71b409a2406d29f6db0f00de/8.jfif" alt="8.jfif" />
<img width="591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acbc8ba6a60b257e54d1f81d1a0266fa36e34e82/9.jfif" alt="9.jfif" />

**Comment by EhsanEhrari** [comment]
https://drive.google.com/file/d/1mLeLtFLpOfE-rrkz034cvHBJ6vxvog9o/view?usp=sharing
