### ISSUE TITLE
Bug with display of some icons next to each other in a chat post

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#1362]
Screen shot from production. The icons should have been Australian flag and Kangaroo.

<img width="1377" alt="Screenshot 2024-09-11 at 9 46 18 AM" src="https://github.com/user-attachments/assets/785189ae-619b-4556-a38a-4f42a45eac68">

**Comment by camerojo** [comment]
This can be reproduced on dev. If you enter the Australian flag icon and the Kangaroo icon next to each other you get the above.

If you put a space between them they display OK.

However, other (more common) icons work fine next to each other - ie without a space in between. For example Thumbs up and Smiley face. So it seems to be icon dependent.

**Comment by cazcam34** [comment]
Fixed bug but PR is failing due a backend test failure see screenshot:
<img width="897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWtuQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cc6227c4732a5273213339c5dbdd91c9e76ed76/Screen%20Shot%202024-10-07%20at%204.25.39%20pm.png" alt="Screen Shot 2024-10-07 at 4.25.39 pm.png" />

**Comment by cazcam34** [comment]
PR fixed in Sadats branch
