### ISSUE TITLE
Watched and Starred on searches isn't working

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#1377]
When I click on the **star** or **eye** icon on the candidate source, nothing appears to be happening. It isn't until I change tabs and the results are reloaded that it seems to work. I tried to fix it but wasn't able to complete, so logging here incase anyone wants to have a look. I believe it may be trying to fetch from the cache which is outdated?

I didn't test on lists but I assume it'll be the same as it's the shared candidate source component

**Comment by cazcam34** [comment]
Video to explain, excuse the toddler in the background!
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3pXQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff522c64c48e6c5d36d2e5145b1398eb78a74dd8/Screenshare%20-%202024-09-16%203_27_09%20PM.mp4)

**Comment by sadatmalik** [comment]
Thanks, @cazcam34 - I can take a look at this one.
