### ISSUE TITLE
Issue reported with candidate's UNHCR registration status not propogating to their candidate profile

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1393]
From Hanine:

We've been running into a problem for the past year where candidates say they're registered with UNHCR, but their profiles still show "No." I have been changing it manually for them and I remember bringing it up to John once but can't find our conversation anymore! One example is <https://tctalent.org/admin-portal/candidate/174881|this candidate>.

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1726820968581409?thread_ts=1726820968.581409&cid=C42S4AJ73)

**Comment by camerojo** [comment]
I think that the problem occurs when a candidate said that they were not registered with UNHCR when they first registered on the TC. Then they go into their profile and try to change it to say that they are now registered.

UnhcrRegistered is a transient field on Candidate, computed from the stored UnhcrStatus field.

There is logic in the setUnhcrRegistered method of the Candidate entity which will only update UNHCR registration status if additional information is being provided. In particular if the existing status is NoResponse or Unsure. Note that setUnhcrRegistered is only called from the candidate portal.  Admin updates call setUnhcrStatus.

The logic for this is to prevent candidates overriding good data that has been set and verified by admins

This doesn't allow the status to be updated from Not registered by a candidate.

**Comment by camerojo** [comment]
I think that this functionality is working as intended and that the issue could be closed for now. 

This is how I responded on Slack to the the user:

> Note that a candidate who said that they were not registered with UNHCR during their registration on the TC cannot update their status to registered afterwards. Only TC admins can do that.
Candidates can only update their UNHCR registration status if the current status on the TC is effectively unknown (ie the candidate did not respond to that question during their initial TC registration, or said that they were unsure).
Once the status has been set to a definite value, only TC admins can update it. 

Note also that the candidate provided as an example is Palestinian so will not be registered by UNHCR anyway. Palestinians are not handled by UNHCR. Another UN agency, UNRWA, handles Palestinians.
