### ISSUE TITLE
ViewJobSummaryComponent Angular unit test failing

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#1416]
This component changed to use auto save. 

That meant that the old save method was now doSave and the unit test stopped compiling.

I changed the unit test so that it now compiles again but it is still failing.

There are some "saving" and "error" fields which are used differently now (maybe not even needed - and shoul have been removed).

**Comment by EhsanEhrari** [comment]
Closing this one because already a ticket exist for this:
#1443
