### ISSUE TITLE
Autosaving search when saving to new list, old behaviour that could be removed

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#1439]
As a TC admin user,
When saving selections to a new list from an unsaved search it is also saving the search with the same name as the new list,
This is confusing as the search could be mistaken for the list and perhaps is not the desired behaviour - or if so it needs some more explanation to user

**Updated:** See notes below for background - this issue became a pandora's box of other issues relating to the saved search screen. I have created new issues for those, this one is less urgent but perhaps worth more of a discussion. Do we want to continue autosaving a search when we are saving a selection to a new list? @camerojo suspects this was done in the early days to encourage people using saved searches, however now it seems unnecessary. Spoke with Naji and he didn't seem to be bothered about it, so it doesn't sound like it's useful for him but can't be sure about others.

**Comment by cazcam34** [comment]
In the code since 2020 we autosave a search when we save a selection...
Suggestions:
- No longer autosave search when saving to list
- Remove 'Clear Search' button from a saved search view (only appear on default saved search)

Currently after saving a selection from a new default search to a saved list, the screen changes to the autosaved saved search and away from the default search without the user knowing. So then if they click 'Clear Search' enter a new search field/s and apply it will be searching a whole new search but still with the old search name. Then if they select from the newly applied search, make selections, save to a list then view list and return back to search (back button) they will have lost their newly applied search fields and the old search fields will return. This is because they are returning to the autosaved saved search and not going back to the default search that they were redirected from initially.

Benefit of the default search is that search fields are cached so they can change that search without clicking 'Update Search' and their search fields are remembered. Moving the user away from the default search into an autosaved saved search means they assume they are working with a default search where their search field changes are rememebred without clicking 'Update Search'

**Comment by cazcam34** [comment]
Digging deeper into saved searches/default searches....

I have a new default search, I add some search fields (e.g. Female, Accountant).
I save my search, naming it Female Accountants, my screen takes me to this new saved search 'Female Accountants'.
I now change the search field adding 'Finance Professional' to the occupations and click 'Search'.
I now see more candidates in my search Female Accountants (Fields: Female, Accountant, Finance Professional).
I add some selections to a list, view that list, click back to return to my search.
I see less candidates in the list, some selections are no longer there.
In my define search, I am only seeing fields Female, Accountant - no longer seeing Finance Professional.
All candidates that appeared due to the added field Finance Professional have been removed.
I go to a new search, and there i see the fields I last entered (Female, Accountant AND Finance Professional).

The Define Search component automatically saves to the default search when 'Search' is clicked, even if I am in a saved search screen.
The Define Search component saves to the associated saved search only when 'Update Search' is clicked AND then it clears the default search.

In summary, the define search filter works differently depending on what search I am on. 
If I am on a default search, the define search filter saves all changes upon each search. So I can search, change pages, come back and my search filters remain. 
If I am on a saved search, the define search filter saves changes to the default saved search and not the saved search it appears on unless I specifically click 'Update Search'.

See code where each 'Search' calls the method that updates the default search:
<img width="1356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBendjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b28caf5c760524deceee1a50bde7c672ce677451/Screen%20Shot%202024-10-03%20at%203.03.02%20pm.png" alt="Screen Shot 2024-10-03 at 3.03.02 pm.png" />

**Comment by cazcam34** [comment]
ALSO narrowing down a saved search, where I've already made some selections those stay selected even if they are filtered out of my narrowed down search!

**Comment by cazcam34** [comment]
Proposal:
- The same way we handle search filter saves for default searches (save the filters on each 'Search') I think we should do the same for saved searches, therefore making the 'Update Search' button redundant.
- Doing so we are showing and updating the search results and search filters relevant for the particular search we are on.
- Currently if I define a search while on my saved search page, I am basically just replacing what exists in my default search and not changing my saved search despite seeing the results of those updated search filters.


Also as above propose the following:
- No longer autosave search when saving to list
- Remove 'Clear Search' button from a saved search view (only appear on default saved search), maybe actually instead have a 'New Search' button

**Comment by cazcam34** [comment]
- [x] Record videos to show what is happening

**Comment by cazcam34** [comment]
Message to Naji with videos:
Hi @Naji, hope you had a good weekend! Just following up on the discussion above - while working on a solution for the issue of extra candidates being mistakenly added to lists I looked further into the search functionality. Doing so I found some ways I propose we can improve it, making search behaviour more consistent between saved searches/unsaved searches as well as making the behaviour more transparent to users.
My proposal is below, as it involves removing some functionality that we don't believe is necessary we want to make sure it's not used before removing. So it would be great to run it by you and get your thoughts on the below or search functionality in general. Please let me know if you have any feedback, or if it's easier to have a quick chat we can do that too. I also filmed some videos to hopefully help explain.

**Proposal:**
- Remove the 'Update Search' button on saved searches, instead autosave the search fields upon each 'Search' click. This keeps consistent with how unsaved searches are saved. See video A.
- In addition to the above, updated search fields on a saved search will update the saved search and not the unsaved search filters. See video A.
- No longer autosave search when saving selection from an unsaved search to a list (currently saving a selection from an unsaved search to a list, autosaves the search with the same name as the list name) - see video B.
- Remove 'Clear Search' button from a saved search view, instead have a 'New Search' button which redirects to the unsaved search page. A clear search is effectively a new search - so we want to redirect users to the unsaved search instead of clearing a previously saved search. Users can still update their saved search filters and that will be saved automatically upon 'search' (see first bullet point/video A).

**Comment by cazcam34** [comment]
**Video A:**
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzhtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c77b8daf11f913ec1dbba99397ec18ca538c7390/Screenshare%20-%202024-10-07%2011_58_16%20AM.mp4)

**Video B:**
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEFtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b37f168235386dbaa3e66c2091896630017b693/Screenshare%20-%202024-10-07%2011_28_48%20AM.mp4)

**Comment by camerojo** [comment]
@cazcam34 While you are reviewing the search screen, here is another idea:

Copy icon should appear on main search display (currently it is only on the short search display card when selecting from list of searches.

When a search is copied, it should automatically navigate to the new copied saved search.

This allows you to create a new search starting from an existing search.

**Comment by cazcam34** [comment]
Along with @camerojo 's note above I have found a small bug with the copy search button, so that can be included in the above idea (see PR #1460)

**Comment by cazcam34** [comment]
Spoke to Naji today - 
- [x] wants to keep update search button for saved searches as he likes to play around with them and doesn't want to loose his initial 'saved' state. 
- [ ] add a new SF stage for removed (accidentally added) - create new issue (#1501)
- [x] Disable the 'clear selection' button if there are no selections associated  (see #1494)
- [x] he doesn't love how the default for the show closed cases checkbox is checked - he only cares about unchecked and always has to uncheck it - Update: Leave as is, that is meant to behave that way and we don't want to change.

Bigger issue around the selected searches still not working - see markUserSelectedCandidates where on 'Search' green button click we are getting the selections from the default search (not from the search we are looking at). See issue #1494
