### ISSUE TITLE
TC is not handling Salesforce opportunities where country name is given as just CA (instead of Canada)

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#144]
See Talent Catalog Alerts - "Salesforce country CA not found in database."

This is sent from SalesforceJobOppServiceImpl.java

**Comment by samschlicht** [comment]
No need for any coding here — turned on Country and State/Territory Picklists on SF, having tested first on Sandbox. SF provides a tool that facilitates cleaning the existing data before the change is implemented, so we should find after the next sync that this is no longer an issue.
![Screenshot 2023-07-10 at 4.28.31 pm.png](https://images.zenhubusercontent.com/64818ed0adecbe758d4abfdb/ca191209-a61b-4cd1-8296-5362a8317825)

**Comment by sadatmalik** [comment]
Nice one, Sam!
