### ISSUE TITLE
Remove General Notes visibility for Employer Access users?

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1462]
Suggestion from Zeynep, for discussion.

At least to hide until Candidates reach e.g. CV Review. There are examples where confidential info may have been added in General notes - examples from Zeynep to follow.

E.g. ID : 241924

**Comment by camerojo** [comment]
This field is explicitly labelled as "notes which can be shared with potential employers".

The solution is not to remove the field but to use it correctly.

<img width="1425" alt="Screen Shot 2024-11-29 at 3 39 46 pm" src="https://github.com/user-attachments/assets/9a2b4aeb-b77d-45ee-849c-c8fba95ac7d0">

**Comment by camerojo** [comment]
I have added a warning to users not to put confidential info in this field.

<img width="1197" alt="Screen Shot 2024-12-11 at 2 13 29 pm" src="https://github.com/user-attachments/assets/099e3e16-6635-4bd1-af81-86dc624be4ac">
