### ISSUE TITLE
Performance issue with launching New Search

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#1476]
Launching the New Search screen has been becoming slower and slower. 

This is caused by initializing just one control ExclusionList. That control selects a list from a drop down of ALL lists. Currently FULL details of ALL lists is loaded at component start up - this is now around 1Mb of data on production and takes around 20 seconds.

Instead lists should be searched for back on the server based on typing in their names - like we do for the quick candidate searches by name, number, email or phone number.

**Comment by camerojo** [comment]
Try ngSelect using own local look up of id to name

But no ngModel

**Comment by camerojo** [comment]
Cherry picked hotfix - has problem with pull requests in between commits

**Comment by sadatmalik** [comment]
We should aim to isolate cherry-picked commits as much as possible. Cherry-picking a merge commit is more complicated and is not fully supported in IntelliJ, as noted in [this JetBrains issue](https://youtrack.jetbrains.com/issue/IJPL-80621/Allow-cherry-picking-merge-commit-from-IDE).

Cherry-picking merge commits requires manual handling, I’ve not done it myself but [this Medium article](https://medium.com/codebrainery/cherry-picking-merge-commits-in-git-bb7dc29d9e2b) outlines the steps. It can introduce additional commits from the merged PR, potentially bringing in unnecessary changes to the branch—problematic if we’re wanting to isolate a specific fix or feature.

That said, there are cases where cherry-picking the merge commit might be necessary, such as when it contains required contextual changes.

The cleaner approach is to cherry-pick individual commits from the relevant branch. If specific commits from the merged PR are needed, they can be cherry-picked directly from the PR’s branch.
