### ISSUE TITLE
Sync candidates to Salesforce candidate records 

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#148]
As a TBB staff member
I would like to be able to access and analyse live-ish candidate data using Salesforce and Sopact reporting tools
To better understand and present information regarding our candidates

This was primarily instigated by the Sopact-TBB team's request for access to this data for the[ impact dashboard](https://tbb.sopact.com/superset/dashboard/13/). There have also been other requests, such as from the comms team to populate their candidate mailing list and more efficiently produce the [Talent Catalog snapshot](https://www.canva.com/design/DAE4wm4ECDc/3YDGnhhcedI40BbaCMiOOA/edit?utm_content=DAE4wm4ECDc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).

John met with Sopact and tentatively settled on the most efficient and secure way of achieving this being to extend our SF API connection to include all live candidate records.

The Sopact team and other stakeholders will need to decide what data they need to gather on SF and adapt the contact records accordingly. At that point we can set up a nightly sync

For discussion by the tech team and action if agreed.

**Comment by samschlicht** [comment]
- [ ] #161

**Comment by samschlicht** [comment]
Suggest this should only happen for SF prod (due to sandbox storage limits)

**Comment by sadatmalik** [comment]
Could this be one for the anonymised data service?

**Comment by samschlicht** [comment]
Moving ahead as #402
