### ISSUE TITLE
Add "Clear Format" Option to Job Opportunity Intake (JOI) Section in Text Editor

### ISSUE THREAD

**Issue by EhsanEhrari** [talentbeyondboundaries/tbbtalentv2#1483]
From **Jana Al Mawed**:

> Is it possible to have a "Clear Format" option in the Job Opportunity Intake (JOI) in addition to the other options of Bold, Underline etc? Most of the times we are copying and pasting into the text fields in the JOI section so it would really come in handy because most of the times texts get pasted in a funny font or size like the attached screenshot - I hope this makes sense.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkZNQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34de3c497db6b8dbb567b565733ef2c487ff6e73/image.png" alt="image.png" />

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1728988401097159)

**Implementation Notes:**
- [x] Add a "Clear Format" button to the ngx-wig in the JOI section.
- [x] Ensure that the button is accessible in the toolbar alongside Bold, Underline, etc.
- [x] The "Clear Format" button should remove all formatting from the selected text, resetting it to default styling.

**Comment by sadatmalik** [comment]
Thanks, @EhsanEhrari - pulling this one into sprint

**Comment by EhsanEhrari** [comment]
Thanks, @sadatmalik - I will pick this one.
