### ISSUE TITLE
Is it possible to add PR previews?

### ISSUE THREAD

**Issue by hiba-machfej** [talentbeyondboundaries/tbbtalentv2#1485]
Most platforms offer the ability to preview PRs before merging them. It creates a link where you can see the effect of the change. I searched in AWS and found this in the docs https://docs.aws.amazon.com/amplify/latest/userguide/pr-previews.html. I found this GitHub action as well but I haven't tried it before: https://github.com/rossjrw/pr-preview-action

**Comment by MuhannedNoman** [comment]
This could be beneficial for the development of the PWA, as they only function on localhost or HTTPS, as indicated [here](https://angular.dev/ecosystem/service-workers/getting-started#initial-load).

Having a secure deployment for each pull request will enable us to test the PWA without needing to deploy to the staging environment.

**Comment by hiba-machfej** [comment]
Started working with [AWS Amplify](https://aws.amazon.com/amplify/). Setting up PR previews for both the candidate and admin portals was straightforward. However, the challenge was figuring out how to deploy only one of them based on specific changes. For example, a PR might only include changes to one portal, or it could be for backend updates only, so we don’t need a deployment every time.

After checking the [Amplify documentation](https://docs.aws.amazon.com/amplify/latest/userguide/monorepo-configuration.html), it seemed possible to deploy individual apps in a monorepo setup. However, after a lot of testing with the `.yaml` file, I found that it mainly supports deploying a single app at a time based on an environment variable, rather than dynamically choosing which one to deploy.

Since running one build at a time wasn’t possible, I tried building both portals but only deploying the one with relevant changes. There’s an environment variable called [AMPLIFY_DIFF_DEPLOY](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#:~:text=example123456-,AMPLIFY_DIFF_DEPLOY,-Enable%20or%20disable), which detects changes and only deploys the app with updates. This works in theory, but when I committed changes only to the candidate portal, Amplify still created a broken link for the admin portal.

The next steps might include writing a GitHub Action to handle this conditionally, checking out [AWS CodePipeline](https://aws.amazon.com/blogs/devops/aws-codepipeline-adds-support-for-branch-based-development-and-monorepos/), or possibly exploring other services like [Render](https://docs.render.com/monorepo-support#pull-request-previews), or [Netlify](https://docs.netlify.com/configure-builds/ignore-builds/).
