### ISSUE TITLE
Employers using employer access see candidate opportunities with other employers

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#1491]
Employers should not see candidate opps with other employers.

Reported by Zeynep in comments on [Talent Catalog for Employers doc](https://docs.google.com/document/d/1aI7dTq9wwucPmY7UMjpsjn9V5sLf1WWpYnhiA_9q43U/edit?pli=1#heading=h.fw9t99c6xm3b).

> In the test environment as Iress Australia, I'm able to see candidate 8363's opportunity with Professional Brotherz Pty Ltd. Maybe there is a bug?
> 
> [https://tctalent-test.org/admin-portal/candidate/8363](https://www.google.com/url?q=https://tctalent-test.org/admin-portal/candidate/8363&sa=D&source=docs&ust=1733107191542889&usg=AOvVaw2pwfxVsKW3m_4Exk11A2aZ)
> [https://tctalent-test.org/admin-portal/opp/5953](https://www.google.com/url?q=https://tctalent-test.org/admin-portal/opp/5953&sa=D&source=docs&ust=1733107191542917&usg=AOvVaw24G_Xr6WiJna0AxlC8UfNl)
>

**Comment by sadatmalik** [comment]
Pulling this one into the sprint. I'll take a look at it today.

**Comment by camerojo** [comment]
### Spring Boot upgrade bugs

- [x] In JPA Specifications comparing a record with an ID without explicitly calling getId on the record used to work but now throws and exception like: org.springframework.dao.InvalidDataAccessResourceUsageException: Cannot compare left expression of type 'org.tctalent.server.model.db.User' with right expression of type 'java.lang.Long'

**Comment by camerojo** [comment]
Also fixes bug where candidate source creating user was not displaying for shared lists or searches
