### ISSUE TITLE
Additional selected candidates in selections when saving to list

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#1492]
Had a call with Naji to continue to discuss the additional candidates appearing in list when selecting. 

Found the source of the issue. As mentioned in another issue here () the define search filter is always saving to the 'default' search upon every 'Search' button click. Even if I am in a saved search screen and the filter is populated with my saved search filters, if I change those filters and click 'Search' I am updating and saving my default search filters not the saved search filters UNLESS i click 'Update Search' button then it saves to my saved search.

In addition to the above upon each 'Search' button click we also are marking the selected candidates for that search. Each user has a different amount of selections for a search. HOWEVER we are marking the selected candidates for the default search and not the saved search!!

**Comment by cazcam34** [comment]
<img width="1266" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUJjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b5c711cb66f83f12940fd7fffe5fb933219d189/Screen%20Shot%202024-10-21%20at%203.47.54%20pm.png" alt="Screen Shot 2024-10-21 at 3.47.54 pm.png" />
<img width="1282" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUZjQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5270d2b9ece604db9e86cff6d2625a1166744e0/Screen%20Shot%202024-10-21%20at%203.48.04%20pm.png" alt="Screen Shot 2024-10-21 at 3.48.04 pm.png" />

**Comment by cazcam34** [comment]
- [x] Only default searches are autosaved upon search click
- [x] Selections are displayed on front end and buttons disabled if no selections made
- [x] Saved searches require tracking of searchForm dirty, if dirty and navigate away from page we want to send pop up saying something link "you have made changes to this search, if you leave page you will lose them unless you click 'Update Search' button"
- [x] Undo clear seelctions on Clear Search on #1438? Bug related to this which needs to update the total selections when we click Clear Search.

**Comment by cazcam34** [comment]
https://medium.com/@aregawihaileyesus/block-leaving-the-route-and-reload-the-page-if-there-are-unsaved-drafts-33102edf6d7d
https://dev.to/netsi1964/create-a-guard-in-angular-to-handle-navigation-away-from-a-component-with-unsaved-changes-40i3

**Comment by cazcam34** [comment]
https://www.tektutorialshub.com/angular/angular-candeactivate-guard/

**Comment by cazcam34** [comment]
Moving away from saved search without saving changes (now we no longer are working with the default search) triggers a modal pop up to confirm
<img width="1019" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWx1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a36bfb8f87498db5e7f6fad141a889ed6616cb31/Screen%20Shot%202024-10-24%20at%208.09.18%20pm.png" alt="Screen Shot 2024-10-24 at 8.09.18 pm.png" />

**Comment by camerojo** [comment]
Thinking more about this following last night's team call I think we need the following new logic when a change is made to a search's filters:

- The system checks if there are any selections. If not, no problem - the user goes ahead with the changes. 
- If there are selections, check whether the selections have been copied to a list. If so, no problem. 
- If the selections have not been copied, the user is prompted to save selections if they wish

@cazcam34
