### ISSUE TITLE
No SF stage for accidental additions to submission list

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#1501]
Despite precautions, candidates could still be accidently added to a submission list (therefore creating an SF candidate opportunity). We need an SF stage for this circumstance (e.g. Removed) so these candidate opps can be closed, and we want to filter candidates with this stage from the submission list so they appear to be removed as opposed to closed.

**Comment by samschlicht** [comment]
Roughly per [Slack convo suggestion](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1728547304081769) I reckon this should be a closed stage called 'Candidate mistakenly added to list'.

Hoping we can squeeze this one into the mini-release!

**Comment by samschlicht** [comment]
Reminder that we have [this handy bit of Tettra doc](https://app.tettra.co/teams/talentbeyondboundaries/pages/recurring-tc-processes#header-8qjuo-changing-opportunity-stages) for this process!

**Comment by samschlicht** [comment]
For some reason I'm not getting the usual option to link the PR to the issue.

Also just noting that these stages need to go on SF right after the relevant release.

**Comment by samschlicht** [comment]
Adding this stage to SF needs to be part of the relevant release plan — will need to check with team which one this will be going into.
