### ISSUE TITLE
Create a section in the candidate portal where candidates can view their coupons

### ISSUE THREAD

**Issue by EhsanEhrari** [talentbeyondboundaries/tbbtalentv2#1537]

**Comment by sadatmalik** [comment]
Hi @EhsanEhrari , @MuhannedNoman ; I think the idea is that candidates will be sent a link by which they will redeem (or activate) the coupon that has been assigned to them?

**Comment by EhsanEhrari** [comment]
@MuhannedNoman  I think we are going to send candidate something like the link below.

https://englishtest.duolingo.com/pay/ACCTBBP5Z8URGF?login_view=register&cta=Accept%20Coupon&show_bundle=false
