### ISSUE TITLE
Update SF dependants at Job Offer stage

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1539]
From Sarah:

Would there be a possibility to get the stage that the dependants are updated from "relocated" to "job offer"?

I ask this because I update the dependants every month or so manually, and I update them from the job offer phase so we can see "how many people secured a durable solution"

I dont think there will be any (unless I missed them!) who will have blank dependants by the time they relocate.

**Comment by samschlicht** [comment]
Picking this one up since it's a simple adjustment to my previous work in #1266!
