### ISSUE TITLE
Display whether or not candidate has had intake in candidate lists

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#156]
As an admin user
I would like to add intake status as a selectable column for search lists
So that I can easily see if candidates have completed intake

**Comment by sadatmalik** [comment]
Opened by JC on Trello board - migrated to ZenHub after discussion with Zeynep

**Comment by samschlicht** [comment]
I'm closing this issue, since it's addressed by #157
