### ISSUE TITLE
Implement unique identifier type for obfuscated IDs

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1634]
For prototyping, uuid for obfuscated IDs will suffice.

However before proceeding beyond prototyping stages; care should be taken in selecting between UUIDs and, for example, Google style identifiers.

See:
https://stackoverflow.com/questions/19686430/is-google-drive-file-id-unique-globally
https://chatgpt.com/share/6733d084-5660-800f-a9df-1b920b9991d2

**Comment by sadatmalik** [comment]
Decide about mappings:

E.g.

UUID to List ID
UUID to Search ID
UUID to Candidate ID or Candidate number?

**Comment by camerojo** [comment]
I suggest that we should use Base64 encoded Version 4 (ie random) UUID's (eg Ej5FZ+iXEtOkVkJmFBBwAA)

See https://chatgpt.com/share/6747794b-0274-800f-90ca-5bc1cce6ba55

In the standard TC database we can add an extra "public_id" field (indexed) to the List, Search, Job, Candidate tables (and potentially others)

### Note
There is also a package called NanoID which is more configurable - you can trade off length of id against uniqueness. But for truly unique ids the length is typically 21 characters - compared to the 22 characters  of Base64 UUIDs - and other factors (like performance) are similar - so no real advantage for us over Base64 UUIDs.

**Comment by camerojo** [comment]
### Possible implementation

- [x] Add PublicIDService which generates public (obfuscated, globally unique) ids.
- [x] Add new publicID field  which is automatically created on creation (by calling PublicIDService) of potentially public objects - ie Candidate, List, Search
- [x] Add publicID to DTOs
- [x] Don't add public id to selection lists?
- [x] Run batch to populate public ids for all existing objects - not deleted - not hidden (eg selection lists)
- [x] Add publicID to OpenAPI def - SM: marking as closed - it will be done in #1770
- [x] Remove id and candidateNumber from OpenAPI def - SM: marking as closed - it will be done in #1770

fyi @sadatmalik

**Comment by sadatmalik** [comment]
These will be implemented in the newly opened issue #1770:

- Add publicID to OpenAPI def
- Remove id and candidateNumber from OpenAPI def
