### ISSUE TITLE
Checkbox for employer sourcing preferences

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#1638]
From Zeynep:

For employer access, could we add a checkbox in the job registration process to allow employers to indicate whether they want source partners to search for candidates or prefer to proceed only with candidates they’ve added to the submission list? We’re currently recommending that employers add this information in the job summary section, but having a more structured option would be incredibly helpful.

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1730914604891109)

**Comment by camerojo** [comment]
### Proposed implementation

- [x] Add "SkipCandidateSearch" checkbox
- [x] Modify initial stage to skip CandidateSearch (next stage is VisaEligibility)
- [x] Find no search icon
- [x] Do Flyway to create new field

**Comment by camerojo** [comment]
<img width="1112" alt="Screen Shot 2024-12-11 at 2 29 48 pm" src="https://github.com/user-attachments/assets/97ded7fd-dda2-40cf-82a2-b9c63f3d6d76">
