### ISSUE TITLE
Rename gradle build from tbbtalentv2 - and other instances of that label

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#175]
See settings.gradle: "rootProject.name = 'tbbtalentv2'"

Check where else this is used. eg in Github builds

Replace with: talentcatalog

Need to replace it also in project Readme and terraform scripts

**Comment by sadatmalik** [comment]
- [x] update settings.gradle: "rootProject.name = 'tbbtalentv2'"
- [x] replace in project Readme
- [x] update terraform scripts
- [x] update Git actions
