### ISSUE TITLE
Rename database from tbbtalent to tctalent

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#176]
Production database as well as dev

- [x] change DB name
- [x] change DB user and password

**Comment by sadatmalik** [comment]
```
alter database tbbtalent rename to tctalent;
```

**Comment by sadatmalik** [comment]
Note: psql is normally automatically installed when you install postgres
The default is to create a master user called postgres with password postgres (which you can override during installation). To start psql, I had to specify psql -U postgres

1. use psql to connect to postgres db locally:

```
> psql postgres
```

2. Make sure you are connected to the postgres db 

```
# \connect postgres
```

3. Check active connections

```
# select * from pg_stat_activity where datname = 'tbbtalent';
```

4. When safe to do so - terminate all connections to tbbtalent database:

```
# select pg_terminate_backend (pid) from pg_stat_activity where datname = 'tbbtalent';
```

5. Check active connections are Zero:

```
# select * from pg_stat_activity where datname = 'tbbtalent';
```

6. Rename the DB:

```
# alter database tbbtalent rename to tctalent;
```

7. Connect to tctalent DB:

```
# \connect tctalent
```

8. Create tctalent user

```
# create user tctalent with superuser password '***';
```

9. Test db connection to tctalent database from IntelliJ

10. Restart Spring application


Note: migration 1.146 points to the old db name - we can't change it in the flyways as it will break the checksum. How to resolve this?

**Comment by sadatmalik** [comment]
- [x] Push image with DB name changes to staging

- [x] Repeat DB renaming steps (see above) for staging:

```
# psql --host=<DB_ENDPOINT> --port=<PORT_NUMBER> --username=<MASTER_USERNAME> --password --dbname=<DATABASE_NAME>
```


- [x] Check DB backups
- [x] Rename DB - steps above
- [x] Restart staging service

- [x] Document these steps in v2.2.0 release preparation notes - that is when the renaming will be applied to production

**Comment by sadatmalik** [comment]
For prod - repeat the below steps applied to staging AWS RDS DB:

1. connect to DB via psql using the MASTER username (e.g. tbbadmin) and password - I had to reset this for staging

```
# psql --host=<DB_ENDPOINT> --port=<PORT_NUMBER> --username=<MASTER_USERNAME> --password --dbname=<DATABASE_NAME>
```

2. create new database

```
# create database tctalent;
# \connect tctalent
```

3. create new user

```
# create user tctalent with password '***';
```

4. stop the TC services

5. quit psql and take a pg_dump of the tbbtalent database

```
# pg_dump -h staging_db_host -U staing_db_user -d tbbtalent -f staging_dump.sql
```

6. restore new tctalent database with tctalent user from dump file

```
# psql -h <NEW_DB_ENDPOINT> -U tctalent tctalent < dump.sql
```

7. restart the TC service using the correct task definition (pointing to the new tctalent database)
