### ISSUE TITLE
Update copyright

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#183]

**Comment by camerojo** [comment]
Among other possible changes - eg updating dates, the Copyright should be changed to refer to Talent Catalog, not Talent Beyond Boundaries

**Comment by cazcam34** [comment]
<img width="1107" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8db57fdd9a68010239990c0c41ef4a4eaff7ab75/Screenshot%202024-04-15%20at%2012.22.49%E2%80%AFPM.png" alt="Screenshot 2024-04-15 at 12.22.49 PM.png" />

Not actioning as it is a large file change, but see screenshot above as where it appears this is actioned. 
https://www.jetbrains.com/help/idea/copyright.html#update-copyright

**Comment by sadatmalik** [comment]
@camerojo - I wonder if now's the time to do this with the front/back library updates?

**Comment by camerojo** [comment]
Yes - we should do this now.  Let's arrange a good time to update all. @sadatmalik
