### ISSUE TITLE
Rename the "Elasticsearch" label in new search screen

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#195]
In demo-ing to partners and Unhcr the term "Elasticsearch" has required extra explaining because of the name "elastic"

Better to rename to a more user friendly naming - e.g. "Keyword search"

Also - consider condensing the elasticsearch explanatory text at the top - and moving below the current elasticsearh field.

"Introducing Elasticsearch which searches all CV's as well! When searching + means AND, space means OR. For example welder diesel+mechanic will find all candidate profiles containing the word 'welder' OR both words 'diesel' AND 'mechanic'. You can just match the first part of a word using *. For example 'account*' will match 'accounting' or 'accountant'. You can also search for phrases as well as words by using double quotes. For example accountant + "hospital director" will find profiles with the word 'accountant' AND the phrase 'hospital director'. You can use brackets to group terms. For example accountant + (excel powerpoint) means find profiles containing the word 'accountant' AND either one of 'excel' or 'powerpoint'. But (accountant + excel) powerpoint means find profiles containing both words 'accountant' and 'excel' OR profiles containing the word 'powerpoint'."

**Comment by samschlicht** [comment]
Could be a tooltip
