### ISSUE TITLE
Follow up meeting with SkyHive

### ISSUE THREAD

**Issue by tbbadmin** [talentbeyondboundaries/tbbtalentv2#214]

**Comment by sadatmalik** [comment]
Meeting arranged for Tuesday 1 August - Mohan, Luke, Sadat

**Comment by sadatmalik** [comment]
See Partner Feature Matrix:
https://docs.google.com/spreadsheets/d/1q8LC7PdUa_RBla_knwJNgSm4fWCmTBpfj70Qv6GTKRk/edit#gid=0
