### ISSUE TITLE
Remember whether "show closed cases" is checked or unchecked on submission lists. Default to checked.

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#222]
As a partner
I would like the TC to remember whether I prefer to show or hide closed cases in submission lists

**Comment by camerojo** [comment]
Defaulting to checked makes more sense because new people are confused when cases they are watching suddenly disappear from the submission list

**Comment by sadatmalik** [comment]
Note - implementing this will also resolve issue #642 reported by Jana (Slack) on 9-Feb:

https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1707488790061359
