### ISSUE TITLE
Fix bug where Job stages could not be updated from the TC

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#236]
This was an urgent bug introduced when we jumped ahead on the production software.

It is an urgent fix because it prevents people from updating job stage from the TC - forcing people to do it the old way -  directly on Salesforce. We need this working now - rather than waiting for the next official release.

So this was pushed into production with a fix on a branch from master - and is now live. See https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1690775639454069?thread_ts=1690495261.260009&cid=C42S4AJ73

The purpose of this issue is to replicate on staging the temporary fix put into master. Because it is just a temporary fix, it will be eventually overwritten on staging by the correct code which will go into production in the next official release.

**Comment by camerojo** [comment]
fyi @sadatmalik (does this look like the right way to track urgent bug fixes?)

I will create a branch from this issue in the normal way. Then I will merge Master into it - which should add the temporary fix.

Then I will create a pull request for this issue.

**Comment by sadatmalik** [comment]
hi @camerojo i think the way you have done it works fine. 

I would do it pretty much as you have but without creating the second branch off of staging. 

So;

- open a "hotfix" issue describing the bug
- create a "hotfix" branch from master
- fix the bug in the hotfix branch and merge it into master
- open a PR from the hotfix branch into staging
- merge the PR into staging 
- delete the hotfix branch and move the issue to "done" on the board
