### ISSUE TITLE
Talk to Naji

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#241]
Follow up with Naji on this one - open as a separate ticket if this is an issue -

- [x] Candidates are added to the suggested list automatically (not sure how but it is matching the candidates in the submission list). [John]

**Comment by camerojo** [comment]
I had a good call with Naji explaining the reasoning behind copying the contents of the submission list to the suggested list when a job is published.

ie it captures the employer's/employer's representative initial thoughts on potential candidates. This is a form of documentation on the job. It is not much use to Naji - but he understands that it could be useful to source partners.
