### ISSUE TITLE
exportToPdf does not work for VisaJobCheckComponent 

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#246]
This code was not compiling in GitHub build of staging - so a new PR #245 was created which commented out call to non existent exportToPdf method.

Also VisaCheckComponentBase did not compile - added @Directive to make it compile - but this class is not used anywhere.

**Comment by cazcam34** [comment]
VisaCheckComponentBase is now used in the new branch updating the visa checks (done while added Canada visa check)
