### ISSUE TITLE
Quick search by Country of Operations (Green Lit countries)

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#248]
See also #454 

From Naji:

"Is it possible to add in the list of the 'Location (Country)' an option for 'Countries of operations'? and once we select this it will automatically search only in Egypt, Iraq, Jordan, Lebanon, Malaysia, Turkey, UAE, Uganda, Kenya, Ecuador, Peru, India, Indonesia and Pakistan. We can add more options once we operate in more countries. or we can have a tick box added to the search for that options.
This won't stop us from searching in other areas, as I usually widen my search when I do not find suitable or strong candidates in those countries (or enough candidates)., but it is usually a starting point for candidate search.
Happy to chat further and hear your thoughts about this."

**Comment by camerojo** [comment]
Can we size the scale of the problem before dedication coding time to it?

**Comment by sadatmalik** [comment]
Green-lit countries:
https://app.tettra.co/teams/talentbeyondboundaries/pages/official-global-source-country-list

**Comment by samschlicht** [comment]
Will be quickly cleared as soon as #454 complete

**Comment by samschlicht** [comment]
I've created and shared these searches based on the [Tettra page](https://app.tettra.co/teams/talentbeyondboundaries/pages/official-global-source-country-list):
[TBB Green-Lit Countries (2800)](https://tctalent.org/admin-portal/search/2800)
[Partnership Countries (2801)](https://tctalent.org/admin-portal/search/2801)

I've added a comment on that page mentioning that these are available to be used as base searches, and would ideally be kept up-to-date (or they can notify me to do so).

These will be more useful once #454 is in prod, enabling elastic searches to be built on top, as well as regular searches.
