### ISSUE TITLE
Central home for interview guidance from employers

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#251]
From Sanah:

As agreed, here is a summary of my ask for an added feature to the TC's Job Opportunity Section.

*Problem:* There is no central and accessible home for interview guidance from employers. This guidance is shared with the destination team (or in small occasions, shared directly with candidates) and lives either in staff emails, candidate emails, on Slack, or Trengo/Whatsapp conversations with candidates. There is a lack of easy and direct access to any information employers share with us. It's crucial this information gets in the hands of candidates as soon as possible.

*Need:* A central and accessible home for interview guidance where key stakeholders can easily access it without having to dig through email, Slack threads, or Trengo conversations. I think it makes the most sense for this to live on the Job Opportunity section of the TC - and potentially with a button where the information can be easily shared with candidates through a Task or another method. It's also important that this field be editable similar to case note, and it is also important for there to be a feature which allows the uploading of files - sometimes employers share documents including special questions they'd like candidates to prepare, or documents including technical tests.

Please let me know if there is more I can provide to clarify and complete this request.

[Slack Message](https://refugeejobsmarket.slack.com/archives/C03KCTEDFKR/p1690455399090329)

**Comment by cazcam34** [comment]
For now: Same as JD save to database and store in folder. To share, make optional button appear if there is interview guidance.

Potential for other uploads: store an other folder link and then just return all files in that folder to display.

**Comment by cazcam34** [comment]
- [x] Create front end admin portal
- [x] Create back end 
- [x] Flyway with new fields (file_interview_guide_name) & (file_interview_guide_link)
- [x] Create front end candidate portal
- [x] Add translation for candidate portal button

**Comment by cazcam34** [comment]
Question: Putting the file link on the saved list object (as per JD) makes sense as then the file can sit in the job folder (nested in the list folder) on the google drive. However this made the file difficult to access on the candidate portal which only shows the candidate opp. Had to nest jobOpp -> saved List  -> fields. Perhaps this needs more thought - should this field sit on the salesforce job opp object? Instead of the saved list object?
