### ISSUE TITLE
New inactive stage for "No Job Offer" candidates - "Relocated through no job offer pathway"

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#257]
Canada has a pathway which selects refugees based on their skills, without needing any sponsoring job offer.

This is a controversial pathway (refugee selection based on skills rather than vulnerability) and does not match TBB's employer led labour mobility model. However, TBB has chosen to use this pathway in Canada.

We need a way of tagging candidates that relocate through this pathway so that they can be reported on separately.

**Comment by cazcam34** [comment]
@camerojo is this a SF/Candidate Opp Stage? Or is this a Candidate Status?

**Comment by camerojo** [comment]
It is a terminal stage

**Comment by cazcam34** [comment]
@cazcam34 to do the TC side & @camerojo to do SF side

Salesforce stage name = relocatedNoJobOfferPathway - "Relocated no job offer pathway)
Closed = true,
Employed = false,
Won = false

Want to trigger candidate status change, when adding this new stage. (an inactive status)

**Comment by cazcam34** [comment]
@camerojo SF name = Relocated no job offer pathway
