### ISSUE TITLE
Branding info does not return landing page details

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#26]
BrandingAdminApi returns a DTO as follows but this does not contain the landing page details - think this might be an omission?

```
    DtoBuilder brandingInfoDto() {
        return new DtoBuilder()
                .add("logo")
                .add("partnerName")
                .add("websiteUrl")
                ;
    }
```

i.e. also - .add("landingPage")  ??

**Comment by camerojo** [comment]
No - the admin portal does not use landing pages - which is why it is not returned in the BrandingInfoDTO.

Landing pages are only used on the candidate portal - selected based on the partner managing the candidate in question.
