### ISSUE TITLE
Should pressing enter in the elasticsearch field trigger a search?

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#267]
As a TC admin user
I would like to be able to trigger an instant search by pressing enter after entering my elasticsearch query
Because it's quicker and that's what I'm used to on other platforms

What does the team reckon?

**Comment by sadatmalik** [comment]
(Hint: Take a look at some existing code that responds to the up and down keys)

**Comment by sadatmalik** [comment]
John + Sadat - thumbs up - let's do this!

**Comment by samschlicht** [comment]
I suppose my only concern with this one is that nothing happens on the visible part of the screen to indicate that the search has happened! Which you could say is also an issue with the 'Search' button, except that it's closer to the results and thereby they're more likely to be in frame when it's clicked. No biggie, but might be a small front-end enhancement for future?
