### ISSUE TITLE
Cannot remove published fields by dragging them away 

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#272]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUFYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7c7d5292e87bc17dcba58f1396d49aec6187219d/Screenshot%202023-08-18%20at%206.58.25%20pm.png)

**Comment by camerojo** [comment]
We have an old Dragula version (2.1.1) which is recommended to work under older Angular versions.

See https://www.npmjs.com/package/ng2-dragula

We can't go to latest version because it requires later version of Angular.

Probably should upgrade to latest Angular, then upgrade Dragula.

**Comment by sadatmalik** [comment]
Related to #352
