### ISSUE TITLE
Hot-fix branching process for review

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#279]
- open a "hotfix" issue describing the bug
- create a "hotfix" branch from master
- fix the bug in the hotfix branch and merge it into master
- open a PR from the hotfix branch into staging
- merge the PR into staging
- delete the hotfix branch and move the issue to "done" on the board

**Comment by camerojo** [comment]
I can't see where this is documented @sadatmalik 

Where did we decide to put this doc - in the Wiki? Maybe here https://github.com/Talent-Catalog/talentcatalog/wiki/Release?

**Comment by sadatmalik** [comment]
Done:

https://github.com/Talent-Catalog/talentcatalog/wiki/Release#hotfix-branches

**Comment by camerojo** [comment]
@sadatmalik I have updated the Wiki with Intellij alternatives.

A couple of comments though:

- There is no Github issue created representing the hot fix. I do that by creating a normal issue in Github branched from staging after doing the master hotfix. Then in that branch I merge from master - which replicates the master hotfix changes. The create a normal pull request from that staging branch - like any other issue. 
- Are your git commands missing a push up to the server? Aren't you just committing to your local repo copy? Or maybe I don't understand some of the options on your git commands.
- The advantage of using Intellij is that it allows you to select all sorts of options prior to a commit - like checking code,
optimizing imports, checking for todos, updating copyrights etc.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d682a0812b7e92a232e990586ad98f341d9c5dd6/Screen%20Shot%202023-11-02%20at%205.55.56%20pm.png)

**Comment by sadatmalik** [comment]
Thanks for the Wiki updates and comments @camerojo 

I've thought about this some more and on reflection think we can avoid having to create a retrospective issue. A cleaner workflow is to generate the PR into staging directly from the hotfix branch. This way is efficient and avoids the creation of an effectively duplicate branch. We can document in the PR description full details about the production issue and the nature of the hotfix. 

Good catch on the missing Git push - you're right - that's my mistake - now corrected!

In practice I use the Intellij Git workflow but I thought we should document a workflow in the Wiki that doesn't depend on Intellij. In case someone isn't using Intellij, unlikely as that may be. There are certainly advantages of committing through Intellij as you've outlined. I haven't found a way yet of tagging via Intellij but there probably is a way to do that too - something to look into.

Thanks again for reviewing. I've updated the Wiki with the relevant Git pushes and documented the steps for PR creation into staging.

**Comment by sadatmalik** [comment]
- [ ] Give the workflow an end to end run through with a Readme update
- [ ] Leave for review - all team
