### ISSUE TITLE
Deleting the contents of a string field value in Search does not clear the search field

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#29]
To reproduce this issue:

1. Click New Search
2. In Referrer type "Alight" - click Apply - no matches
3. Delete "Alight" in Referrer
4. In Partner select Alight - click Apply - should have matches but don't see any

If you now click "Clear Search" - reselect Partner "Alight" and click Apply - you will see matches.

Suspect that step "3" above doesn't set the referrer to empty (null) but trims it down to a blank string (i.e. "")

**Comment by tbbadmin** [comment]
Paired up with Sam on this one. @param makes sense in the context of a method's Javadoc (but don't make sense on class properties which are not params). The doc comments themselves are looking great.

**Comment by samschlicht** [comment]
Hey @sadatmalik this one was moved back from Done to Review — curious why as I think it's merged at this point?

**Comment by tbbadmin** [comment]
Hey @Sam ***@***.***> I think this may have been accidentally moved by me in a demo – that’s my bad, apologies.

I try to only move my tickets around when demoing (and then hopefully remember to undo any damage by resetting anything I’ve changed) but I guess this one slipped through!



From: samschlicht ***@***.***>
Date: Monday, 10 July 2023 at 02:22
To: talentbeyondboundaries/tbbtalentv2 ***@***.***>
Cc: tbbadmin ***@***.***>, Comment ***@***.***>
Subject: Re: [talentbeyondboundaries/tbbtalentv2] Deleting the contents of a string field value in Search does not clear the search field (Issue #29)

Hey @sadatmalik<https://github.com/sadatmalik> this one was moved back from Done to Review — curious why as I think it's merged at this point?

**Comment by tbbadmin** [comment]
No worries, just checking there wasn't anything for me still to do!

Sam
