### ISSUE TITLE
Visa Intakes - Standardise way to store different language thresholds

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#290]
Currently hardcoded if candidate meets an english language threshold, however different countries will need to store additional language thresholds (e.g. Canada needs a meets french language threshold, some countries may need spanish/german etc...). We need a flexible way to store these. Options?
1. In a one to many table - languageThreshold (languageId, candidateId, meetsThreshold)
2. A multiselect dropdown where languages can be selected under a question such as "Select languages the candidate meets the threshold for?" Can provide a notes field for more information to be added.

**Comment by cazcam34** [comment]
Discussed and going for easiest option 2. This should work for the interim and in shared google doc when creating canada visa intake we discussed why we need a flexible workaround. She didn't provide any further input so safe to assume this is sufficient and will be an improvement on what is currently in there (just added in english threshold notes).
Google doc: (https://docs.google.com/document/d/1xPglPXr8k6wjYN3BcnOmUjp_z9ZNVP3c2mSChj5VS3M/edit?pli=1)

<img width="1618" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUMzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9bec778d9e97a9128d2b9a8a6764b45e0b1b6592/Screen%20Shot%202024-01-11%20at%2010.56.43%20am.png" alt="Screen Shot 2024-01-11 at 10.56.43 am.png" />

**Comment by cazcam34** [comment]
Update: Realised two new fields required (1. select the languages that are required for role & 2. does candidate meet these language thresholds).

- [x] Create new DB field (languagesRequired)
- [x] Create new DB field (languagesThresholdMet)
- [x] Rename notes field (englishThresholdNotes) to languagesThresholdNotes
- [x] Create new TC field languagesRequired multiselect list of country ids.
- [x] Create new TC field languagesThresholdMet (yes/no)
- [x] Front end create multiselect saving country ids w/ question eg 'select languages candidate meets threshold for'
- [x] Create flyway SQL to populate english id into new field list of ids if it exists, and to populate the meets requirements to Yes if Yes.
- [ ] Remove english threshold question from front end
- [x] Add new fields to tests
- [ ] Drop english threshold field once all done

**Comment by sadatmalik** [comment]
<img width="1188" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFBOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--181dc3bd677c2d8c87f987395bac9e213de18c05/Screenshot%202024-01-16%20at%2013.47.35.png" alt="Screenshot 2024-01-16 at 13.47.35.png" />
