### ISSUE TITLE
Ngb Accordion component to be deprecated in the newest angular version 16.0. Update to directive.

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#303]
Need to update the <ngb-accordion> component to an ngbAccordion directive. See details here: https://ng-bootstrap.github.io/#/components/accordion/overview

**Comment by sadatmalik** [comment]
Related to #352

**Comment by sadatmalik** [comment]
The deprecation will be with Bootstrap version 16, not Angular version 16.

We have moved to Angular 16 in issue #352 with a related Bootstrap upgrade to v15. When we update to Angular 17 and Bootsrap 16; the Ngb Accordian will be deprecated and should be moved to the newest version.

**Comment by cazcam34** [comment]
@sadatmalik yes apologies I can see I was mistaken with this, as you say it refers to the bootstrap version. I'll close this with this comment.
