### ISSUE TITLE
Remove Recaptcha

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#311]
See pic for the little error at the bottom of the screen. The full text reads 'ERROR for site owner: Invalid domain for site key Privacy - Terms'

Not critical as presumably an attack on tc-test is unlikely — but not very elegant, as we start to make more use of tc-test.

A quick reading suggests that we just need to log into Google an add this domain name to the site key. https://help.whmcs.com/m/troubleshooting/l/1189046-troubleshooting-recaptcha-invalid-domain-for-site-key

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1dwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26ab80971a56f29382999dccaafe33d4d6ef7774/Screenshot%202023-09-18%20at%202.34.37%20pm.png)

**Comment by camerojo** [comment]
We no longer need recaptcha on admin now that we have standardized on MFA - so I will remove it altogether
