### ISSUE TITLE
Transition the Repo

### ISSUE THREAD

**Issue by tbbadmin** [talentbeyondboundaries/tbbtalentv2#34]
As an engineering team
We would like to transition from a personal to an organisation Github repo
So that we can have more than one Repo administrators

Note - new organisation / repo name - talentcatalog/tctalent ??  (confirm with JC)

**Comment by sadatmalik** [comment]
Useful links:

https://docs.github.com/en/get-started/learning-about-github/access-permissions-on-github#organization-accounts

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by sadatmalik** [comment]
- [x] Add organisation members first so that issue assignments remain intact on transition
- [x] Transition the Repo
- [x] Set Repo admins
- [x] Start using Repo for issues, branches and PRs
