### ISSUE TITLE
Problem connecting with Salesforce

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#341]
Hi <@U3TVD430A> <@U055YR1QT0A>
I keep getting this message on TC when I am trying to change the opportunity stage:
`org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest: 400 Bad Request from POST <https://test.salesforce.com/services/oauth2/token?grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&amp;assertion=eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiAiIiwgInN1YiI6ICIiLCAiYXVkIjogImh0dHBzOi8vdGVzdC5zYWxlc2ZvcmNlLmNvbS8iLCAiZXhwIjogIjE2OTYyMTI3NzEifQ.uMQufslVKoJlva2aPyJ2KB3GOaQHgqYuDGWWBhZwVl4HZ5nJZ2jrcywIJR5GgD1FA0L6Aa5TqeOYBNxpuChx-UbWdBVz17stZibhawL9JvT89_TnqgvVUmNmawXQauFa61M96RrrCL2n0jJRZkIzYKFuBwq41fUxnTYo0I1CRqI>`
I am trying to change the stage for candidates in this <https://tctalent.org/admin-portal/list/7068|list>.
Thanks for your help! :heart:

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1696212736373409?thread_ts=1696212736.373409&cid=C42S4AJ73)

**Comment by cazcam34** [comment]
Not 100% this will fix Naji's issue, as it's a front end fix however could be a contributing factor. But it does seem that all SF links in prod are broken due to a small spelling mistake in the env sf url. See where my cursor is, there is a '.' missing so all sf links are going to https://talentbeyondboundarieslightning.force.com/ instead of https://talentbeyondboundaries.lightning.force.com/. I have created a pull request with this fix and assigned it to this issue although more needs to be done in the branch to fix Naji's issue:
<img width="868" alt="Screen Shot 2023-10-02 at 4 15 39 pm" src="https://github.com/Talent-Catalog/talentcatalog/assets/43192228/f6ed270e-755f-4e0f-a9b1-e5fd2e21cd94">

**Comment by cazcam34** [comment]
Is it odd that his request is going to test.salesforce.com also? I am not very familiar with this code, so unsure if that's normal or not.

**Comment by camerojo** [comment]
Yes - that is definitely a problem. Well done tracking it down @cazcam34.

I am am going to take a longer look at the code - front end and back. Can you look too? We want to see if there are any other problems with how production connects to SF.

Then when @sadatmalik comes on line we can discuss next steps together.

**Comment by camerojo** [comment]
Note that we don't really want to restart production anyway - until the Elastic Search update has completed.

**Comment by camerojo** [comment]
> Is it odd that his request is going to test.salesforce.com also? I am not very familiar with this code, so unsure if that's normal or not.

I think that this might be Salesforce doing a url rewrite of all those user specific links to their standard Sandbox which has the domain test.salesforce.com - just guessing.

**Comment by sadatmalik** [comment]
- [x] Check staging vs prod tasks (Sadat)
- [x] Check back-end code in depth (John/Sadat)
- [x] How does the bad URL redirect?
- [x] Merge Caroline's PR
- [x] Restart
- [x] Admin API esload variant (John)
- [x] PG database tests (Sadat)
- [x] Integration tests post release - confirm all external services connect
