### ISSUE TITLE
Forced logout for sourcepartneradmins when deleting a visa check. Should throw error instead.

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#347]
Automatic forced logout for SPA's when it should throw error. BUT should SPAs be allowed to delete a country visa check? What about delete job visa check? I'd suggest no, as these records can be overwritten if needed and really shouldn't be deleted.

**Comment by cazcam34** [comment]
Best to hide the delete button or do i keep the button and throw an error 'You do not have permission to delete this check'

**Comment by cazcam34** [comment]
Same logout for deleting tasks as a SPA. Best show icon and show error, or remove icon.

**Comment by sadatmalik** [comment]
John - safe thing might be to not have the delete button i.e. it's like deleting a job - doesn't make sense. Deleting a visa check could be a system admin function.
