### ISSUE TITLE
We need more flexible mapping of Salesforce json API responses to map to Java objects

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#35]
Our current code uses the default of mapping json field names directly to Java properties on the receiving Java object with the same field name.
 
This does not work when the json field to be mapped uses dot notation - for example "Account.Description". This is not an allowed Java property name - so the default mapping won't work.

@sadatmalik felt that it should be possible to control the mapping using field annotations. Can we confirm that this is possible, and if so implement it in our Spring SalesforceService code.

See, for example, org/tbbtalent/server/model/sf/Opportunity.java and the code that uses it in org/tbbtalent/server/service/db/impl/SalesforceServiceImpl.java

**Comment by sadatmalik** [comment]
Mapping the SF field names to Java filed names with the JsonSetter annotation.

![Screenshot 2023-05-26 at 14.35.00.png](https://images.zenhubusercontent.com/646cd77ef0193a455894c3a4/dfabe1a4-f790-44c9-a521-2fb7d4399f88)

**Comment by sadatmalik** [comment]
API test results when using JsonSetters to map SF field to Java field names for SF Contact - 

![Screenshot 2023-05-26 at 17.06.07.png](https://images.zenhubusercontent.com/646cd77ef0193a455894c3a4/5748be37-61fe-4b67-a28e-fc1fc6826b00)
