### ISSUE TITLE
Clarify Login Username

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#361]
Hello <@U055YR1QT0A> <@U3TVD430A>
I was wondering if it would be possible to make a small change on the <https://tctalent.org/candidate-portal/?returnUrl=%2Fhome|TC log in homepage>. Instead of just having "*username*," could we replace it with "*username (email)*"? We've been working hard to raise awareness, but unfortunately, some candidates still mistakenly believe that their log in username is their TBB ID.

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1696586525071419?thread_ts=1696586525.071419&cid=C42S4AJ73)

**Comment by sadatmalik** [comment]
This relates to #131 - clarify registration screens

**Comment by cazcam34** [comment]
This is actually just a translations change - I couldn't edit translations, can I be made a system admin? Once translation updated I can get back to the Slack message and let them know, also ask for more translations?

**Comment by sadatmalik** [comment]
Also relate to #507 - (document translation process)

**Comment by sadatmalik** [comment]
Closing issue - no further action needed - handled in: #131 and #507
