### ISSUE TITLE
Update Opportunity Progress dialogue display issue

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#435]
This update opportunity progress dialogue is not displaying properly for some candidate opportunities.

For example - see image - the stage selection drop down is screwed up for this candidate opp:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDYxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--819a23cd8d6b5658ca625dc8f96a225b10305648/Screenshot%202023-11-08%20at%2011.57.11.png)

**Comment by sadatmalik** [comment]
Investigation shows some data discrepancy for candidate opportunities where this issues occurs:

1. Jobs for candidate #7087

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWUxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51e0aa0ad0677d79c216ab1089c9d10e98a05fc6/Screenshot%202023-11-08%20at%2012.13.30.png)

2. Zooming in on opportunity #3443 - the stage select drop down is broken:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW0xQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b96bdbda3db037293a86a96ebacfaffa84865d3b/Screenshot%202023-11-08%20at%2012.15.13.png)

3. The corresponding entry in the candidate_opportunity table has a different candidate id - it should be #7087

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTYxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b03801623934bf5d01dc0b735b0c35e2cce73cd8/Screenshot%202023-11-08%20at%2012.16.57.png)

**Comment by sadatmalik** [comment]
submissionList undefined in this.savedListService.get(opp.jobOpp.submissionList.id) in edit-opp.component.ts:

```
  checkOpenCases(opp: CandidateOpportunity) {
    if (!this.opp.closed) {
      const request: SearchCandidateSourcesRequest = {
        keyword: null, global: null, owned: null, shared: null
      }
      this.savedListService
        .get(opp.jobOpp.submissionList.id)
        .pipe(
          switchMap((fullList) =>
            this.candidateSourceCandidateService.search(fullList, request)
          )
        )
        .subscribe((result) => {
          this.isOnlyOpenCaseOfParentJob = (result.length === 1);
        },
          (error) => this.error = error);
      }
    }
```

Indeed the submission_list_id is null in the database salesforce_job_opp entry for this job_is #512:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXU0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58daf3ef16716335a561c0fcf88efedca5e49f96/Screenshot%202023-11-08%20at%2019.56.49.png)

**Comment by sadatmalik** [comment]
Check how many of these there are in staging/prod (focus on more recent)

**Comment by sadatmalik** [comment]
The following steps resolve the dialogue display issue:

1. Create a new list (or assign the existing submission list - if you can find it) to the job #512
2. Update the submission_list_id in the salesforce_job_opp table - set it manually to #4647

Are these steps valid? Yes. Confirmed with John.
Should the submissison_list_id automatically update? No.
Is there another way to do this?

**Comment by cazcam34** [comment]
SQL to check how many job opps have no submission list (and are not closed):
`select * from salesforce_job_opp s where s.submission_list_id is null and closed is false;`

**Comment by sadatmalik** [comment]
Count in Staging - 91
Count in Prod - 88 - makes sense as have manually fixed 3

Plan: Fix them all in Prod and then on next DB synch they will update in Staging too.

**Comment by sadatmalik** [comment]
Fully updated in Prod - now there are no jobs remaining in the database without a submission list attached.

Copy from Prod after the next release to resolve any gaps in Staging.
