### ISSUE TITLE
Improve look and feel of Job Chat post user interface

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#444]

**Comment by cazcam34** [comment]
Preview of what I've done to the chat components, the left side still needs work:
<img width="1550" alt="Screenshot 2023-11-27 at 3 46 50 pm" src="https://github.com/Talent-Catalog/talentcatalog/assets/43192228/292a1f8e-f7cd-405a-9c50-b20af1931509">

**Comment by cazcam34** [comment]
I have a question @camerojo around what to do with the source partner contacts. Depending on the type of user, do we want to hide contacts? Eg. If a candidate works for Afghan Talent and we only allow them to chat with talent beyond boundaries, can we then also hide the source partner contacts? I think I can make this left side of the screen look better and more 'slack' like, but at the moment its a bit confusing that its the contact details of all source partners, as well as a chat screen.
