### ISSUE TITLE
Read/Unread - JobChat Notifications - Front end

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#445]
As a chat user
I want to be able to be notified of new posts to chats and record whether I have read a chat or not
so that I can be aware of new messages coming and so that I can see which chats I have looked at, or still need to look at.

**Comment by camerojo** [comment]
# Implementation 

Each chat will have a toggling button "Mark read/unread" (or something equivalent)

Clicking that button will send a message to the server, updating the database recording whether or not the chat has been read by the user.

The data can be stored in a table UserReadChat which stores an entry for each chat read by a user

user/chat/timestamp(or last read post id)

That entry records that the user has indicated that they have read the chat.

When a new post is made on a chat, all entries for that chat will be removed from the table - because the chat now contains new information unread by any user.

On the front end, a new component can be created which monitors and displays the read/unread status of a chat. Instances of this component are used to notify the user of new chat posts that they have not read. It may simply display an asterisk (for example) indicating that the chat has unread posts. This component queries the initial "read status" of the chat (from the UserReadChat table on the server), and then subscribes to the stream of post updates received by subscribing to the chat, merged with a stream of "user read chat" events. The latter stream is generated completely locally from the Angular code (rather than events from the server).
The component subscribes to the stream when it is displayed, an unsubscribes when it is not displayed. A new chat post causes the component to display "unread", a "user read chat" event causes the component to display "read".
 @sadatmalik

**Comment by sadatmalik** [comment]
Create a Spring JPA entity JobChatParticipant to track the read status for each participant in a chat. 

An example database schema for such an entity's corresponding DB table:

```
CREATE TABLE job_chat_participant (
    chat_id INT,
    user_id INT,
    last_read_post_id INT,
    PRIMARY KEY (chat_id, user_id),
    FOREIGN KEY (chat_id) REFERENCES job_chat(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
```

- chat_id: Identifier for the job chat.
- user_id: Identifier for the user.
- last_read_post_id: The ID of the last post the user has read in the job chat.

The table allows tracking of the last read post for each participant in a job chat.

When a user reads a post in a job chat, update the last_read_post_id for that user and chat in the job_chat_participants table.

Expose API endpoints for updating and retrieving read status for job chats:

- `POST /api/job-chats/:jobChatId/posts/:postId/read`: Mark a post as read for the current user in a job chat.

- `GET /api/job-chats/:jobChatId/participants/:userId/latest-read-post`: Retrieve the ID of the latest post that a specific user has read in a job chat.

Response:

```
{
  "latestReadPostId": 789
}
```

Potentially for a future release:

- `GET /api/job-chats/:jobChatId/posts`: Retrieve posts for a job chat, taking into account the read status of each participant.

Response:  

```
[
  {
    "postId": 456,
    "content": "Hello, World!",
    "sender": "user4",
    "timestamp": "xxxxxx",
    "readStatus": {
      "user1": true,
      "user2": true,
      "user3": false
    }
  },
  // More posts...
]
```
[ Additionally would need to push real-time updates over the WebSockets API when read-status changes. ]

**Comment by camerojo** [comment]
@sadatmalik I added a paragraph above on a front end mechanism for processing incoming chat posts.

I think that our solutions are more or less the same but there are a couple of differences.

- In my approach, I only propose recording whether a chat has been read or not - without trying to cope with partially read chats. I used timestamp - but I think that using the latest post id at the time the user looks at the chat is probably better - and closer to your model. But I am proposing for simplicity (and also to reduce traffic) that we don't need to support partially read chats - ie that the user has read up to this post, but still hasn't acknowledged all following posts.
- The JobChatParticipant table has the potential to grow indefinitely and could get pretty large given that many chats are created for each opportunity. Given that I am only interested in recording whether a user is up to date with a chat or not (rather than knowing exactly where they got up to), that allows me to remove entries from the table when new posts are made to a chat. I can do that because I don't mind losing exactly what was the last post each user read on a chat - I just need to know that there is something new they haven't seen.
 
So I guess the question is: "Do we need to support partially read chats"

Slack does support that. For example, if I go to a chat they display a red "New" line after my last read post. If we want to do that we need to go with your solution. But if we just want to display when something new has been posted since the user last looked at a chat, my solution will do.

I think that difference between us and Slack is that our number of chat channels grow continuously and become less interesting over time - for example the chats associated with a candidate opportunity that didn't go anywhere might be of interest to the candidate concerned, but probably of diminishing interest to others. And what interest there is will be related to the content rather than where each user read up to.

Slack is configurable on how a channel is marked read. 
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnFsQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b85bb2361122fbafa75121c4095ca7e6cf84ba1b/Screen%20Shot%202024-01-08%20at%206.08.03%20pm.png" alt="Screen Shot 2024-01-08 at 6.08.03 pm.png" />

**Comment by camerojo** [comment]
- [x] Add notification component to all source partners
- [x] Add notification component to candidate case
- [x] Make chat names look like links in candidate portal
- [x] Add notification component to candidate portal - still need to put notification by job name in list
- [x] Chats are static - so can be cached by request rather than being retrieved each time. Hash from request?
- [x] Check existing translation keys by giving them values in dev env.
- [x] Support providing translation keys for chat component messages - eg Post, Send
- [x] Fix combineLatest bug - needs to work for ALL chats (not just 2)
- [x] Handle onDestroy for new Observables in ChatService

**Comment by camerojo** [comment]
- [ ] Error https://stackoverflow.com/questions/73284811/should-we-always-create-a-taskexecutor-bean-named-taskexecutor-when-we-use-en When running create_employer_for_all_jobs

**Comment by camerojo** [comment]
I think that marking the chat as read should be a PUT rather than a POST because it is idempotent - ie same request multiple times from same user will not change state further
