### ISSUE TITLE
Uploads of files (images and other docs) to JobChat posts

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#446]

**Comment by cazcam34** [comment]
Store uploaded link in the html of the post - rather than in the database in a field.

**Comment by cazcam34** [comment]
Going to move to ngx-quill from ngx-wig. Will create new issue.

**Comment by cazcam34** [comment]
- [x] Create ChatUploads folder in job google folder - this is where we will store the post uploads
- [x] Rename the file with a prefix indicating the job chat id (ChatId_FileName)
- [x] Figure out how we give access to the file, tested briefly sharing with public google link but didn't seem to work. Tested with a regular google image link and it worked.
- [x] How can i return a file url string back in the api, that isn't saved to an object/database.

**Comment by cazcam34** [comment]
Alternative to custom image handler https://www.npmjs.com/package/ngx-quill-upload

**Comment by cazcam34** [comment]
Dont forget PDFs uploads
Test on all other chats (standardise the chat view)
