### ISSUE TITLE
Support for emojis in Job Chats

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#488]

**Comment by camerojo** [comment]
See https://plainenglish.io/blog/how-to-add-emoji-to-your-angular-application

**Comment by camerojo** [comment]
Not also that we need emojis to react to a post

**Comment by samschlicht** [comment]
NB: I had to go for version 6.2.0 as we're running Angular 13

<img width="675" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDEyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a92acdaa88e6539cf20441d1d547074e35e0188b/Screenshot%202024-02-21%20at%2010.07.45%E2%80%AFam.png" alt="Screenshot 2024-02-21 at 10.07.45 am.png" />

**Comment by samschlicht** [comment]
Emoji picker is up and running on both portals. The version made specifically for Quill simply didn't work — the latest version is 4 years old and with scant doc, so perhaps not surprising. Unfortunately I sank a fair bit of time into trying to make it happen.

Anyway, instead I downloaded [emoji-mart](https://www.npmjs.com/package/@ctrl/ngx-emoji-mart) version 6.2.0 which works with our v13 version of Angular. It's obviously not made for Quill and so took a lot of CSS and TypeScript work to get it behaving more or less as we would like. When we upgrade Angular, we may look at newer versions, which would allow for removing some of my code.

Candidate portal is heavily adapted for mobile. Again, once we align Font Awesome versions with the admin portal, some of the code could be reviewed. But both are stable and look okay, in my view!

<img width="444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFNRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--159e94b296bd2d3df827c247e62dad2de80b8204/Screenshot%202024-02-27%20at%204.36.48%E2%80%AFpm.png" alt="Screenshot 2024-02-27 at 4.36.48 pm.png" />

<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFdRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad1198297b5b3b8c56730431abe32b7249299a5f/Screenshot%202024-02-27%20at%204.34.04%E2%80%AFpm.png" alt="Screenshot 2024-02-27 at 4.34.04 pm.png" />

**Comment by samschlicht** [comment]
Back-end is implemented for the chat post emoji-reactions. I'm aiming for something similar to Slack and it should work in group chats in a similar fashion (users can upvote others' reactions and see who has done the same). Therefore we have a one-to-many post-to-reaction relationship and the object also stores the user IDs of all who have upvoted — as on Slack, they'll also be able to retract their upvote and obviously it'll be deleted if everyone retracts.

**Comment by samschlicht** [comment]
I've got this looking and behaving a lot smoother now. Since it's all very active, I'd advise checking out the branch rather than me putting lots of pictures here. Happy to do a show-and-tell in meeting.
