### ISSUE TITLE
Support for reactions (eg like) to JobChat posts

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#515]

**Comment by camerojo** [comment]
As a Job Chat user 
I would like to be able to give a quick reaction to a post - eg a like - using an emoji
in order to give a quick personal response to the post

**Comment by camerojo** [comment]
This adds data associated with each post.

Each post can have a collection of the following data associated with it:

post id, reacting user id, emoji

The same emoji cannot appear twice for the same user/post. Attempting to apply the reaction again, removes the entry.  So reactions can be toggled on and off (ie typical reaction functionality)

**Comment by sadatmalik** [comment]
This has been done with release 2.2.1
