### ISSUE TITLE
Preview links in Chat Posts

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#523]
Here's a vid to illustrate what's in the PR:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMExjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6468e035d15b40157fb3482dfa9c6048484e9f8/Screen%20sharing%20-%202024-07-15%201_03_14%20PM.mp4)

**Comment by samschlicht** [comment]
I'm going to have a go at implementing Gaydos's solution (see JC link), adding the Puppeteer library and implementing it in a new Angular component.

**Comment by samschlicht** [comment]
Made a start on this but unfortunately link support is not currently working, so I've lodged a bug issue (#1133) to take care of that first.

UPDATE: it's more the imperfections of the Quill Editor. I'm going to stick with creating this new component for now, which we can repurpose to work with any editor.

**Comment by samschlicht** [comment]
- [ ] identify when link entered in editor
- [ ] extract the URL and send to child component

**Comment by samschlicht** [comment]
I've gone with JSoup and server-side scraping. I had difficulties getting Puppeteer to work and anyway looking at its Git, it seems quite buggy and there isn't a lot of work going on to fix that. 

I've still used [the blog post](https://andrejgajdos.com/how-to-create-a-link-preview/) that JC included but adapted the Javascript/Puppeteer instructions for Java/Jsoup - it's a good resource for creating a scraping hierarchy for the link preview properties.
