### ISSUE TITLE
WB surveys - planning

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#536]
From Sarah W:

I spoke to the research team and these are the key points that they were asking about whether it could be done in SF:

1) For each job offer, change the status of the candidates considered by TBB to reflect that they have been selected to a position before (ex. considered for position). Anyone considered for a position will be automatically sent the baseline survey. One important condition here to avoid sending the baseline survey several times if a person is considered for several positions, is to never change back the status of this candidate - _I think for this we would need a condition for each candidate contact that if they have been sent the baseline survey once, they will not be sent it again._ 

2) For each job offer, all considered candidates will be tied to one group (probably tied to the job itself), and will be automatically sent the first follow-up survey six months after the selected candidate arrives at the destination, so after the status of this candidate changes to "arrived to destination"- _Sam and I thought this could be done by adding a "Relocated" stage to the employer opportunity, so when the candidate relocates, all candidates attached to this job opportunity will get the survey once the selected  candidate(s) has relocated_ 

3) If a candidate is not successful for one opportunity, but is then put forward for another opportunity and gets the job, then when their changes status from "Considered for position" to "Selected", then this candidate must: a) Be dropped from the first group they were tied to. b) Not be sent a link for the baseline survey, yet the rest of the group selected for the same position, must receive the survey, c) Become the new anchor person to which follow-ups surveys for the group of selected candidates will be sent after his arrival - _this one is abit trickier and might need some though_ 

[Slack Message](https://refugeejobsmarket.slack.com/archives/D05DZ9HA2LB/p1703078183629199)

**Comment by samschlicht** [comment]
The technicalities for SF automation here are tricky, but at first consideration, probably achievable.

What I want to clear with our team is the principle of surveying unsuccessful candidates (considered for a job but didn't get it). Here is Sarah's case for the ethics:

- Asking for the candidates consent at intake - someone from source team would tell them about the project on the phone, answer their questions, and that we will be sending surveys and also sending reminders though email and calls. We wont send surveys to people who dont consent.
- The consent form would be translated into Arabic and other languages
- We have budget for incentives - we will offer a gift card as a prize for completing the survey
- We have had a meeting to get feedback on the survey from the UK alumni committee - so getting feedback from our candidates who have been through the process about these points (how to manage expectations for candidates who dont get a job, incentives etc)
- The researchers are from Oxford University RSC and other universities, who have done research and surveys with vulnerable refugee populations in East Africa and Jordan
- We are trying to shorten the survey to 15 minutes (to not take up too much of peoples time!)
- We are also getting input and feedback from the World Bank about how to conduct them
- I have spoken to Noura and Steph about this and they are supportive.

I'm not necessarily against this, particularly now there's talk of remuneration, which I think is appropriate. Just checking everyone on the team is comfortable, before I move ahead.

**Comment by samschlicht** [comment]
Here's the research brief:
https://docs.google.com/document/d/1fE9zbcXRlawsbvIvDCqtCMrkPiVSivxHDZOzKURrdn4/edit

**Comment by samschlicht** [comment]
And finally just adding that there will probably need to be a survey consent checkbox added to the TC intake.

**Comment by samschlicht** [comment]
Closing this issue and will summarise the project in the epic and write some new issues accordingly
