### ISSUE TITLE
Release tasks 2.2.0

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#539]
As the tech team
we need to capture somewhere special manual tasks that have to be carried out for a release
so that we don't forget 

Typically we will carry out these tasks progressively over time on staging, but all at once in production.

We should add the tasks as a task list as we carry them out on staging, then when we release into production, we just copy the task list, and mark them off as we complete them on production. 

I suggest that this issue starts in Review/QA so that we can always easily find it. It is only moved to Done when the production release is completed.

See also Issue #429

**Comment by camerojo** [comment]
### Staging task list

- [x] Rename database from tbbtalent to tctalent. See #176
- [x] Add new closing stage - Relocated no job offer pathway. See #257
- [ ] SystemAdminApi create_employer_for_all_jobs

**Comment by camerojo** [comment]
### Production task list

To be copied from staging task list above, then worked through during the production release.

**Comment by cazcam34** [comment]
See #429

**Comment by camerojo** [comment]
Duplicate of #429
