### ISSUE TITLE
Remove button does not work correctly on submission lists

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#543]
Reported by Naji - See Slack https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1704338823770919?thread_ts=1704255232.219629&cid=C42S4AJ73

The Remove button for submission lists should automatically close the corresponding SF opps - acting very similarly to the Update Cases(s) button (should be able to share same code - just with stages restricted to closing stages).

**Comment by camerojo** [comment]
There is a small but important other bug that came up when looking at this bug. Closed opps in submission lists do not appear by default (unless Show Closed Cases checkbox is checked). However, they may still be marked as selected. This means closed opps can unintentionally and invisibly get modified by any operation (ie button) that operates on "selected" cases. Either closed cases should automatically be unselected, or selection should ignore closed cases.

**Comment by cazcam34** [comment]
Made it so that when a case is closed it removes those case/s from the selection. There are still situations where we might want to do something to a closed case with a select method, so I don't think we want to ignore closed cases in the selected cases. I think we just want to deselect a case when it is closed.

**Comment by cazcam34** [comment]
Let Naji/Andrew & Rana know about this bug fix. Also created a short video to show how this button works: https://app.screencastify.com/v3/watch/kjVLY36RggGFGdUrzbxr
