### ISSUE TITLE
Copy terraform.tfvars to env.INFRA_PATH directory?

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#559]
Terraform checks are failing in Github whenever we submit changes to TF files. @sadatmalik has diagnosed that this is caused by the following outstanding TODO (the Github Action goes looking for the terraform.tfvars file and it isn't where it's meant to be):

from terraform-plan.yml:
<img width="767" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejZ5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7f3f11b82eb48fe9c72ef0f4ea9a9f26c593898/Screenshot%202024-01-10%20at%201.29.40%E2%80%AFpm.png" alt="Screenshot 2024-01-10 at 1.29.40 pm.png" />

On the one hand, the failing check has potential to cause confusion, as we've found. On the other, am I right thinking we will never actually deploy from Github, so on balance it might be better not to upload the terraform.tfvars file somewhere where it will never be used (but where it would periodically need updating)?

Will discuss w Sadat in 1-1.

**Comment by samschlicht** [comment]
Noting that I'll want to get the most up-to-date version of the file and edit it to include the environment variable introduced as part of #402. Once this issue is complete I should also run the TF checks on that issue to see if they've been resolved (since that was the instigation for moving ahead with this now).

**Comment by sadatmalik** [comment]
Hey Sam, good to create an issue for this. However I think we already had one; see issue #308 ?

If so, are you Ok to update #308 with any additional notes/comments; and we can close this one as a duplicate.

Agreed - let's keep the tfvars updated in its current location, with the new environment variable, as you mentioned; to ensure we have a working copy ready for when we do transition the deployment process - good thinking. 👍🏻

**Comment by samschlicht** [comment]
Ah sorry, missed that. Great, @sadatmalik — will do, and I've made a note in our 1-1 appointment to get the most recent version from you.
