### ISSUE TITLE
If we have an auto-assign partner for a given country, but a candidate signs up using a managing link from a second partner in that country, will they be assigned to the second partner?

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#583]
From Zeynep

**Comment by sadatmalik** [comment]
IRC are starting a project for US welcome core to consider there own candidates from Kenya and Uganda for opportunities within the US. 

Currently candidates from these locations are auto-assigned to FCA upon registration.

Candidates are assigned based on their location or a specific partner link. With location taking precedence over the partner link. For the IRC project, they would like candidates registering in these locations using their specific partner link to be auto-assigned to them.

We considered changing the precedence of location and partner link. But there may be side effects to doing it this way. John suggested an alternative would be to have a default partner for a location, so any registrations using a specific partner link go to the specific partner (e.g. IRC) and all other registrations for the location default to the default partner (e.g FCA).

**Comment by camerojo** [comment]
There is discussion underway on the best way to do this (particularly in a short time frame).

See https://refugeejobsmarket.slack.com/archives/C06QSPXH1RU/p1711149376943949

The solution I have proposed in the above discussion does not require any TC code changes.

**Comment by camerojo** [comment]
It appears that my proposed solution has been accepted. See the Slack reference above.

However, as a separate issue for the next release I have suggested explicit support for a new type of operating source partner: a "Specialist Source Partner" - See #804
