### ISSUE TITLE
A few Chat / Job styling bits to tidy up

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#609]
A few niggles (not necessarily bugs) - see screenshots below

**Comment by sadatmalik** [comment]
- [x] Missing a column header title for Full Name:

<img width="1319" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEVPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06fd61c9a33b3473216194378af41199d0a3a0ec/Missing%20column%20header%20title.png" alt="Missing column header title.png" />

**Comment by sadatmalik** [comment]
- [x] Missing responsive table styling on group chats:

<img width="1434" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFFPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57caf285df92e57a1dc9b9ddf345963286083f9c/Style%20this%20similarly%20to%20Partners-Chats.png" alt="Style this similarly to Partners-Chats.png" />

**Comment by sadatmalik** [comment]
- [x] Consider adding table styling to candidate chats?

<img width="612" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGdPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c98a23652ab252f23c3ecdb11e5b6b5f610a9ce/Job%20chat%20list%20styling.png" alt="Job chat list styling.png" />

**Comment by sadatmalik** [comment]
- [x] Consider adding tool tips to Job tabs? (as discussed just the two chats tabs)

<img width="1436" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHNPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34d7d2cb5a22343a2a6cd622381ddb76883f941e/Tooltips%20on%20Jobs%20tabs.png" alt="Tooltips on Jobs tabs.png" />

**Comment by sadatmalik** [comment]
- [x] Consider Styling and re-positioning of Publish Job button:

<img width="1786" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--740c20c018eb47c066963e6dbfb4d17a12a4f848/publish%20job%20styling%20and%20position.png" alt="publish job styling and position.png" />

**Comment by sadatmalik** [comment]
- [x] Add new partner selection box spacing:

<img width="522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFFQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad1e9998d661459c2884796417b278f110f4ae05/Screenshot%202024-01-30%20at%2013.05.03.png" alt="Screenshot 2024-01-30 at 13.05.03.png" />

**Comment by cazcam34** [comment]
Notes: 
- Editable on job chats -> button appears for semi limited, however user get's logged out if clicked as semi limited (check there are any semi limited users - probably not!) No semi limited users - ignore. (create issue )
- How to find a job I created but didnt publish? (have to enter stage prospect to view - maybe add checkbox for unpublished?) CREATE NEW ISSUE FOR THIS
- Advice on text for tooltips? (Chat with Dad tomorrow)
