### ISSUE TITLE
Change position of Publish Job button?

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#614]
To my eyes it looks a little at odds with the Job Summary box — wondering if it could even have its own row under _'Job Opportunity Number 31'_ and perhaps be single-row text (so a bit wider)? Interested in team's view.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk1hQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80741f567d12fd162d4983abcf01191ce7a91701/Screenshot%202024-02-01%20at%202.20.14%E2%80%AFpm.png" alt="Screenshot 2024-02-01 at 2.20.14 pm.png" />

**Comment by sadatmalik** [comment]
Hey Sam, I had the same thought. Caroline's sorted it already - see #609 

Therefore I'll close this as a duplicate.

**Comment by sadatmalik** [comment]
Hey Sam, I had the same thought. Caroline's sorted it already - see #609 

Therefore I'll close this as a duplicate

**Comment by samschlicht** [comment]
Great! Thanks, Sadat.

Sam
