### ISSUE TITLE
Candidate status changes from active need to reflect on SF

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#615]
With this release we've added TC status to SF candidate contact records. The nightly TC-SF sync only includes 'active' candidates (active, pending, incomplete). 

While the rationale for that made sense at the time, the following has occurred to me...

Currently, changing a candidate case on the TC to an employed stage will also change the candidate's status. This won't reflect on SF, since that candidate is no longer active and so won't be included in the sync.

Likewise, if a previously active candidate is marked 'unreachable' in the TC, that won't be picked up in the SF sync.

So, we're piling up candidates who're actually inactive but will appear to be active in SF.

My suggested fix for this is to just remove the status filter and include all candidate contact records. 

SF candidate stats will just have to be filtered the same way we do on the TC. Having the two databases aligned probably just makes more sense.

**Comment by sadatmalik** [comment]
Just updating this ticket following today's team meeting. 

Following discussion with John we decided to pick this up after the 2.2.0 release. We can look to roll it out with 2.2.1 or, if needs be, we can push it sooner as a hot-fix.

**Comment by samschlicht** [comment]
Wanted to note John's solution, which seems like the right one at first consideration: add an OR filter to also include all candidates who already have a SF link!

**Comment by samschlicht** [comment]
I've added a new repo SQL query to this effect. 

FYI it gets 96,278 out of 193,767 candidates.

As the query was previously written, it would've got 95,344 candidates, so not much difference, but avoiding what would've been a gradual accretion of outdated statuses on SF.

**Comment by samschlicht** [comment]
We don't know to what extent this sync affects performance yet, but I'm still considering ways it might be more efficient.

I did consider further filtering by 'updated_by', but unfortunately our audit fields aren't applied reliably enough — e.g. status change doesn't reflect. I'll note this as a new issue linking to this one, as perhaps I can revisit.

**Comment by samschlicht** [comment]
Left to do:
- [X] Check if current iteration has fired
It's not working, so as part of this issue, I need to troubleshoot that
- [X] Adjust scheduler lock time
Changed to 2am GMT - good time to get the least possible users and doesn't coincide with other sched methods
- [X] Replace env variable (back to prod)
- [X] Reinstate scheduler lock

**Comment by samschlicht** [comment]
I've added IgnoreCase to the running-environment check, just to be on the safe side — but I don't think that's the issue, since AWS task definition variables are returned case-sensitive.

`if (environment.equalsIgnoreCase(Environment.prod.name())) { ...`

I think I need to put a provisional method into staging (perhaps console logging the steps) to get a better idea what's happening. Got a 1-1 w John tomorrow so we may be able to do it together.

**Comment by samschlicht** [comment]
I will note that I think it's the running-environment variable that's causing the issue, by a process of elimination: 
- the scheduling is set up exactly the same as other methods that are successfully firing in prod — Shedlock is logging the method being called, but nothing is happening, no error messages or anything else; so it seems to be falling at the next hurdle, which is the env check.
- when I trigger the sync from TC local System Admin API, it works fine upserting to SF sandbox, so it's presumably not the SF code.

The running environment variable is unproven. It's also named 'environment', which could be interfering with the way these properties are accessed. (Noting that AWS task definition puts all these variables inside an array called 'environment', though it's not referenced in the YAML.)

I think I need to console log this step in staging to see what's happening. Worth trying on first consideration:

- renaming the variable e.g. to 'runningEnvironment'
- indenting it under a parent value (note in attached pic that it's the only property that isn't)

![Screenshot 2024-02-07 at 2 52 17 pm](https://github.com/Talent-Catalog/talentcatalog/assets/111261894/954a402d-8364-499e-99f8-06ab6310e5d9)

**Comment by samschlicht** [comment]
Can confirm that it's not the environment variable causing the issue! Triggering my method actually caused staging to shut down, but did log the correct variable first. Just merged another branch into staging with more logs to get a better idea of what part of the code is causing the issue.

**Comment by samschlicht** [comment]
It never gets further than the repository method. So why is it breaking there in staging/prod but not dev? 

It looks like it's running out of memory when it tries to put the list together. Is it too many candidate objects for one list? We are looking at 90k+.

<img width="1526" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2s5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ebf87b8351f1520117a1c4a49b0571aeae1d703/Screenshot%202024-02-08%20at%202.18.44%E2%80%AFpm.png" alt="Screenshot 2024-02-08 at 2.18.44 pm.png" />

Obviously in dev it's many fewer (around 20k) and the constraints will be different anyway. So maybe that's the issue.

**Comment by samschlicht** [comment]
The issue was putting the results in a list, which got far too big in staging and prod with the full DB in play.

I've started making a new method using Page instead — which definitely would've been the way to go from the beginning, but you can't win them all. In the meantime, John and I did a hotfix to stop it firing in prod. I'll aim to submit tomorrow the new, improved version!

**Comment by samschlicht** [comment]
- [ ] update release notes to reflect weekly not nightly
