### ISSUE TITLE
Google drive no longer embedding links in img tags

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#628]
As of Jan this year google has stopped using the embeddable link for drive files. This is causing google drive images to not display (see screenshot) in chats.

the image upload in chats still works, and it's saving the links correctly however it's just no longer displaying them. See the docs here for more:
https://support.google.com/sites/thread/253003338
https://support.google.com/drive/thread/253314542/since-last-night-my-forum-no-longer-displays-google-drive-images-embedded-in-the-text?hl=en

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2c5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61c07d26ab96bbd30951781480a0988ae3b5e480/Screen%20Shot%202024-02-08%20at%202.14.33%20pm.png" alt="Screen Shot 2024-02-08 at 2.14.33 pm.png" />

**Comment by cazcam34** [comment]
This occurs in both the post and the text editor widget. Interim solution is display the link as a text link (e.g https://drive.google.com/file/d/1sjQ99pu4Ns1CT98MaQOCNNyN88WtDBxR/view?usp=sharing) which can then be hyperlinked.

**Comment by cazcam34** [comment]
Update from google which I think reflects what has happened: https://workspaceupdates.googleblog.com/2023/10/upcoming-changes-to-third-party-cookies-in-google-drive.html

**Comment by cazcam34** [comment]
TODO: Uninstall ngx quill upload -> we no longer need! On both candidate and admin portal

**Comment by sadatmalik** [comment]
Waiting on #488

**Comment by cazcam34** [comment]
All working, but document links don't open in new tab once the content is posted. the target="_blank" disappears from the a link.
