### ISSUE TITLE
Move translation key logic into admin-portal as well as candidate-portal

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#645]
As a TC developer
I need to be able to use keys instead of hard coded text
so that I can share code between admin-portal and candidate-portal 
and also so that I can change displayed text without requiring a new release.

**Comment by camerojo** [comment]
Relates to #541

**Comment by samschlicht** [comment]
We'll need to add ngx-translate to the admin portal
