### ISSUE TITLE
create UK visa check

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#646]
Need to continue to roll out the visa checks on the TC. Canada is the latest with the updated 'standardised' style, so use that as the structure.

**Comment by samschlicht** [comment]
Worth considering #651 as an alternative solution here - Zeynep checked in with the UK and got the following info:

Nope, no one does an explicit visa check in UK. Their main eligibility criteria is that the candidate should be in need of a durable solution, have Minimum IELTS 4 and meet the needs of an employers. So source team submits candidates that fall under this criteria but because it is much more simpler to understand and implement there are no additional checks on whether candidates are eligible for the pathway or not

**Comment by samschlicht** [comment]
Spoke to John and just adding a note that we discussed the possibility of having the relocating dependants viewable and modifiable from the visa tab _and_ somewhere on the candidate opportunity. That way it would be accessible and logically placed irrespective of a country's visa process and the current stage of the recruitment. TBC!

**Comment by cazcam34** [comment]
Based on the comments above - I wonder if we really just need to add the sync dependants button/dropdown to the candidate case? Because it doesn't sound like UK is asking for a visa check... that we just want somewhere for the relocating dependants data to be updated.

Wonder if the real issue to work on here then is #651?

**Comment by cazcam34** [comment]
Chatted with @camerojo and it sounds like UK _should_ have a visa check... discuss with @sadatmalik

**Comment by cazcam34** [comment]
Discussed with Sadat - will keep simple and create a UK visa check but it will only contain the dependants question (sync). Can release this as 2.2 and mention to UK team that they now have a basic UK visa check which contains this question, but suggest they look at AU and CA visa checks and give them time to reflect if there is any greater use for their visa check. Will likely need to lead this conversation, but it's something we can then build on and encourage over time.

**Comment by cazcam34** [comment]
Problem deleting visa checks or visa job checks:
org.springframework.web.util.pattern.PatternParseException: No more pattern data allowed after {*...} or ** pattern element

Update: Fixed by adding new delete endpoints for visa check and visa job checks in Security Config - they should've been there anyways. However it could mean all 'other' delete endpoints still don't work...

**Comment by cazcam34** [comment]
Question: with having candidate dependants sync on the visa job check... what happens if someone deletes a visa job check? Do we even have the delete, instead we could just let people clear the fields. 
I think we should remove the option to delete visa job checks, once added they can be updated but shouldn't be deleted.

**Comment by cazcam34** [comment]
Occasionally after working successfully with SF staging, I start getting a new error stopping me from doing something I was doing before... Got both these errors when trying to sync candidates on a UK and an AU visa check.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGlXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3021b6d1c444523a9ddbc24921b1c183aafb4a25/Screen%20Shot%202024-06-27%20at%2011.48.13%20am.png" alt="Screen Shot 2024-06-27 at 11.48.13 am.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG1XQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--951bc8fcdb083c3e5e9362895d00af6de8f5dce2/Screen%20Shot%202024-06-27%20at%2011.49.05%20am.png" alt="Screen Shot 2024-06-27 at 11.49.05 am.png" />

Update! A few minutes later started working again...

**Comment by cazcam34** [comment]
Need new issue - candidate dependants relocating is saved on a visa job check. Currently however, we allow all candidate opps to be selected when choosing a job opp to associate to a visa job check. This means one candidate opp can technically be assigned to multiple candidate visa job checks via different countries visa checks. This creates confusion because in different visa job checks, there can be different number of dependants located. Realistically this shouldn't be a problem, because only one countries visa job check will be applicable to the job (the destination country of the job). But in any case we should filter the candidate opps displayed when adding a visa job check to only be the candidate opps that are based in the destination of the visa check.
Issue is #1122

**Comment by cazcam34** [comment]
Found a bug in my fix!! Argh!
