### ISSUE TITLE
Show "alert" information in headers of closed tabs in intake

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#662]
This came out of meeting with Louna where she requested a way to see key information summarized in intakes.

This information could include:

- Ages of all dependents on header of Dependents tab
- Any dependent health issues
- Primary candidate health issues on "Additional eligibility" tab
- Louna to get back with other info they might want highlighted

**Comment by cazcam34** [comment]
Duplication of issue #764 which was closed with PR #873
