### ISSUE TITLE
Visa eligibility checks - Canada (first section)

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#67]
As a destination team member,
I would like to complete a candidate's visa eligibility check on the Talent Catalog,
So that I can easily view the data (intake data, job data) and make the necessary visa check assessments in the one place (the TC).

**Comment by cazcam34** [comment]
Great post from Kat with videos explaining what they are after: https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1679688747853939

**Comment by cazcam34** [comment]
Collaborative Google doc: https://docs.google.com/document/d/1xPglPXr8k6wjYN3BcnOmUjp_z9ZNVP3c2mSChj5VS3M/edit#

**Comment by cazcam34** [comment]
- [x] Visa specific assessment questions added
- [x] Some missing questions for visa assessment (see collab google doc) for canada team to discuss with source 
- [ ] Job specific assessment questions added
- [x] Make sections easier to view, some displayed intake questions are quite long. Look at making collapsible?
- [ ] Timestamp work experience questions (see Kat's comment in doc)
- [ ] Job selection modal to select the job for the job specific checks
- [x] Make UI more inline with intakes (eg. try using accordions)
- [x] Remember the last viewed visa country that was selected
- [ ] Make new base class for country visa checks (different from intakeTab base class which I am using) - or do I incorporate into same class?
- [x] I wonder if I should move the questions under each section of 'data' to the top, easier to see the responses that way.

**Comment by camerojo** [comment]
(this is Caroline on John's computer) I have two different versions of the UI, canada has an 'improved' version using accordions to be inline with intakes. And it helps to reduce the clutter on the page. Australia has previous version (unchanged). I have another alternative view also, but will await some feedback.

**Comment by cazcam34** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/TC-Engineering-646c91f0c3176e1ce584ec28/issues/talentbeyondboundaries/tbbtalentv2/67?planning-poker) with Zenhub @sadatmalik @samschlicht

**Comment by cazcam34** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/TC-Engineering-646c91f0c3176e1ce584ec28/issues/talentbeyondboundaries/tbbtalentv2/67?planning-poker) with Zenhub @cazcam34

**Comment by cazcam34** [comment]
I have completed the first section of the visa check for Canada - it is ready for feedback from the Canada team. I will create a new issue with the second half of the visa check.
