### ISSUE TITLE
Exception in Candidate Portal jobs tab

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#692]
From Hanine:

This candidate has messaged us about an issue he’s facing with his TC profile. The Job tab shows this message. His TBB ID: 49127

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1709155573014529)

<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2pkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efa4c35a51dfd3c22a6de6ffb814fc0fa2402281/72df22ef-3142-4fc5-a1d6-0587815be27b.jpg" alt="72df22ef-3142-4fc5-a1d6-0587815be27b.jpg" />

**Comment by camerojo** [comment]
I think that this is a chat related bug that has already been fixed.

I have posted that to the user who reported it.
