### ISSUE TITLE
AWS configuration - increase CPU

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#70]

**Comment by sadatmalik** [comment]
Follow up recommendations from Support:

As access-logs at the ALB if was enabled would have helped in troubleshooting from the ELB Team support, however for future reference you can surely enable those so that a deep-dive can be done.

Considering the CPU Utilization spiking to 100% and plus range would be an expected behavior within the increase of traffic at that time at the ALB. To eliminate this, I would recommend that you can increase the resource-requirements on the Task Definition "tbb-task-definition:19" to allow more buffer and help to smoothen the application-running

**Comment by sadatmalik** [comment]
https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=12975951491&language=en

**Comment by sadatmalik** [comment]
Task definition:
https://us-east-1.console.aws.amazon.com/ecs/v2/task-definitions/tbb-task-definition/19/json?region=us-east-1

**Comment by camerojo** [comment]
CPU was increased on 12 June
