### ISSUE TITLE
Mini Intake: English Assessment - intake screen changes only

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#707]
See: https://www.canva.com/design/DAFtz28cQHE/JZI_5copovFN8N1fE2lQYg/view

Implement intake screen only changes to English Assessment from the relevant slides.

**Comment by samschlicht** [comment]
- [x] Change title of panel to 'Language Assessment'
- [ ] Add auto-populated field showing Duolingo test score: **we don't have this data yet - have made #754 to action that request once we do.**

Adding French assessment
- [ ] English assessment field currently referred to as 'langAssessment' - needs changing to englishAssessment from front-end to DB
- [ ] DB will need coordinating with JC — I have to rename the lang_assessment and lang_assessment_score fields and this will break the code if my branch not ready and merged right away into staging.
- [ ] Add French and largely replicate English code — except I need to clarify whether in the same fashion we will have actual scores to privilege on this assessment, as we do with IELTS.

**Comment by samschlicht** [comment]
**Also just noting that this issue will also change the full intake (they both use the same Angular component and data).** I assume that's desired, but I'll have to change that accordion too, so it bears mentioning in case reviewer is confused.

**Comment by samschlicht** [comment]
This is an interesting one: TEF and TCF are both tests of French language ability admissible for immigration purposes (see [this useful article](https://canada2036.com/immigration/courses/tef-tcf/)).

They have different marking schemes but it appears both marks can be referenced by 'Canadian Language Benchmarks' grading system:

<img width="1380" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOURQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--761d2547ec31f0a5e9d8788ddd307bd56d411502/Screenshot%202024-03-12%20at%201.41.20%E2%80%AFpm.png" alt="Screenshot 2024-03-12 at 1.41.20 pm.png" />

<img width="1370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUhQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39373050a8efce8c2cbf266dacdcfd3afa6fa038/Screenshot%202024-03-12%20at%201.41.11%E2%80%AFpm.png" alt="Screenshot 2024-03-12 at 1.41.11 pm.png" />

The way our IELTS/English Assessment code works is we have fields on the DB for the intake english assessment and resulting IELTS score estimation. _Actual_ IELTS exams taken are recorded in the 'Language Exams' panel on Mini and Full Intakes. Finally there's an IELTS score column on the candidate table that's populated by a hierarchical-choice method using all the possible measures (IELTS gen -> IELTS academic -> intake assessment estimation). That field is what enables useful candidate searching by IELTS level.

My suggestion for replicating this for Canada is this:

- On the 'Language Assessment' panel we have a single field for estimated TEC/TCF score that uses the CLBs (the grading system they have in common).
- As part of this issue or subsequent to it, we add those qualifications to the 'Language Exams' panel dropdown and make a similar hierarchical choice method to populate a single candidate 'TEC/TCF' field for candidate searching by French ability.
- The question is, is the CLB measure sufficient? If it isn't, we'll need to separate the two qualifications to ensure we have the future options we need. I'll write to the CA team and see what they say.

**Comment by samschlicht** [comment]
[Here's my message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1710216420740979) to some of the CA team — I'll leave this in the In Progress lane and pick it back up when we have a response.

**Comment by samschlicht** [comment]
Got some useful input from Kat and Ayana on Slack. Pending any further input, we'll do this as follows:

Assessment Q:
Pouvez-vous me parler de vous et de votre métier? Quelle est votre plus grande réussite?

Estimate Q:
 Estimated French Canadian Language Benchmark (CLB) 
+ hover-over tooltip that gives some useful context re TEF and TCF tests to the intaker (perhaps linking the CA gov article, which should stay current)
+ dropdown options CLB 4, CLB 5, etc

**Comment by samschlicht** [comment]
After a bit of to-ing and fro-ing with Kat and Ayana, and my own reading, which actually shows that NCLCs are the French-language equivalent of CLBs, I've settled here, pending any further feedback:

<img width="1187" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzMwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca4d59cc80f87b1a3b4c1f8fcf37665714e2fdf6/Screenshot%202024-03-20%20at%208.59.34%E2%80%AFam.png" alt="Screenshot 2024-03-20 at 8.59.34 am.png" />

I'm saving FrenchAssessmentScore as a number, which seems more useful than replicating the IELTS field which saves a string. In the frontend I've made the input a bit more restrictive to the user, which should hopefully also feel more instructive. Also couldn't resist some nifty DOM manipulation for error display and correction.

**Comment by samschlicht** [comment]
These are the linked resources: 

- [A guide to grading the NCLC, to assist the intaker's estimate](https://www.language.ca/wp-content/uploads/2019/02/CLB_NCLC_Overview-of-Competencies.pdf)
- [A conversion chart from TEC and TCF scores to NCLCs](https://www.canada.ca/en/immigration-refugees-citizenship/corporate/publications-manuals/operational-bulletins-manuals/standard-requirements/language-requirements/test-equivalency-charts.html)

I've made it a clickable tooltip (an adapted button) both for accessibility reasons (keyboard focusable) and also so that the links can be used. They both open in new tabs.

**Comment by samschlicht** [comment]
I've made a new issue which I'll link to this one, to add support for Canadian French Language Exams in other places including visa checks and language exams. It's not necessary for completing this issue but will inevitably be requested in future.

**Comment by samschlicht** [comment]
This is ready for PR but I'm not going to submit it till tomorrow just before my 1-1 with John, as I can't update the Flyways without stopping anyone else from doing so (I'm making alterations to the DB so it would break the build).
