### ISSUE TITLE
Full Intake: Interest in International Recruitment - intake screen changes only

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#708]
See: https://www.canva.com/design/DAFtz28cQHE/JZI_5copovFN8N1fE2lQYg/view

Implement intake screen only changes to Interest in International Recruitment from the relevant slides.

**Comment by cazcam34** [comment]
A requested removal (without moving elsewhere), potential data loss. Unsure where this eligibility is captured beforehand? And the rural question is dependant on the job opportunity, I guess rural is a broad term and would be weighed up against the particular job opp and i guess without knowing the location, it's a vague question as how rural is rural...
Referenced in the issue #719

<img width="1939" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHk5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--860125418110c2576127b08b335a511310f55c64/Screen%20Shot%202024-03-07%20at%201.42.14%20pm.png" alt="Screen Shot 2024-03-07 at 1.42.14 pm.png" />

**Comment by cazcam34** [comment]
Check with Noura and Mariam for some more clarification on what do they mean here - when does the confirmation occur beforehand?

**Comment by cazcam34** [comment]
If no longer need rural question, to avoid loosing data we could transfer to a best suited 'Notes' question in the form of a set string "Candidate answered No to interest in rural areas."

**Comment by cazcam34** [comment]
Spoke with John decided to hold off getting in touch with source until we have a broader chat about data removal.
