### ISSUE TITLE
Full Intake: Dependents - intake screen changes only

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#709]
See: https://www.canva.com/design/DAFtz28cQHE/JZI_5copovFN8N1fE2lQYg/view

Implement intake screen only changes to Dependents from the relevant slides.

**Comment by cazcam34** [comment]
Removal of 'are they registered question' for dependants. What does ask at mobility stage mean? When would that data be captured? Referenced in #719

<img width="1486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVM5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59c13d978aea93628073e486b2c8cb6a1112edca/Screen%20Shot%202024-03-07%20at%201.54.00%20pm.png" alt="Screen Shot 2024-03-07 at 1.54.00 pm.png" />

**Comment by cazcam34** [comment]
Removal of some relation types - do we just stop those being selected in future but allow existing ones to be displayed? How will that work in a dropdown?

<img width="1788" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVc5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3462d3352940bdebb11b97ee192ed0d5694c7573/Screen%20Shot%202024-03-07%20at%201.56.32%20pm.png" alt="Screen Shot 2024-03-07 at 1.56.32 pm.png" />
