### ISSUE TITLE
Full Intake: Host Country Status - intake screen changes only

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#711]
See: https://www.canva.com/design/DAFtz28cQHE/JZI_5copovFN8N1fE2lQYg/view

Implement intake screen only changes to Host Country Status from the relevant slides.

**Comment by cazcam34** [comment]
Removal - Where specifically in your home country are you from. This isn't being moved anywhere else. Referenced in #719

<img width="1602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMSs5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e4c52f98a1c2a37396d870162b3cb5859dc6119/Screen%20Shot%202024-03-07%20at%203.14.45%20pm.png" alt="Screen Shot 2024-03-07 at 3.14.45 pm.png" />
