### ISSUE TITLE
Data fields requested for removal in the Intake Revisions epic + other clarifications

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#719]
We should not delete any data from the TC database as it is intrinsically extremely valuable. We should not remove any associated data capture fields from the intake screens as this will make our collected data stale.

Keep a note here of any data deletion requests so we can update the requester that the deletion will not be actioned.

**Comment by cazcam34** [comment]
See issue #708 - removal of whole Interest in International Recruitment section
See issue #709 - removal of 'are they registered' question in dependants card, and removal of relation types. What to do with existing relations of those types, they can be displayed but they can no longer be selected?
See issue #711 - removal of 'where specifically in your home country are you from?'

**Comment by samschlicht** [comment]
See issue #713 - p28 of slide deck, removal of 4 questions on Full Intake, Additional Eligibility
See issue #712 - p27 of slide deck, removal of 'What best describes your status not being registered?' 
See issue #710 - p24 of slide deck, removal of 'Have you studied, lived, or worked abroad for more than 90 days?'
See issue #705 - p14 of slide deck, removal of 'Date of Asylum' field

**Comment by sadatmalik** [comment]
On #704: Mini Intake: International Protection - new section

There are already some questions that address need for international protection:

- Full Intake > Host Country Status
<img width="1242" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDNXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a04d6acb94824ab531f7e72c91d5a82e3b50e971/Screenshot%202024-03-13%20at%204.44.18%E2%80%AFpm.png" alt="Screenshot 2024-03-13 at 4.44.18 pm.png" />

- Candidate Visa Checks — **NB:** on the Canadian version, the staff member is asked to decide whether they judge that the candidate is in need of international protection, _based on the candidate's answer at intake_, which is displayed; whereas on the the Australian version, the answer is _auto-populated by the candidate's answer at intake._
🇨🇦
<img width="723" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNURXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e11cba625f4c4e8d599e4a24c7fbee17e3c7b258/Screenshot%202024-03-13%20at%204.50.19%E2%80%AFpm.png" alt="Screenshot 2024-03-13 at 4.50.19 pm.png" />
🇦🇺
<img width="692" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUhXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79819642aaf9b501410ab8e81ae0aa2548b63a91/Screenshot%202024-03-13%20at%204.49.53%E2%80%AFpm.png" alt="Screenshot 2024-03-13 at 4.49.53 pm.png" />

Before making any changes to the intake Q on international protection, these both need to be kept in mind.

Q for Source: what is the value in changing the questions we already have, or in adding this new one?

Finally, on the 'Do you consider yourself currently a refugee or stateless person?' Q, On review with John, this seems a redundant questions as the candidate has already gone to the trouble of filling in their profile (with questions about UNHCR status, etc) and scheduling the intake call — so clearly they are going to answer yes?
