### ISSUE TITLE
Hovering over links in candidate portal's job tab should switch mouse to pointer

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#746]
Instead it's switching to the text caret. Should be a nice quick win

<img width="442" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm5KQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13b13daa9bdc10f3a540ab3cc921835f16e5c900/Screenshot%202024-03-11%20at%2010.17.57%E2%80%AFam.png" alt="Screenshot 2024-03-11 at 10.17.57 am.png" />

<img width="446" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnJKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf07e4b07325aa76f69d5f25ac6738c5232a2d8c/Screenshot%202024-03-11%20at%2010.17.30%E2%80%AFam.png" alt="Screenshot 2024-03-11 at 10.17.30 am.png" />

**Comment by cazcam34** [comment]
Could be a duplicate of #782?

**Comment by MuhannedNoman** [comment]
Tested and it is working, duplicate of #[782](https://github.com/Talent-Catalog/talentcatalog/issues/782).
