### ISSUE TITLE
Sorting by a DOB column in search results coming from an Elastic Search fails

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#757]
This error is displayed

RestStatusException{status=400} org.springframework.data.elasticsearch.RestStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]; nested exception is ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]

To make it happen, create any search on the TC - which uses Elastic search. Choose to display DOB as a column. Click on the column header.

**Comment by sadatmalik** [comment]
Checking the field type for dob in the ES index mappings - it is defined as a date type with the format basic_date:

```
        "dob" : {
          "type" : "date",
          "format" : "basic_date"
        }
```

It seems the issue with sorting on dob may be arising from the attempt to sort using a .keyword suffix (dob.keyword):

`Page request [number: 0, size 20, sort: dob.keyword: ASC,masterId: DESC]`

ES date fields are sorted directly by their field name without the .keyword suffix - try adjusting the sort query to reference dob directly, without .keyword.

**Comment by sadatmalik** [comment]
Yes - this fixed it. Simply add dob to the nonKeywordFields. See PR for details.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDdZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec5b9d2b6e4c6c1fcd7ceee7dba612a5f2ff98b0/Screenshot%202024-03-13%20at%2012.32.43.png" alt="Screenshot 2024-03-13 at 12.32.43.png" />

**Comment by sadatmalik** [comment]
Checked + confirm that sorts on all other fields work fine.
