### ISSUE TITLE
Display summary data on intake accordion panels (Louna's suggestion)

### ISSUE THREAD

**Issue by cazcam34** [talentbeyondboundaries/tbbtalentv2#764]
More details to be added (John's notes) but on our call with Louna about the TC, she identified a problem when having to dig for the same data in intakes. One example is dependants, how many there are and their ages. We thought a solution would be use the empty space in the accordion panels to display some data summaries (e.g. On dependants panel show: **4, 10, 48** to indicate quickly how many dependants there are and their ages).

Some other examples were provided in the call and listed in John's notes to be added.

**Comment by cazcam34** [comment]
Provide screenshot for release notes

**Comment by sadatmalik** [comment]
This went out last week with the mini-release with the performance updates. However, I think it's still worth having screenshots for the formal release notes. What do you think @cazcam34?

**Comment by cazcam34** [comment]
Apologies @sadatmalik I didn't realise that this went out in the 2.2.1 release. So there isn't anything in the release notes about this change. Should I add something in the 2.2.1 release notes, or wait for the release notes for the upcoming release?
