### ISSUE TITLE
Add ngx translate to admin portal

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#770]
Currently only candidate portal uses ngx translate - where keys are used for displayed text instead of hard coded text. This enables switching between different languages. 

We should add support for it to admin portal so that we can share identical code across both portals. In the admi portal the language will always be English, but it means that we can share common code which uses keys - which is currently not possible - because one portal has support for keys and the other doesn't.

**Comment by samschlicht** [comment]
#645 ?

**Comment by samschlicht** [comment]
Moving ahead as #645
