### ISSUE TITLE
SPIKE: Port opportunity related Slack workflows (such as intake request) across to JobChats

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#791]
Slack workflows related to managing opportunities naturally become posts on JobChats associated with the relevant opportunity/candidate.

They can be automatically triggered by stage changes

**Comment by samschlicht** [comment]
@camerojo I actually don't have access to any of these Slack workflows. No rush (I'll pick up another issue for now), but would you mind inviting me to collaborate on them? Or pointing me to someone who might be able to?

**Comment by camerojo** [comment]
Can you find out who created them? I thought it was you. Maybe Saleem?

**Comment by samschlicht** [comment]
Ah I thought there was more to it than just the one — Naji made the intake request form and I have access to it now. I can't see any others. Thanks, @camerojo!

**Comment by samschlicht** [comment]
<img width="586" alt="Screenshot 2024-04-11 at 10 36 34 AM" src="https://github.com/Talent-Catalog/talentcatalog/assets/111261894/b1b460d6-e9c3-47d4-8fe6-33b9595bfb59">

**Comment by samschlicht** [comment]
I've written to Naji for his input. Nice opportunity to get a star user involved here.

Hey Naji, we’re going to put something like your intake request form into the TC code! We’re thinking it will trigger a Job Chat post to the relevant source partner. Just wondering if you have any suggestions for how it would look/behave in the UI?

I’d note that less fields will need to be filled in, because the TC already has the destination, employer, job title and submission list — they might not even need to be in the message that gets sent (because it’s accessible elsewhere on the job menu they’ll be viewing) — but again, you might have some thoughts about that.

No rush, obviously, just getting the ball rolling for now.

**Comment by samschlicht** [comment]
From Naji:
 Hi @Sam Schlicht
mmm not sure how it might look like, but looking at the form now, all the information is in TC so it is only for notifying Source or Partners.

I think it would be beneficial if we can do some sort of notification that could also help the people doing the intake to track what is happening and when is the due date.

So for example, we can have a page where you can see how many people you need to do the intake for.
Also when is the deadline for each candidate. You can see it per job or per candidate.

Also if we can let people assign the intake to each other. For example if I notify Source that this job has a list of candidates to intake. Then Source leads will look at it and assign each candidate to certain team member. Then each team member can get a notification.

Not sure if I explained it well or not, but I am happy to chat more about it and will give it a think as well!

 One of the issues, is that the Source team do not operate as a call centre where we can send tasks out to be done and they will have tickets system to assign.
What I would love to see is that this system will work as ticketing system to notify them and let them assign the task for the team.
Also it would be great to track how long things are taking by getting a default turnaround deadline.

**Comment by samschlicht** [comment]
From me:
Interesting. Leaving the bigger question aside for a moment, are you finding that the workflow is useful? Would it be helpful as a standalone measure to have it on the TC, where it can reach partners who won’t necessarily be on Slack, going forward?
To the bigger question, your explanation makes total sense but not something we can effect through the software alone — i.e. Noura’s team and our partners would have to sign on to a different way of working, and only then would we provide the proper TC functionality. I’ll definitely bring this to the team, though: everything about the way we do intakes and what they are is up for conversation, and these are great ideas. I’ve added these messages to the intake issue on our dev team project board — hope that’s okay. We’ll definitely discuss further.

**Comment by samschlicht** [comment]
I think Naji has the germ of a great idea here, but this is far from implementation stage for now.

I'm going to bring this to discussion with team:

_What do we think about adding a way for destination to request individual or group candidate intakes, for example with a 'Request Intake' button on the candidate profile and/or a 'Request Intake' button on the list view screen?_

_This could automate a chat post, but we might want something less ephemeral to go with it — e.g. as Naji suggests, a source team intake console, where requests can be prioritised, marked done/in progress, etc._

I think this would require broader consultation and perhaps move forward as a new issue in the next release cycle, but first I just want to take the team's temperature.

**Comment by samschlicht** [comment]
Closing this and it'll move ahead as #1079.
