### ISSUE TITLE
BUG (Staging and Local only): 'Other languages' in elasticsearch produces error

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#793]
<img width="1365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62ee45af438ca0a4811582db9aeabcadb8005a88/Screenshot%202024-03-26%20at%204.21.52%E2%80%AFpm.png" alt="Screenshot 2024-03-26 at 4.21.52 pm.png" />

**Comment by samschlicht** [comment]
Found this one while working on adding remaining excluded filters to elasticsearch

**Comment by samschlicht** [comment]
From the logs:
<img width="1504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42635d27cd33533b531ee4d51272b9a8f8a448bd/Screenshot%202024-03-26%20at%204.32.02%E2%80%AFpm.png" alt="Screenshot 2024-03-26 at 4.32.02 pm.png" />

**Comment by samschlicht** [comment]
Interestingly, it's working in prod, where 'Other languages' _is_ a nested object (it's not on my local ES index or staging's) - is this something we need to do elsewhere other than just our code?
Prod:
<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf67f5c25b43315fe41683a18af9318f7cb8e0d5/Screenshot%202024-03-26%20at%204.39.45%E2%80%AFpm.png" alt="Screenshot 2024-03-26 at 4.39.45 pm.png" />

Staging:
<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1MQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8f79e1def14533ff9d4271dd6621f736db67385/Screenshot%202024-03-26%20at%204.42.55%E2%80%AFpm.png" alt="Screenshot 2024-03-26 at 4.42.55 pm.png" />

**Comment by samschlicht** [comment]
I don't really understand because it certainly appears to be nested in the index mapping, as pictured. Will have a closer look tomorrow.

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUVNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ee48741b24bf355102bcac3dd811eaca487c138/Screenshot%202024-03-26%20at%206.14.59%E2%80%AFpm.png" alt="Screenshot 2024-03-26 at 6.14.59 pm.png" />

**Comment by samschlicht** [comment]
Perhaps this has to do with elasticsearch version?

- 7.17.11 running in local
- 7.17.11 running in staging
- Nope, 7.17.11 in prod too!

**Comment by samschlicht** [comment]
Ah, the prod mapping has a 'type: nested' annotation for otherLanguages. I'll need to find out how that's imputed there and not in staging or local ES.

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBellNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0450b55e2821b29df01cc98f397b464b311cb1cd/Screenshot%202024-03-26%20at%206.32.30%E2%80%AFpm.png" alt="Screenshot 2024-03-26 at 6.32.30 pm.png" />

**Comment by samschlicht** [comment]
Might be this small difference in settings?

Staging and local:
<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0148488e50aad3d2d48e9f1af2c84284207ef98d/Screenshot%202024-03-26%20at%207.03.01%E2%80%AFpm.png" alt="Screenshot 2024-03-26 at 7.03.01 pm.png" />

Prod:
<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUFNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f461cd91da2dd75306fbd8388bb6936944783f1d/Screenshot%202024-03-26%20at%207.03.58%E2%80%AFpm.png" alt="Screenshot 2024-03-26 at 7.03.58 pm.png" />

**Comment by samschlicht** [comment]
Hmm, nope, ES doc advises never to set or remove the block in question yourself: `"index.blocks.read_only_allow_delete": "false",`

**Comment by samschlicht** [comment]
research document annotation and when it can be overridden

**Comment by samschlicht** [comment]
- [x] We could undo the dob change and see if that makes a difference - DONE, NO DIFFERENCE

- [x] In the meantime, disable Other Languages for elastic (put in a one-line PR just to do this as a safety measure)

**Comment by samschlicht** [comment]
Sam to update Sadat at the end of his day Wednesday

**Comment by samschlicht** [comment]
Removing and then running elastisearch again fixed the problem on my local server, irrespective of whether the 'dob' bug fix is included in the code.
<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXdTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5bf6e5d0b71e8bf2795d20b4443befdbb3ec8ae/Screenshot%202024-03-27%20at%208.56.55%E2%80%AFam.png" alt="Screenshot 2024-03-27 at 8.56.55 am.png" />

**Comment by samschlicht** [comment]
This could be an issue caused by dynamic mapping (which we have enabled), though I haven't quite found the silver bullet description that covers our issue. Sadat's Q re whether dynamic mapping might override the explicit mapping provided by CandidateEs and its @Document annotation is key, but I can't find a source to say that it would.

The question is, why would he have it turned on, when we're defining our mapping explicitly and always submitting the same document that conforms to it? For safety's sake, it might make sense to turn it off anyway. But I'd obviously like to know that that will take care of this bug.

[This article](https://opster.com/guides/elasticsearch/data-architecture/elasticsearch-dynamic-mapping/) just generally advises the benefits of explicit mapping — key para:

> 1. Use explicit mappings: While dynamic mapping is convenient, it’s always a good idea to define explicit mappings for fields that are known in advance. This ensures that the fields are mapped correctly and helps avoid potential issues with data type conflicts.

And from the [ES doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/explicit-mapping.html):

> You know more about your data than Elasticsearch can guess, so while dynamic mapping can be useful to get started, at some point you will want to specify your own explicit mappings.

**Comment by samschlicht** [comment]
I'm also noticing that the [type hints](https://docs.spring.io/spring-data/elasticsearch/docs/4.3.0-M1/reference/html/#elasticsearch.mapping.meta-model.rules) embedded in the staging and prod mappings are different.

**STAGING**
<img width="259" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnNTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a73200100c6647d2f26e399b8495580e7e7ef5f5/Screenshot%202024-03-27%20at%2012.12.14%E2%80%AFpm.png" alt="Screenshot 2024-03-27 at 12.12.14 pm.png" />

**PROD**
<img width="244" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNndTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59ad16ec55f6e1ad1fefe293d3d0968e7f3f5ef2/Screenshot%202024-03-27%20at%2012.13.17%E2%80%AFpm.png" alt="Screenshot 2024-03-27 at 12.13.17 pm.png" />

This one (in otherLanguages specifically) is not in staging at all:
<img width="203" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjRTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bed9c4902708fd2c0ccbb76a47055662309d52c2/Screenshot%202024-03-27%20at%2012.14.15%E2%80%AFpm.png" alt="Screenshot 2024-03-27 at 12.14.15 pm.png" />

**Comment by samschlicht** [comment]
A quick summary of where I'm up to:

**I've submitted [a one-line PR](https://github.com/Talent-Catalog/talentcatalog/pull/795) that disables the Other Languages filter when Keyword Search is populated.** That's the standard technique we use when fields and filters are unavailable for ES. It's not ideal, but it will stop people hitting the bug.

**Diff between prod vs staging and local candidates index mapping**

- [Type hints](https://docs.spring.io/spring-data/elasticsearch/docs/4.3.0-M1/reference/html/#elasticsearch.mapping.meta-model.rules) included in prod either not included or slightly different in staging and local indexes (see above comment for details).
- `type: nested` annotation not on otherLanguages field in staging and local indexes.
- On closer inspection, index settings in slightly different order but no material difference that I can see.

**Findings**

- On my local system, removing and then re-running elasticsearch and then rebooting Spring produced the same index mapping as prod and the bug no longer happens.
- This is true with or without Sadat's DOB-fix branch change, suggesting it played no part in producing the variation in indexing and subsequent bug. (That was the only code diff between staging and master that I would expect to have any effect on ES.)
- Populating the index did not change its mapping, which calls into question that this would be anything to do with our dynamic mapping setting.
- Furthermore, I can find no source suggesting that dynamic mapping would affect fields which we are explicitly mapping.
- That being said, we're not using dynamic mapping, so we could turn it off for safety's sake. I haven't reviewed the effect closely, but same goes for type hints. Here's how:

<img width="700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2tUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b37c34074a52fc7a0f4ac43e49974d81077a1c9/Screenshot%202024-03-27%20at%203.16.52%E2%80%AFpm.png" alt="Screenshot 2024-03-27 at 3.16.52 pm.png" />

- I restarted ES staging, redeployed TC-Test and re-indexed candidates, but that also didn't change the mapping. It also blew out CPU at around 17495 docs and stopped indexing. 
- I had noticed previously that there were only roughly 40,000 docs in staging vs 294,000 in prod, despite the DBs not being that far removed. I'm wondering if the same happened last time it was re-indexed?
- So my working hypothesis is that issues during re-indexing are causing the faulty mapping. Could be performance-related — we don't have the same capacity in terms of TC tasks and elasticsearch instances, perhaps it's struggling with the new expanded DB dump — but I would note that the faulty mapping started from the first document.

I'm out of time for today but my next step tomorrow (if Sadat hasn't worked on this already) would be to review the TC Test AWS logs (at the time of the re-indexing) and task definition JSON thoroughly for any issue that might be particular to the staging setup.

**Comment by camerojo** [comment]
So are these the current conclusions?

- Sadat's DOB fix branch change is not the problem - so activating the one-line PR to pull that change out is not likely to have any effect
- Prod is OK now - and probably will remain OK after the release.
 
Ultimate conclusion: do nothing. The release will probably not break prod's Elasticsearch. It should all just work.

Does that sound where we are right now?
@samschlicht

**Comment by samschlicht** [comment]
Thanks, @camerojo: that would be my 80% confident conclusion — I suspect the other 20% is mostly humility owing to my relatively new exposure to this part of the TC. If it looks reasonable to you, that helps.

**Comment by camerojo** [comment]
After 50 years coding, I still never get above 80%! But that's what it looks like to me too. Fingers crossed. I think you are right - Elasticsearch reindexes on your dev and staging were both interrupted leaving a corrupted ES. Production is good and should stay that way.

But going forward we do want a working ES on staging. But we can fix that after the release hopefully.
fyi @sadatmalik

**Comment by sadatmalik** [comment]
Just verified this in my local environment, works fine and I don't see the error locally. My local index mapping reflects what we have in production. Confirms your thinking Sam that this may have been introduced somehow to your local environment. It would be interesting to take stock of what your steps were prior to first seeing the issue.

I have a theory what may have caused it in staging, noted further below.

But first, in the staging environment, I've performed the following steps to address the issue:

1. Stopped the AWS service.
2. Deleted the existing ES index.
3. Restarted the AWS service.

This guarantees the initial index mapping is generated based on the document annotations in ESCandidate. Subsequently, I initiated an esload operation, to begin populating the index. It's moving along - let's keep an eye on it.

I've double checked the OtherLanguages index mapping in staging, and it now appears to be correct:

<img width="555" alt="Screenshot 2024-03-27 at 11 22 51" src="https://github.com/Talent-Catalog/talentcatalog/assets/87991701/7c008b99-efde-44b2-bde7-6bfa5df66de3">

On dynamic mappings, just noting that once a field is added to an index mapping, it remains unchanged. The mapping used to insert a document into the index must be consistent with the mapping used to retrieve a document later on. Dynamic mapping is only invoked for new, unmapped fields, where Elasticsearch applies its dynamic mapping rules when it encounters a field not already in the index mapping.

A possible explanation for the issue could involve the sequence of operations on the ES index and the Spring service:

- If the Spring service continues running,
- The ES index is deleted,
- And an esload is performed without first stopping and restarting the Spring service,

the initial index mapping is not built from the ESCandidate annotations but instead is constructed dynamically as data is loaded. If the first loaded candidate lacks nested OtherLanguage fields, this could lead to the dynamic creation of a non-nested OtherLanguage field in the index, which would then persist across subsequent esload operations.

**Comment by samschlicht** [comment]
That definitely makes sense to me, @sadatmalik. So we need to be very mindful of the sequence in prod _and_ staging when we make changes to EsCandidate — basically always to stop the service, delete the index, restart the service, check the mapping, and only then esload.

The mapping has remained accurate on ES staging. The re-indexing is still going, 12 hours later, and not even halfway by my reckoning — luckily we're not too reliant on TC Test but we may want to look at the performance of the re-indexing method and perhaps considering adding an extra AWS task and/or ES instance. TC Test is not really usable at the moment and that may be the case for 24 hours or more. Another consideration is reducing the DB size.

**Comment by samschlicht** [comment]
I would add that that's almost certainly what caused the bug on my local system — I wasn't aware, until exploring this bug, that the mapping is done when Spring is booted up.

I hadn't re-indexed or in any other way interacted with staging's ES setup, prior to discovering the bug on there — but it seems plausible that someone made a similar process error in the past. 

Perhaps we should add to the readme (I assume that's the right place, or perhaps the Tettra doc) a short process guide for redeployment following any changes to elasticsearch?

**Comment by sadatmalik** [comment]
Following the deployment to AWS production yesterday, it has been verified that the ES production mappings have remained consistent.

Recalling the initial creation of the Staging ES index, we did that in part to facilitate testing of changes aimed at keeping all search fields active during keyword searches, including the nested "other languages" field. To confirm the index mapping was correctly applied, it was tested and confirmed via Kibana using the query copied below. It appears that subsequently, the index may have been unintentionally deleted and recreated.

Ticket #809 has been opened to outline the necessary steps for rebuilding the index, if required. It's important to approach the deletion and rebuilding of ES indexes in both staging and production environments with caution, as these processes are time-intensive. This caution is underscored by the recent need to initiate a rebuild in staging during this investigation.

Ticket #842 has been opened to diagnose the slow ES index building process. 

```
# search with nested other languages successfully ran from Kibana in Staging when the Index was initially created
GET /candidates/_search
{
  "query": {
    "bool" : {
      "must" : [
        {
          "simple_query_string" : {
            "query" : "lebanon",
            "flags" : -1,
            "default_operator" : "or",
            "analyze_wildcard" : false,
            "auto_generate_synonyms_phrase_query" : true,
            "fuzzy_prefix_length" : 0,
            "fuzzy_max_expansions" : 50,
            "fuzzy_transpositions" : true,
            "boost" : 1.0
          }
        }
      ],
      "filter" : [
        {
          "range" : {
            "minEnglishSpokenLevel" : {
              "from" : 1,
              "to" : null,
              "include_lower" : true,
              "include_upper" : true,
              "boost" : 1.0
            }
          }
        },
        {
          "range" : {
            "minEnglishWrittenLevel" : {
              "from" : 2,
              "to" : null,
              "include_lower" : true,
              "include_upper" : true,
              "boost" : 1.0
            }
          }
        },
        {
          "simple_query_string" : {
            "query" : "lebanon",
            "flags" : -1,
            "default_operator" : "or",
            "analyze_wildcard" : false,
            "auto_generate_synonyms_phrase_query" : true,
            "fuzzy_prefix_length" : 0,
            "fuzzy_max_expansions" : 50,
            "fuzzy_transpositions" : true,
            "boost" : 1.0
          }
        },
        {
          "terms" : {
            "partner.keyword" : [
              "TBB",
              "HIAS",
              "IOM",
              "RP",
              "Dignity",
              "AT",
              "CRS"
            ],
            "boost" : 1.0
          }
        },
        {
          "terms" : {
            "status.keyword" : [
              "active",
              "incomplete",
              "pending",
              "unreachable"
            ],
            "boost" : 1.0
          }
        },
        {
          "term" : {
            "gender" : {
              "value" : "male",
              "boost" : 1.0
            }
          }
        },
        {
          "nested": {
            "path": "otherLanguages",
            "query": {
              "bool": {
                "must": [
                  {
                    "match": {
                      "otherLanguages.name.keyword": "Arabic"
                    }
                  },
                  {
                    "range": {
                      "otherLanguages.minSpokenLevel": {
                        "gte": 3
                      }
                    }
                  },
                                  {
                    "range": {
                      "otherLanguages.minWrittenLevel": {
                        "gte": 3
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ],
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  }
}
```
