### ISSUE TITLE
Naji does not see the intake and additional info tabs

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#81]

**Comment by sadatmalik** [comment]
From Naji -

"In any list, when I click on the candidate name in the review column on the right side of the screen, is it possible to review the whole profile? This will help us review the intake information as well as reviewing the CV since some candidates do not have their experience tab filled. Both intake and additional information tabs are not showing at the moment."

**Comment by cazcam34** [comment]
Created a new issue for this, as it is related to a broader UI improvement issue. See here #138. @sadatmalik - what should I do with this issue now I've addressed it with another issue? Or should i have just amended this existing one?

**Comment by cazcam34** [comment]
I replied to Naji's original post here: https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1686278441317699

**Comment by sadatmalik** [comment]
Hi @cazcam34 - just picking up on your query above. If you've addressed it another issue then if you pop a comment in with a reference to the other issue then go ahead and close this one as a duplicate.
