### ISSUE TITLE
Possible bug: error message in candidate portal Jobs tab - can't access chats

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#815]
I haven't looked into this one yet, just logging for now. I've tried a number of ways to create a new candidate, add them to a job and follow the links, but I get these errors and the job links aren't clickable:
<img width="700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3NtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebfeb0c67ddc719677bc323dc36e3a4fe61355b6/Screenshot%202024-04-02%20at%2010.00.50%E2%80%AFam.png" alt="Screenshot 2024-04-02 at 10.00.50 am.png" />

**Comment by samschlicht** [comment]
I'm getting the same error in preview:

<img width="1922" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2duQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--049d9c84798b561b1d2d99ad730e6a13fd7bdb88/Screenshot%202024-04-02%20at%2010.10.44%E2%80%AFam.png" alt="Screenshot 2024-04-02 at 10.10.44 am.png" />

**Comment by camerojo** [comment]
@samschlicht This is the fall out from an old bug which will have corrupted your dev database. The bug was that it was possible for multiple chats of the the same type and associated with the sam opp to be created - when there should only be one.

The easiest way to clean this up is to delete all chats from your test DB.

**Comment by samschlicht** [comment]
Phew! I had a feeling we'd discussed this before, hence the 'possible'. 

Thanks, @camerojo!

**Comment by samschlicht** [comment]
I'll close this to save any alarm.
