### ISSUE TITLE
Selected Shareable Attachments display issues

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#83]
From Naji -

- [ ] Selected Shareable Attachments - CVs selection bar is looking empty (with an x next to the arrow) but the CV is actually connected but not showing the name in the bar. [Caroline]
- [ ] Selected Shareable Attachments - When I upload a CV, sometimes I need to refresh the page few times before it appears in the dropdown list. [Caroline]

**Comment by sadatmalik** [comment]
From Naji -

- [ ] Selected Shareable Attachments - CVs selection bar is looking empty (with an x next to the arrow) but the CV is actually connected but not showing the name in the bar. [Caroline]

- [ ] Selected Shareable Attachments - When I upload a CV, sometimes I need to refresh the page few times before it appears in the dropdown list. [Caroline]

**Comment by cazcam34** [comment]
Hard to replicate the bugs - I think I have been able to address the second one, and I asked Naji to provide a screenshot/candidate number for the first bug.

**Comment by cazcam34** [comment]
Example of candidate: https://tctalent.org/admin-portal/candidate/115739

https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1695259370327579?thread_ts=1686278441.317699&cid=C42S4AJ73

**Comment by cazcam34** [comment]
Can't replicate bug. Tried logging is as a same role as Naji (source partner admin) but still appears. The HTTP requests is also returning the name, so likely a front end issue perhaps around load time? Chased up with Naji for more information to gage urgency.

**Comment by cazcam34** [comment]
Not an urgent bug and Naji will keep track of when/who it happens to. Here is his reply: 
https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1695297173375309?thread_ts=1686278441.317699&cid=C42S4AJ73

It is very random to be honest 
@Caroline Cameron
, every now and then it happens but can’t tell if there is a trend with certain candidates or for certain opportunities/lists.
It doesn’t bother me much except the fact that I don’t know which document/CV is linked to their profile in case there is more than one in their profile and we need to add the newest one sometimes.
I will keep a record from now on for the candidates profiles that has this issue to see if there is any certain thing that is causing it. Thanks for your help.

**Comment by cazcam34** [comment]
Seen the issue with this candidate: https://tctalent.org/admin-portal/candidate/144867 
Something to do with shareable docs?

**Comment by cazcam34** [comment]
I moved this into the product backlog as it's a draft PR, which needs a bit more time to look into as it's a difficult bug to replicate. Feel free to move again.
