### ISSUE TITLE
Spike: Investigate why building ES index is slow

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#842]

**Comment by samschlicht** [comment]
It looks like making new deployment devoted to logging and monitoring would give us a bit more insight ([ES doc](https://www.elastic.co/guide/en/cloud/current/ec-enable-logging-and-monitoring.html)).

I've also checked out a branch to see where most of the time is spent in the indexing method,

**Comment by samschlicht** [comment]
Based on findings in #860, `EntityManager.clear()` may help with processing here, although on my local system most of the CPU load is from Docker (i.e. it's elasticsearch). 

What I've done for now is added EntityManager but commented it out, along with some duration logging that will help with measuring effect. I'd like to run the indexing in staging without it, then try again with it. I'll also keep an eye on the ES staging cluster's [monitoring](https://cloud.elastic.co/deployments/b48a0505dc2345e0a40158b57c85e89c/metrics). I probably don't even need to index the whole lot — I could do enough to get a decent measurement, then do the whole lot once we've decided on an approach.

However, with the new mappings and Python scripts, along with the disruption to staging, I'll need to discuss and coordinate this w the team.

**Comment by samschlicht** [comment]
Results on staging:
(There was a slight creep up from 14-15 secs per 100 candidates at the beginning, to 15-16 candidates by the end. Still a vast improvement, I would say — maybe just some tuning to be done, but serviceable for now.)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDlFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da380bc775d7b77a30514813bf027b3e7b408f39/Screenshot%202024-06-06%20at%209.26.40%E2%80%AFPM.png" alt="Screenshot 2024-06-06 at 9.26.40 PM.png" />


<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXRFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f04fca2d0322fae03b9c9792479631de8ece2df5/Screenshot%202024-06-06%20at%209.34.47%E2%80%AFPM.png" alt="Screenshot 2024-06-06 at 9.34.47 PM.png" />
