### ISSUE TITLE
ID, Email/Phone, Name/Number search slowness

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#847]
Reported by Hanine:

There is a delay of up to a minute before a result is displayed when I input an email or name for searching.

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1712335637663359?thread_ts=1712335637.663359&cid=C42S4AJ73)

**Comment by camerojo** [comment]
I am seeing this too (although less than a minute).

I believe that those little search fields are used a lot by users - so worth keeping them fast.

I think it is just getting slower with the number of candidates/users.

We are missing some indexes to keep this fast. The SQL code that executes the searches is in CandidateRepository. 
For example, I think we need indices on Users firstname and lastname and email and phone and Candidate lowercase number (maybe can replace existing index without lower case - note that Candidate number is text not number - tech debt. Maybe we just remove the unnecessary lowercase function from candidate number searches). Also externalId, country. Probably some others.
