### ISSUE TITLE
Spike - Review AWS database set up - look at Provisioned storage model - recommended for production

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#85]
See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html

**Comment by sadatmalik** [comment]
Production:

<img width="1429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUhWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--364e7c4f893304573c4b33a4c3af7fe560651909/Production%20DB%20Storage%20Type.png" alt="Production DB Storage Type.png" />


Staging:

<img width="1436" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVBWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--720d9997ea3199f8b0ba45567f8ea9966695c7b7/Staging%20DB%20Storage%20Type.png" alt="Staging DB Storage Type.png" />

**Comment by sadatmalik** [comment]
Modify Storage Type in DB Configuration:

<img width="1335" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTdWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce5d31de98fa290dd9b8be1e555f26bfee69ec8f/Modify%20Storage%20Type.png" alt="Modify Storage Type.png" />
