### ISSUE TITLE
Add support for new train-to-hire SF stages

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#867]

**Comment by samschlicht** [comment]
Requested by EU lead Daniele and approved by John.

‘Training’ stage added as follows:
Candidate opportunity: between ‘Acceptance’ and ‘Visa preparation’
Employer opportunity: between ‘Job offer’ and ‘Visa preparation’

I've requested a deadline for this — it's a minimal amount of code and could possibly need to be a hot fix.

 - [ ] Add stages to TC (needs to be a hot fix)
 - [ ] Add stages to SF
 - [ ] Tettra doc
 - [ ] Does it need a new closed stage?

**Comment by samschlicht** [comment]
Update: ideally this would be implemented by 11 June, when Daniele expects the first cohort (in Italy) to start training. For that reason, per John's suggestion, I've put it in the sprint backlog for prompt discussion.

**Comment by samschlicht** [comment]
This is a very quick one but ideally would be a hot fix - will discuss w @sadatmalik.

**Comment by camerojo** [comment]
Sorry we missed the deadline on this one. 

Let's touch base when I am back in Australia next week - and get this done.

I think it probably does need a new closing stage - along the lines of "Did not successfully complete training".
@samschlicht

**Comment by samschlicht** [comment]
@camerojo no worries and yep, agreed on the closing stage and getting it done as a hot fix.

Sarah Walder has also requested a new 'MOU' stage on employer opps (it may also benefit from a closed stage), so perhaps we can combine them. #1171

**Comment by camerojo** [comment]
Video for people to add new stage

**Comment by samschlicht** [comment]
This is ready for pushing to master w JC tomorrow

**Comment by samschlicht** [comment]
Just a note that I've made Tettra doc for this process [here](https://app.tettra.co/teams/talentbeyondboundaries/pages/recurring-tc-processes#header-8qjuo-changing-opportunity-stages)

**Comment by samschlicht** [comment]
Just a note that we had to make some small edits in an additional hotfix. I can't link the PR for some reason - [here it is](https://github.com/Talent-Catalog/talentcatalog/pull/1199).
