### ISSUE TITLE
Potential null pointer exception in SF Service

### ISSUE THREAD

**Issue by samschlicht** [talentbeyondboundaries/tbbtalentv2#878]
Found this while working on #860. I had to fix it to carry on testing my branch for that issue, so, depending what happens with that one, the PR may resolve this issue.

I think nationality is a mandatory field now but there are two null values for this field in the prod DB (and there were a few on my local DB), so we should have the null check.

SalesforceServiceImpl.java:1396

Here's the fix:
`final Country countryOfNationality = candidate.getNationality();
            if (countryOfNationality != null) {
                setNationality(countryOfNationality.getName());
            }`

**Comment by cazcam34** [comment]
Looking into this it appears the fix was merged into staging by Sam in PR #879
