### ISSUE TITLE
Get support for ReadOnly users working - New job contact type for Employer Access: "Hiring manager"

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#913]
As a hiring manager at an employer
I would like to be able to monitor the progress of a job that we are advertising
so that I know what kind of candidates are available and so that I can give feedback and prepare for my interview with promising candidates.

Suggestion from @ajt001 

Hiring manager should be able to view jobs relevant to them under myJobs

Note that this is specific to direct Employer access. With indirect access such as through TBB or Recruiter portal, we normally will not have direct contact with hiring managers.

**Comment by cazcam34** [comment]
@camerojo - a bit unsure what this relates to.
Is it a new contact (e.g. Destination contact) for a job where a user can be assigned as a hiring manager for a job? (See screenshot below)
<img width="976" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c1fc4b90a4b730ade206a6627458c1ef378a816/Screen%20Shot%202024-06-03%20at%2012.23.09%20pm.png" alt="Screen Shot 2024-06-03 at 12.23.09 pm.png" />

**Comment by camerojo** [comment]
This is really a new user type. A user that can't do much but can view opportunities.

**Comment by cazcam34** [comment]
Sort of like a 'read only' employer?

**Comment by camerojo** [comment]
> Sort of like a 'read only' employer?

Yes - exactly.

**Comment by camerojo** [comment]
### To do

- [x] Allow partner admins to create other partner admins for their own partner (Hiring manager will be a partner admin)
- [x] Get ReadOnly working - monitors will have read only access
- [x] Read only can only add to or modify lists that they own.
- [x] Read only can only add to or modify searches that they own.
- [x] Copy list not selecting correct lists
- [x] When a candidate summary is selected, display of candidate info crashes read only
- [x] Look at use of SelectListComponent - when does ReadOnly need to specify my lists only?
- [x] Read only can see posts but cannot post or react.

### Issues

- [x] Read only should not be able to change job summary unless it is his job
- [x] Evergreen job is not updating (merged #1220)
- [x] Possible for two jobs to share a single intake - in test db. Should not happen. - eg select * from jobOpp where jobOppIntake = 2 returns two jobs. Looks like this is fixed intakes are now copied - see code in JobServiceImpl.copyJobFields
