### ISSUE TITLE
New job should be able to be created from a previous job - acting as a job "template".

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#914]
As a job creator
I should be able to create one job from another job
so that I can impose some consistency in the way that jobs are created.

Suggestion from @ajt001 
According to Andrew Todd, Iress had standard job templates. This copy capability allows users to set up previous jobs as templates.

The new job will be a copy of the original job. The user can then modify the details of the new job as appropriate.

Although this is attached to the Employer  Access epic, this capability should be useful for all job creators.

**Comment by camerojo** [comment]
Has fairly common functionality with the Evergreen job support which involves copying jobs.

**Comment by cazcam34** [comment]
@camerojo what exactly is to be copied in this feature? What I assume so far is:
- Job Uploads
- JOI
- Job Summary
- Some job information like country

Obviously people can only copy from jobs that are part of their partner, as we don't want them to be able to copy jobs from other partners which will give them access to other partners job information/uploads. Also we wouldn't want to copy employer/recruiter/contact as that should be populated depending on the job creator. Is that correct?

What about the name? The job should have a unique name, not the same name as the copied job?

**Comment by cazcam34** [comment]
@camerojo This is what I am thinking so far... Once a job name is entered, you have the option to create a new blank job or copy an existing job. 
<img width="1942" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2RLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82a8068383f17b08756503fcf6d3643783376391/Screen%20Shot%202024-06-10%20at%2011.54.03%20am.png" alt="Screen Shot 2024-06-10 at 11.54.03 am.png" />

I've then created a new modal which allows a selection of a job to copy from... but those jobs are only those that belong to the job creator's partner. Upon selection of the job to copy from, that id is passed up in the request and then used to fetch and copy the specific "copy" attributes.
<img width="1498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHRXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c036a7862a829cb24034fd135c1d23eb6fd4a58d/Screen%20Shot%202024-06-12%20at%2011.25.29%20am.png" alt="Screen Shot 2024-06-12 at 11.25.29 am.png" />
