### ISSUE TITLE
Tool tip for Fixed checkbox on Update Existing Candidate List

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#917]
From Saleem:

Here is the screenshot for the "Fixed?" checkbox for updating an existing candidates list. Adding a little help icon with a note on how this is used would be greatly appreciated.

<img width="1428" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemlqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c1f3611da46e40e3a43714d5082798a60958caf/Screenshot%202024-04-25%20at%2011.58.01%E2%80%AFAM.png" alt="Screenshot 2024-04-25 at 11.58.01 AM.png" />

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1714076332007689)

**Comment by samschlicht** [comment]
Found some doc for the 'fixed' attribute: so, it means, 'not modifiable except by owner':

<img width="604" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemFzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fcf02963ec8ed10b01f14648f6de5fa010f93c5/Screenshot%202024-05-02%20at%2011.30.27%E2%80%AFAM.png" alt="Screenshot 2024-05-02 at 11.30.27 AM.png" />

**Comment by samschlicht** [comment]
Keyboard focusable tooltip:
<img width="1037" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHFzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ca64bd34fdaae1b0aa68b7dc511d8fa4f44a9a4/Screenshot%202024-05-02%20at%2011.55.57%E2%80%AFAM.png" alt="Screenshot 2024-05-02 at 11.55.57 AM.png" />

**Comment by samschlicht** [comment]
Just a note that as part of this PR I've added the styling for this keyboard-focusable tooltip (which is essentially a repurposed button, per bootstrap doc advice) to the admin portal's global styles.scss — previously it was only in the search component stylesheet.
<img width="732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHVzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf9afedbb8a59adeacdb1d4c43c854cc960ba031/Screenshot%202024-05-02%20at%2011.57.34%E2%80%AFAM.png" alt="Screenshot 2024-05-02 at 11.57.34 AM.png" />

**Comment by samschlicht** [comment]
JC has requested it be added to this issue that the 'Fixed?' checkbox not be displayed when the list is a submission list, since those should always be modifiable by others.

It appears that the property denoting this is 'registeredJob':

<img width="743" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1N4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d355a87c85e3d4fb8cb6ca82ea4ff142791f661e/Screenshot%202024-05-03%20at%2011.24.18%E2%80%AFAM.png" alt="Screenshot 2024-05-03 at 11.24.18 AM.png" />

I'll need to check this property when an existing list is being updated. (New list creation will never be for a submission list, since they're created automatically when a job is registered.)

**Comment by samschlicht** [comment]
Fairly straightforward. The server was already sending the registeredJob property but it wasn't in the Angular model — so I added it to the model and then could add this condition check to create-update-list.component:
<img width="452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGl4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8445d0d8c7f1b0fe17373e06ce38b72833942db8/Screenshot%202024-05-03%20at%2012.13.45%E2%80%AFPM.png" alt="Screenshot 2024-05-03 at 12.13.45 PM.png" />

<img width="711" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJ4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d56e986c7cb603290f932bd8bbdf99f21348a280/Screenshot%202024-05-03%20at%2012.37.05%E2%80%AFPM.png" alt="Screenshot 2024-05-03 at 12.37.05 PM.png" />
