### ISSUE TITLE
Simplify menu layouts

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#92]
New Search
- [ ] move the breadcrumb position to top-right above the Save Search Button
- [ ] remove the Home / from the breadcrumb ?
- [x] Use standard buttons look and feel

**Comment by sadatmalik** [comment]
Raised by Zeynep on Trello board -

Improve the menu layouts
Maybe group tabs into key categories: jobs, searches, lists etc?
Hide the unused field

**Comment by zyurdoglu** [comment]
test

**Comment by tbbadmin** [comment]
Main menu tabs - Sub menu tabs

Search - New Search | My Searches | * Searches | Watched Searches
Jobs - New Job | Live Jobs | Partner Jobs | * Jobs 
Candidates - Partner Cases | My Lists | * Lists
Stats - Candidate | Intake | Occupations



User Account drop down menu
Settings
Lists with External Links
