### ISSUE TITLE
Add UNHCR status search filter

### ISSUE THREAD

**Issue by sadatmalik** [talentbeyondboundaries/tbbtalentv2#926]
Add a search criteria that allows selection on candidate's registration status. 

The Welcome Corps at Work program only allows candidates who are UNHCR registered. Filtering on this would make source's and destination's work faster.

[Slack Message](https://refugeejobsmarket.slack.com/archives/C42S4AJ73/p1714399165391329?thread_ts=1714399165.391329&cid=C42S4AJ73)

**Comment by samschlicht** [comment]
I began to implement this using the unhcrRegistered property but see now that it's treated as transient and actually only used to set the unhcrStatus, which is the authoritative source for this info.

**Comment by samschlicht** [comment]
Implemented UNHCR status and all working fine. Just need to add saved search functionality but will check this is the right approach first.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNldpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--817880bb9f686667db50ed64bb562d3de56ee35a/Screenshot%202024-04-30%20at%206.02.25%E2%80%AFPM.png" alt="Screenshot 2024-04-30 at 6.02.25 PM.png" />

**Comment by samschlicht** [comment]
I've sent Caroline message to request a review of my code, as John mentions she may be working in the same area. Notwithstanding her endorsement, this is good to go.
