### ISSUE TITLE
Automated TC message when a candidate is removed from the submission list

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#934]

**Comment by cazcam34** [comment]
Candidates aren't 'removed' but their status is changed to closed. So need to automate message when status changed to a closed status?

**Comment by cazcam34** [comment]
Where to put these chats?
- Job Creator Source Partner
- Candidate Prospect
- Candidate Recruiting
A candidate could be removed at different stages, before the CV reivew (prospect chat) or after the CV review (recruiting chat). However does a chat need to be sent if removed, as it really is just being closed which appears on the stage. Also if we send a chat, it will show as a Chat Unread. This could really fill up the chats for admin portal users?
Also need to consider how we communicate these chats to candidates. A generic candidate xyz has been removed from job abc with the closing stage efg - this could seem harsh? A notification is good for the candidate so they get notified when they are removed, however it does cause a lot of notifications for the TC user as every candidate removed will get a notification which is maybe redundant?

**Comment by cazcam34** [comment]
When updating stages, it is calling the CreateOrUpdate method twice which is then sending twice as many posts. 

<img width="1165" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM25TQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd2451739b406b14de99cbf570a39cfe8bbd65c6/Screen%20Shot%202024-05-13%20at%201.20.28%20pm.png" alt="Screen Shot 2024-05-13 at 1.20.28 pm.png" />

**Comment by cazcam34** [comment]
Wait for PR #1014 to be merged into staging - it posts due to stage changes so this will be similar except a different post if the stage changed to a closed stage.

**Comment by cazcam34** [comment]
Getting this error when trying to connect/update SF: 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40ece05f0acd6731d27caff9a5ba2c595cb6b67b/Screen%20Shot%202024-05-29%20at%2012.56.30%20pm.png" alt="Screen Shot 2024-05-29 at 12.56.30 pm.png" />

**Comment by cazcam34** [comment]
Question:
- Post in multiple places with the same audiences (prospect, recruiting & jscpChat) - do we need to update in all of these?
