### ISSUE TITLE
Remove unused fields of CandidateVisaJobCheckBase: name and sfJoblink

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#964]
See comments in CandidateVisaJobCheckBase

Confirm that we can in fact get rid of these fields and remove them.

Convert old data to populate jobOpp if needed.

**Comment by samschlicht** [comment]
This is a bit of a tricky one in terms of setting the job_opp_id where currently there is none.

The only column that helps us match the candidate_visa_job_check with its intended salesforce_job_opp is 'name'.

There are 20 records returned by this query:
`select cvjc.job_opp_id, cvjc.name, sjo.id, sjo.name
from candidate_visa_job_check cvjc
join salesforce_job_opp sjo on sjo.name like cvjc.name
where cvjc.job_opp_id is null;`

**Comment by samschlicht** [comment]
This query would populate the candidate_visa_job_check.job_opp_id as appropriate:
`UPDATE cvjc
SET 
    cvjc.job_opp_id = sjo.id
FROM candidate_visa_job_check cvjc
JOIN salesforce_job_opp sjo
    ON sjo.name LIKE cvjc.name
    OR cvjc.sf_job_link LIKE '%' || sjo.sf_id || '%'
WHERE cvjc.job_opp_id IS NULL;
`

**Comment by samschlicht** [comment]
All that being said, I'm not sure we should delete 'name' — instead just mark it clearly as deprecated. 64 CVJCs would be without a display name, and this bit of template code would no longer work, to the detriment of what we're able to display:


<img width="925" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWhaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8f126756644e6d7ed864f37ebda90497d9dcead/Screenshot%202024-08-14%20at%204.25.22%E2%80%AFPM.png" alt="Screenshot 2024-08-14 at 4.25.22 PM.png" />


I'll check with the team, but my suggestion would be to:

**Comment by samschlicht** [comment]
There are 88 candidate visa job checks (CVJCs) without a linked job (null value for job_opp_id).

This combined query returns 77 of them:
```
SELECT
    id
FROM (
         SELECT
             cvjc.id
         FROM
             candidate_visa_job_check cvjc
                 JOIN candidate_opportunity co
                      ON co.name LIKE cvjc.name
                          OR cvjc.sf_job_link LIKE '%' || co.sf_id || '%'
         where cvjc.job_opp_id is null
         UNION
         SELECT
             cvjc.id
         FROM
             candidate_visa_job_check cvjc
                 JOIN salesforce_job_opp sjo
                      ON sjo.name LIKE cvjc.name
                          OR cvjc.sf_job_link LIKE '%' || sjo.sf_id || '%'
         where cvjc.job_opp_id is null
     ) combined;
```

I can split this into subqueries to make an update statement that will link the appropriate jobs.

**Comment by samschlicht** [comment]
And this provides the remaining 11 which can't be matched to an existing job via SQL:

```
SELECT
    cvjc.name,
    cvjc.sf_job_link
FROM
    candidate_visa_job_check cvjc
WHERE
    cvjc.job_opp_id IS NULL
  AND cvjc.id NOT IN (
    SELECT
        id
    FROM (
             SELECT
                 cvjc_inner.id
             FROM
                 candidate_visa_job_check cvjc_inner
                     JOIN
                 candidate_opportunity co
                 ON co.name LIKE cvjc_inner.name
                     OR cvjc_inner.sf_job_link LIKE '%' || co.sf_id || '%'
             WHERE
                 cvjc_inner.job_opp_id IS NULL

             UNION

             SELECT
                 cvjc_inner.id
             FROM
                 candidate_visa_job_check cvjc_inner
                     JOIN
                 salesforce_job_opp sjo
                 ON sjo.name LIKE cvjc_inner.name
                     OR cvjc_inner.sf_job_link LIKE '%' || sjo.sf_id || '%'
             WHERE
                 cvjc_inner.job_opp_id IS NULL
         ) combined
);
```

There may be a bit of sleuthing in the TC required to match these to their intended jobs.

**Comment by samschlicht** [comment]
- [x] Link jobs to all possible CVJCs in staging
- [x] Link jobs to all possible CVJCs in prod 
- [x] Remove all front- and back- end references to the deprecated fields
- [x] Make an issue to get rid of the DB columns in the next TC release (#1277)
