### ISSUE TITLE
Option to copy candidate opp next step and due date up to parent job opp

### ISSUE THREAD

**Issue by camerojo** [talentbeyondboundaries/tbbtalentv2#99]
We have the concept of jobs with multiple opportunities (1 to many)
Often one candidate is favoured in to the final stages (1 to 1)
Updating the favoured candidate -> can automatically update the job stage

**Comment by samschlicht** [comment]
![Screenshot 2023-07-18 at 2.42.51 pm.png](https://images.zenhubusercontent.com/64818ed0adecbe758d4abfdb/2e1cbd44-ac15-4556-afb1-3f77c24ea315)

**Comment by samschlicht** [comment]
'Copy next step info to parent job opportunity'

Write separate authservice.ts function that returns boolean whether candidate opportunity is only remaining, in which case component shows checkbox.

**Comment by samschlicht** [comment]
Could be some concern with employer comms -- should it necessarily be easy to show them exactly where we're up to with child candidate opportunity. Might be solved by having a destination partner is employer check.
