### ISSUE TITLE
Spring Lib Upgrade Step 

### ISSUE THREAD

**Issue by ajt001** [talentbeyondboundaries/tbbtalentv2#991]
As a developer 
I want to upgrade to the 6.x version of spring security, and the spring boot 3 version.
In preparation to moving to the current version of spring and minimising the size of the PR delta.

These two versions are done together after upgrading to the spring sec 5.8 as per #974

**Comment by camerojo** [comment]
Currently on:
Spring Boot 2.7.13
Spring Security 5.8.12

https://mvnrepository.com/artifact/org.springframework.boot/spring-boot
https://mvnrepository.com/artifact/org.springframework.security/spring-security-core


### Preparation - factored out into #1610

- [x] Move from javax to jakarta

### Upgrade to Spring Boot 3/Spring Security 6

- [x] Check gradle build against a Spring Initializr with all our dependencies in there. Modify our gradle to bring it into line with standard
- [x] Remove existing security stuff to check that it is not already pulled in by starter (look at the libraries)

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide
https://docs.spring.io/spring-security/reference/6.0/migration/index.html

- [ ] Upgrade to 6.0 security "when upgrading to Spring Boot 3.0" -

**Comment by camerojo** [comment]
### Random guides

- https://lastjavabuilder.medium.com/step-by-step-migration-to-spring-3-x-jakarta-security-hibernate-6-openapi-cache-925401fa7b2c

**Comment by camerojo** [comment]
### Changes to Websocket Security

Deleted org/tctalent/server/configuration/WebSocketSecurityConfig.java and replaced with EnableWebSocketSecurity on TcTalentApplication

See #1034

**Comment by camerojo** [comment]
### Elasticsearch needs a rewrite
No support for REST client which we used.

See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#elasticsearch-clients-and-templates

- [x] Make separate issue - Done #1619

**Comment by camerojo** [comment]
### Javax Email needs a rewrite in EmailSender
Note that simple migration to jakarta email didn't work - see previous issue where we had to back out the jakarta email change.

See https://www.baeldung.com/spring-email

https://docs.spring.io/spring-framework/reference/integration/email.html

- [x] Make separate issue - #1617

**Comment by camerojo** [comment]
### Upgraded from Hibernate 5 to 6
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide
https://thorben-janssen.com/migrating-to-hibernate-6/

### Upgraded from Hibernate 5 Criteria API to JPA 3 Criteria API

https://thorben-janssen.com/migration-criteria-api/
